<?php

/**
 * Legacy (pre-namespace) global class name -> Propulsion\ FQCN map.
 *
 * Generated Object Model classes (both the archived PHP5 builders and the
 * current PHP84 ones) are emitted unnamespaced and reference these runtime
 * classes by their bare historic name (e.g. TableMap, PropelException),
 * because that was their actual global name before this fork renamed
 * Propel\ to Propulsion\. The autoloader registered at the bottom of
 * Propulsion.php uses this to alias them on demand, so already-generated code --
 * and anyone who hasn't regenerated their models yet -- keeps working.
 *
 * @return array<string,string>
 */
return [
    'BaseObject' => 'Propulsion\\OM\\BaseObject',
    'BasePeer' => 'Propulsion\\Util\\BasePeer',
    'BasicValidator' => 'Propulsion\\Validator\\BasicValidator',
    'ColumnMap' => 'Propulsion\\Map\\ColumnMap',
    'Criteria' => 'Propulsion\\Query\\Criteria',
    'Criterion' => 'Propulsion\\Query\\Criterion',
    'CriterionIterator' => 'Propulsion\\Query\\CriterionIterator',
    'DBAdapter' => 'Propulsion\\Adapter\\DBAdapter',
    'DBMSSQL' => 'Propulsion\\Adapter\\DBMSSQL',
    'DBMySQL' => 'Propulsion\\Adapter\\DBMySQL',
    'DBNone' => 'Propulsion\\Adapter\\DBNone',
    'DBOracle' => 'Propulsion\\Adapter\\DBOracle',
    'DBPostgres' => 'Propulsion\\Adapter\\DBPostgres',
    'DBSQLSRV' => 'Propulsion\\Adapter\\DBSQLSRV',
    'DBSQLite' => 'Propulsion\\Adapter\\DBSQLite',
    'DatabaseMap' => 'Propulsion\\Map\\DatabaseMap',
    'DebugPDO' => 'Propulsion\\Connection\\DebugPDO',
    'DebugPDOStatement' => 'Propulsion\\Connection\\DebugPDOStatement',
    'Join' => 'Propulsion\\Query\\Join',
    'MatchValidator' => 'Propulsion\\Validator\\MatchValidator',
    'MaxLengthValidator' => 'Propulsion\\Validator\\MaxLengthValidator',
    'MaxValueValidator' => 'Propulsion\\Validator\\MaxValueValidator',
    'MinLengthValidator' => 'Propulsion\\Validator\\MinLengthValidator',
    'MinValueValidator' => 'Propulsion\\Validator\\MinValueValidator',
    'ModelCriteria' => 'Propulsion\\Query\\ModelCriteria',
    'ModelCriterion' => 'Propulsion\\Query\\ModelCriterion',
    'ModelJoin' => 'Propulsion\\Query\\ModelJoin',
    'ModelWith' => 'Propulsion\\Formatter\\ModelWith',
    'MssqlDebugPDO' => 'Propulsion\\Adapter\\MSSQL\\MssqlDebugPDO',
    'MssqlPropelPDO' => 'Propulsion\\Adapter\\MSSQL\\MssqlPropelPDO',
    'NestedSetRecursiveIterator' => 'Propulsion\\OM\\NestedSetRecursiveIterator',
    'NodeObject' => 'Propulsion\\OM\\NodeObject',
    'NodePeer' => 'Propulsion\\Util\\NodePeer',
    'NotMatchValidator' => 'Propulsion\\Validator\\NotMatchValidator',
    'Persistent' => 'Propulsion\\OM\\Persistent',
    'PreOrderNodeIterator' => 'Propulsion\\OM\\PreOrderNodeIterator',
    'Propel' => 'Propulsion\\Propulsion',
    'PropelArrayCollection' => 'Propulsion\\Collection\\PropelArrayCollection',
    'PropelArrayFormatter' => 'Propulsion\\Formatter\\PropelArrayFormatter',
    'PropelAutoloader' => 'Propulsion\\Util\\PropelAutoloader',
    'PropelCSVParser' => 'Propulsion\\Parser\\PropelCSVParser',
    'PropelCollection' => 'Propulsion\\Collection\\PropelCollection',
    'PropelColumnTypes' => 'Propulsion\\Util\\PropelColumnTypes',
    'PropelConditionalProxy' => 'Propulsion\\Util\\PropelConditionalProxy',
    'PropelConfiguration' => 'Propulsion\\Config\\PropelConfiguration',
    'PropelConfigurationIterator' => 'Propulsion\\Config\\PropelConfigurationIterator',
    'PropelDateTime' => 'Propulsion\\Util\\PropelDateTime',
    'PropelException' => 'Propulsion\\Exception\\PropelException',
    'PropelFormatter' => 'Propulsion\\Formatter\\PropelFormatter',
    'PropelJSONParser' => 'Propulsion\\Parser\\PropelJSONParser',
    'PropelModelPager' => 'Propulsion\\Util\\PropelModelPager',
    'PropelObjectCollection' => 'Propulsion\\Collection\\PropelObjectCollection',
    'PropelObjectFormatter' => 'Propulsion\\Formatter\\PropelObjectFormatter',
    'PropelOnDemandCollection' => 'Propulsion\\Collection\\PropelOnDemandCollection',
    'PropelOnDemandFormatter' => 'Propulsion\\Formatter\\PropelOnDemandFormatter',
    'PropelOnDemandIterator' => 'Propulsion\\Collection\\PropelOnDemandIterator',
    'PropelPDO' => 'Propulsion\\Connection\\PropelPDO',
    'PropelPager' => 'Propulsion\\Util\\PropelPager',
    'PropelParser' => 'Propulsion\\Parser\\PropelParser',
    'PropelQuery' => 'Propulsion\\Query\\PropelQuery',
    'PropelSimpleArrayFormatter' => 'Propulsion\\Formatter\\PropelSimpleArrayFormatter',
    'PropelStatementFormatter' => 'Propulsion\\Formatter\\PropelStatementFormatter',
    'PropelXMLParser' => 'Propulsion\\Parser\\PropelXMLParser',
    'PropelYAMLParser' => 'Propulsion\\Parser\\PropelYAMLParser',
    'RelationMap' => 'Propulsion\\Map\\RelationMap',
    'RequiredValidator' => 'Propulsion\\Validator\\RequiredValidator',
    'TableMap' => 'Propulsion\\Map\\TableMap',
    'TypeValidator' => 'Propulsion\\Validator\\TypeValidator',
    'UniqueValidator' => 'Propulsion\\Validator\\UniqueValidator',
    'ValidValuesValidator' => 'Propulsion\\Validator\\ValidValuesValidator',
    'ValidationFailed' => 'Propulsion\\Validator\\ValidationFailed',
    'ValidatorMap' => 'Propulsion\\Map\\ValidatorMap',
];
