<?php

/**
 * This file is part of the Propulsion package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propulsion\Generator\Builder\OM;

/**
 * Generates the empty PHP 8.4 stub peer class for user object model (OM).
 *
 * This class produces the empty stub peer class that can be customized with application
 * business logic, custom behavior, etc. Using modern PHP 8.4 features.
 *
 * @author     Modernized for PHP 8.4
 * @package    propel.generator.builder.om
 */
class ExtensionPeerBuilder extends AbstractPeerBuilder
{
    /**
     * Returns the name of the current class being built.
     * Inlined from the (now-archived) PHP5ExtensionPeerBuilder base -- this class no
     * longer extends it (see KNOWN_ISSUES.md, PHP5 removal).
     * @return     string
     */
    public function getUnprefixedClassname()
    {
        return $this->getStubObjectBuilder()->getUnprefixedClassname() . 'Peer';
    }

    /**
     * Closes class.
     * Inlined from the (now-archived) PHP5ExtensionPeerBuilder base.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addClassClose(&$script)
    {
        $script .= "
} // " . $this->getClassname() . "
";
        $this->applyBehaviorModifier('extensionPeerFilter', $script, "");
    }

    /**
     * Adds the include() statements for files that this class depends on or utilizes.
     * For PHP 8.4, we use autoloading instead of require statements.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addIncludes(&$script = null)
    {
        // PHP 8.4 uses namespaces and autoloading, so no require statements needed
    }

    /**
     * Adds class phpdoc comment and opening of class with modern PHP 8.4 features.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addClassOpen(&$script): void
    {
        $table = $this->getTable();
        $this->declareClassFromBuilder($this->getPeerBuilder());
        $tableName = $table->getName();
        $tableDesc = $table->getDescription();

        switch ($table->treeMode()) {
            case 'NestedSet':
                $this->declareClassFromBuilder($this->getNestedSetPeerBuilder());
                $baseClassname = $this->getNestedSetPeerBuilder()->getClassname();
                break;
            case 'MaterializedPath':
            case 'AdjacencyList':
            default:
                $baseClassname = $this->getPeerBuilder()->getClassname();
                break;
        }

        $script .= "

/**
 * Skeleton subclass for performing query and update operations on the '$tableName' table.
 *
 * $tableDesc
 *";
        if ($this->getBuildProperty('addTimeStamp')) {
            $now = datefmt_create(
                'en_US',
                \IntlDateFormatter::FULL,
                \IntlDateFormatter::FULL,
                'Europe/Helsinki',
                \IntlDateFormatter::GREGORIAN,
                "yyyy-MM-dd HH:mm:ss"
            );
            $script .= "
 * This class was autogenerated by Propulsion " . $this->getBuildProperty('version') . " on:
 *
 * " . datefmt_format($now, 0) . "
 *";
        }
        $script .= "
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.".$this->getPackage()."
 */
class ".$this->getClassname()." extends ".$baseClassname."
{
";
    }

    /**
     * Specifies the methods that are added as part of the stub peer class.
     *
     * By default there are no methods for the empty stub classes; override this method
     * if you want to change that behavior with modern PHP 8.4 patterns.
     *
     * @see        PeerBuilder::addClassBody()
     */
    protected function addClassBody(&$script): void
    {
        $this->addStubMethods($script);
        $this->applyBehaviorModifier('peerStubMethods', $script, "    ");
    }

    /**
     * Adds example modern static methods for the stub peer class.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addStubMethods(&$script): void
    {
        $objectClass = $this->getStubObjectBuilder()->getClassname();
        
        $script .= "
    /**
     * Example of a modern static method with proper type hints and return types.
     * 
     * @param array<string, mixed> \$criteria
     * @param ?PropulsionPDO \$con
     * @return array<$objectClass>
     */
    // public static function findByCustomCriteria(array \$criteria, ?PropulsionPDO \$con = null): array
    // {
    //     \$c = new Criteria();
    //     foreach (\$criteria as \$field => \$value) {
    //         \$c->add(constant('self::' . strtoupper(\$field)), \$value);
    //     }
    //     return self::doSelect(\$c, \$con);
    // }

    /**
     * Example of a method with union types for flexible input.
     * 
     * @param Criteria|array<string, mixed> \$criteria
     * @param ?PropulsionPDO \$con
     * @return int
     */
    // public static function countByCriteria(Criteria|array \$criteria, ?PropulsionPDO \$con = null): int
    // {
    //     if (is_array(\$criteria)) {
    //         \$c = new Criteria();
    //         foreach (\$criteria as \$field => \$value) {
    //             \$c->add(constant('self::' . strtoupper(\$field)), \$value);
    //         }
    //         \$criteria = \$c;
    //     }
    //     return self::doCount(\$criteria, \$con);
    // }

    /**
     * Example of a method using match expressions for cleaner conditionals.
     * 
     * @param string \$status
     * @param ?PropulsionPDO \$con
     * @return array<$objectClass>
     */
    // public static function findByStatus(string \$status, ?PropulsionPDO \$con = null): array
    // {
    //     \$criteria = new Criteria();
    //     \$statusValue = match(\$status) {
    //         'active' => 1,
    //         'inactive' => 0,
    //         'pending' => 2,
    //         default => throw new \\InvalidArgumentException('Invalid status: ' . \$status)
    //     };
    //     
    //     \$criteria->add(self::STATUS, \$statusValue);
    //     return self::doSelect(\$criteria, \$con);
    // }

    /**
     * Example of a method with readonly array return type annotation.
     * 
     * @return array{total: int, active: int, inactive: int}
     */
    // public static function getStatusCounts(): array
    // {
    //     \$total = self::doCount(new Criteria());
    //     \$activeCriteria = new Criteria();
    //     \$activeCriteria->add(self::STATUS, 1);
    //     \$active = self::doCount(\$activeCriteria);
    //     
    //     \$inactiveCriteria = new Criteria();
    //     \$inactiveCriteria->add(self::STATUS, 0);
    //     \$inactive = self::doCount(\$inactiveCriteria);
    //     
    //     return [
    //         'total' => \$total,
    //         'active' => \$active,
    //         'inactive' => \$inactive
    //     ];
    // }

    /**
     * Example of a method using modern null coalescing and array destructuring.
     * 
     * @param array{limit?: int, offset?: int, order?: string} \$options
     * @param ?PropulsionPDO \$con
     * @return array<$objectClass>
     */
    // public static function findWithOptions(array \$options = [], ?PropulsionPDO \$con = null): array
    // {
    //     \$limit = \$options['limit'] ?? 100;
    //     \$offset = \$options['offset'] ?? 0;
    //     \$order = \$options['order'] ?? 'ASC';
    //     
    //     \$criteria = new Criteria();
    //     \$criteria->setLimit(\$limit);
    //     \$criteria->setOffset(\$offset);
    //     \$criteria->addAscendingOrderByColumn(self::ID);
    //     
    //     if (\$order === 'DESC') {
    //         \$criteria->addDescendingOrderByColumn(self::ID);
    //     }
    //     
    //     return self::doSelect(\$criteria, \$con);
    // }
";
    }
}