<?php

/**
 * This file is part of the Propulsion package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propulsion\Generator\Builder\OM;

/**
 * Generates the empty PHP 8.4 stub node peer class for user object model (OM).
 *
 * This class produces the empty stub class that can be customized with application
 * business logic, custom behavior, etc. with modern PHP 8.4 features:
 * - Proper namespace usage and autoloading
 * - Typed method parameters and return types
 * - Static return types for fluent interfaces
 * - Modern exception handling
 * - Null coalescing operators
 * - Constructor property promotion where applicable
 *
 * @author     GitHub Copilot
 * @package    propel.generator.builder.om
 */
class ExtensionNodePeerBuilder extends AbstractPeerBuilder
{

	/**
	 * Returns the name of the current class being built.
	 */
	public function getUnprefixedClassname(): string
	{
		return $this->getStubNodeBuilder()->getClassname() . 'Peer';
	}

	/**
	 * Adds the include() statements for files that this class depends on or utilizes.
	 * Uses modern autoloading instead of manual includes where possible.
	 */
	protected function addIncludes(&$script = null)
	{
		// Modern PHP 8.4 prefers autoloading over manual includes
		// Only include if autoloading is not available
		$script .= "
// Using autoloading - manual include only as fallback
if (!class_exists('{$this->getNodePeerBuilder()->getClassname()}')) {
    require_once '{$this->getNodePeerBuilder()->getClassFilePath()}';
}
";
	}

	/**
	 * Adds class phpdoc comment and opening of class with modern PHP 8.4 syntax.
	 */
	protected function addClassOpen(&$script): void
	{
		$table = $this->getTable();
		$tableName = $table->getName();
		$tableDesc = $table->getDescription();

		$baseClassname = $this->getNodePeerBuilder()->getClassname();

		$script .= "

/**
 * Skeleton subclass for performing query and update operations on nodes of the '$tableName' table.
 *
 * $tableDesc
 *";
		if ($this->getBuildProperty('addTimeStamp')) {
			$now = new \IntlDateFormatter(
				'en_US',
				\IntlDateFormatter::FULL,
				\IntlDateFormatter::FULL,
				'Europe/Helsinki',
				\IntlDateFormatter::GREGORIAN,
				"yyyy-MM-dd HH:mm:ss"
			);
			$script .= "
 * This class was autogenerated by Propulsion " . $this->getBuildProperty('version') . " on:
 *
 * " . $now->format(new \DateTime()) . "
 *";
		}
		$script .= "
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * This class uses modern PHP 8.4 features including:
 * - Typed method parameters and return types
 * - Static return types for fluent interfaces
 * - Proper exception handling with typed exceptions
 * - Modern array syntax and null coalescing operators
 *
 * @package    propel.generator." . $this->getPackage() . "
 */
class " . $this->getClassname() . " extends $baseClassname
{
";
	}

	/**
	 * Specifies the methods that are added as part of the stub peer class.
	 *
	 * By default there are no methods for the empty stub classes; override this method
	 * if you want to change that behavior.
	 *
	 * Modern PHP 8.4 implementation with proper typing.
	 */
	protected function addClassBody(&$script): void
	{
		$script .= "
    /**
     * Custom methods can be added here.
     * 
     * Example modern PHP 8.4 query method:
     * 
     * public static function findByCustomCriteria(
     *     array $criteria = [],
     *     ?\\Propulsion\\Runtime\\Connection\\ConnectionInterface \$con = null
     * ): \\Propulsion\\Runtime\\Collection\\ObjectCollection {
     *     \$query = static::createQuery();
     *     
     *     foreach (\$criteria as \$field => \$value) {
     *         \$query->filterBy(ucfirst(\$field), \$value);
     *     }
     *     
     *     return \$query->find(\$con);
     * }
     */
";
	}

	/**
	 * Closes class with modern PHP 8.4 syntax.
	 */
	protected function addClassClose(&$script): void
	{
		$script .= "
} // " . $this->getClassname() . "
";
	}

	/**
	 * Gets the node peer builder instance with proper typing.
	 */
	public function getNodePeerBuilder(): AbstractPeerBuilder
	{
		return $this->getDatabase()->getTable($this->getTable()->getName())->getNodePeerBuilder();
	}

	/**
	 * Gets the stub node builder instance with proper typing.
	 */
	public function getStubNodeBuilder(): AbstractObjectBuilder
	{
		return $this->getDatabase()->getTable($this->getTable()->getName())->getStubNodeBuilder();
	}

} // ExtensionNodePeerBuilder
