<?php

/**
 * This file is part of the Propulsion package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propulsion\Generator\Builder\OM;

/**
 * Generates the empty PHP 8.4 stub object class for user object model (OM).
 *
 * This class produces the empty stub class that can be customized with application
 * business logic, custom behavior, etc. Using modern PHP 8.4 features.
 *
 * @author     Modernized for PHP 8.4
 */
class ExtensionObjectBuilder extends AbstractObjectBuilder
{

    /**
     * Returns the name of the current class being built.
     * Inlined from the (now-archived) PHP5ExtensionObjectBuilder base -- this class no
     * longer extends it (see KNOWN_ISSUES.md, PHP5 removal).
     * @return     string
     */
    public function getUnprefixedClassname()
    {
        return $this->getTable()->getPhpName();
    }

    /**
     * Closes class.
     * Inlined from the (now-archived) PHP5ExtensionObjectBuilder base.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addClassClose(&$script)
    {
        $script .= "
} // " . $this->getClassname() . "
";
        $this->applyBehaviorModifier('extensionObjectFilter', $script, "");
    }

    protected function addIncludes(&$script = null)
    {
        // PHP 8.4 uses namespaces and autoloading, so includes are minimal
        // No need to include parent class files as they are autoloaded
        // This method can be left empty or used for specific includes if needed
    }
    /**
     * Adds class phpdoc comment and opening of class with modern PHP 8.4 features.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addClassOpen(&$script): void
    {
        $table = $this->getTable();
        $this->declareClassFromBuilder($this->getObjectBuilder());
        $tableName = $table->getName();
        $tableDesc = $table->getDescription();

        switch($table->treeMode()) {
            case 'NestedSet':
                $baseClassname = $this->getNestedSetBuilder()->getClassname();
                break;
            case 'MaterializedPath':
            case "AdjacencyList":
            default:
                $baseClassname = $this->getObjectBuilder()->getClassname();
                break;
        }

        $script .= "

/**
 * Skeleton subclass for representing a row from the '$tableName' table.
 *
 * $tableDesc
 *";
        if ($this->getBuildProperty('addTimeStamp')) {
            $now = datefmt_create(
                'en_US',
                \IntlDateFormatter::FULL,
                \IntlDateFormatter::FULL,
                'Europe/Helsinki',
                \IntlDateFormatter::GREGORIAN,
                "yyyy-MM-dd HH:mm:ss"
            );
            $script .= "
 * This class was autogenerated by Propulsion " . $this->getBuildProperty('version') . " on:
 *
 * " . datefmt_format($now, time()) . "
 *";
        }
        $script .= "
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 */
class ".$this->getClassname()." extends $baseClassname
{
";
    }

    /**
     * Specifies the methods that are added as part of the stub object class.
     *
     * By default there are no methods for the empty stub classes; override this method
     * if you want to change that behavior with modern PHP 8.4 patterns.
     *
     * @see        ObjectBuilder::addClassBody()
     */
    protected function addClassBody(&$script): void
    {
        // Declare the base object class for inheritance
        $this->declareClassFromBuilder($this->getNewObjectBuilder($this->getTable()));

        $this->addStubConstructor($script);
        $this->addStubMethods($script);
        $this->applyBehaviorModifier('objectStubMethods', $script, "    ");
    }

    /**
     * Adds a modern constructor example for the stub class.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addStubConstructor(&$script): void
    {
        $script .= "
    /**
     * Constructor with optional initialization.
     * 
     * Example of modern PHP 8.4 constructor with property promotion:
     * 
     * public function __construct(
     *     ?string \$name = null,
     *     ?int \$age = null,
     *     ?\DateTime \$createdAt = null
     * ) {
     *     parent::__construct();
     *     if (\$name !== null) \$this->setName(\$name);
     *     if (\$age !== null) \$this->setAge(\$age);
     *     if (\$createdAt !== null) \$this->setCreatedAt(\$createdAt);
     * }
     */
";
    }

    /**
     * Adds example modern methods for the stub class.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addStubMethods(&$script): void
    {
        $script .= "
    /**
     * Example of a modern method with proper type hints and return types.
     * 
     * @param array<string, mixed> \$data
     * @return static
     */
    // public function fromArray(array \$data): static
    // {
    //     foreach (\$data as \$key => \$value) {
    //         \$method = 'set' . ucfirst(\$key);
    //         if (method_exists(\$this, \$method)) {
    //             \$this->\$method(\$value);
    //         }
    //     }
    //     return \$this;
    // }

    /**
     * Example of a method with union types (PHP 8.0+).
     * 
     * @param string|int \$identifier
     * @return bool
     */
    // public function matchesIdentifier(string|int \$identifier): bool
    // {
    //     return match(true) {
    //         is_string(\$identifier) => \$this->getName() === \$identifier,
    //         is_int(\$identifier) => \$this->getId() === \$identifier,
    //         default => false
    //     };
    // }

    /**
     * Example of a method using readonly properties pattern.
     * 
     * @return array<string, mixed>
     */
    // public function toReadonlyArray(): array
    // {
    //     return [
    //         'id' => \$this->getId(),
    //         'name' => \$this->getName(),
    //         'created_at' => \$this->getCreatedAt()?->format('Y-m-d H:i:s'),
    //         'updated_at' => \$this->getUpdatedAt()?->format('Y-m-d H:i:s'),
    //     ];
    // }
";
    }
}