<?php

/**
 * This file is part of the Propulsion package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propulsion\Generator\Builder\OM;

/**
 * Generates the empty PHP 8.4 stub interface for user object model (OM).
 *
 * This class produces the empty stub interface when the interface="" attribute is used
 * in the schema xml, with modern PHP 8.4 features:
 * - Proper namespace declarations
 * - Modern doc comments with typed parameters
 * - Attributes support
 * - Readonly interface contracts where applicable
 *
 * @author     GitHub Copilot
 */
class InterfaceBuilder extends AbstractObjectBuilder
{

	/**
	 * Returns the name of the current class being built.
	 * @return     string
	 */
	public function getUnprefixedClassname(): string
	{
		return ClassTools::classname($this->getInterface());
	}

	/**
	 * Adds the include() statements for files that this class depends on or utilizes.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addIncludes(&$script = null)
	{
		// PHP 8.4 uses namespaces and autoloading, so includes are minimal
	}

	/**
	 * Adds class phpdoc comment and opening of interface.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassOpen(&$script): void
	{
		$table = $this->getTable();
		$tableName = $table->getName();
		$tableDesc = $table->getDescription();

		$script .= "
/**
 * Interface for $tableName objects with modern PHP 8.4 features.
 *
 * $tableDesc
 *";
		if ($this->getBuildProperty('addTimeStamp')) {
			$now = datefmt_create(
				'en_US',
				\IntlDateFormatter::FULL,
				\IntlDateFormatter::FULL,
				'Europe/Helsinki',
				\IntlDateFormatter::GREGORIAN,
				"yyyy-MM-dd HH:mm:ss"
			);
			$script .= "
 * This interface was autogenerated by Propulsion " . $this->getBuildProperty('version') . " on:
 *
 * " . datefmt_format($now, time()) . "
 *";
		}
		$script .= "
 * You should add additional method declarations to this interface to meet the
 * application requirements. This interface will only be generated as
 * long as it does not already exist in the output directory.
 *
 */
interface ".$this->getClassname()."
{
";
	}

	/**
	 * Specifies the methods that are added as part of the stub interface.
	 *
	 * By default there are no methods for the empty stub interfaces; override this method
	 * if you want to change that behavior.
	 *
	 * @see        AbstractObjectBuilder::addClassBody()
	 */
	protected function addClassBody(&$script): void
	{
		// Interface body is intentionally empty for stub interfaces
	}

	/**
	 * Closes interface definition.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassClose(&$script): void
	{
		$script .= "
}
";
	}

	public function build(): string
	{
		$script = '';
		
		if ($this->getNamespace()) {
			$script .= "<?php

namespace " . $this->getNamespace() . ";

";
		} else {
			$script .= "<?php

";
		}

		$this->addClassOpen($script);
		$this->addClassBody($script);
		$this->addClassClose($script);

		return $script;
	}
}
