<?php

/**
 * This file is part of the Propulsion package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propulsion\Generator\Builder\OM;

/**
 * Generates the empty PHP 8.4 stub object class for use with inheritance in the user object model (OM).
 *
 * This class produces the empty stub class that can be customized with application
 * business logic, custom behavior, etc. with modern PHP 8.4 features:
 * - Proper namespace usage
 * - Typed properties and methods
 * - Constructor property promotion where applicable
 * - Modern inheritance patterns
 *
 * @author     GitHub Copilot
 */
use Propulsion\Generator\Model\Inheritance;
use Propulsion\Generator\Exception\EngineException;

class MultiExtendObjectBuilder extends AbstractObjectBuilder
{

	/**
	 * The current child "object" we are operating on.
	 */
	private ?Inheritance $child = null;

	/**
	 * Returns the name of the current class being built.
	 * @return     string
	 */
	public function getUnprefixedClassname(): string
	{
		$child = $this->getChild();
		$className = $child->getClassName();
		if ($className === null) {
			throw new EngineException("The child Inheritance set via setChild() has no class name (missing 'class' attribute).");
		}
		return $className;
	}

	/**
	 * Override method to return child package, if specified.
	 * @return     string
	 */
	public function getPackage(): string
	{
		return $this->child?->getPackage() ?: parent::getPackage();
	}

	/**
	 * Set the child object that we're operating on currently.
	 * @param      Inheritance $child
	 */
	public function setChild(Inheritance $child): void
	{
		$this->child = $child;
	}

	/**
	 * Returns the child object we're operating on currently.
	 * @return     Inheritance
	 * @throws     EngineException - if child was not set.
	 */
	public function getChild(): Inheritance
	{
		if (!$this->child) {
			throw new EngineException("The MultiExtendObjectBuilder needs to be told which child class to build (via setChild() method) before it can build the stub class.");
		}
		return $this->child;
	}

	/**
	 * Returns classpath to parent class.
	 *
	 * A bare `extends="Foo"` (no namespace separator) is left untouched and
	 * resolves via PHP's normal unqualified-name lookup against the
	 * generated file's own namespace -- correct as long as ancestor and
	 * child share a namespace, same as before this method existed.
	 * `extends="Foo\Bar\Baz"` is normalized to an absolute reference
	 * (leading `\`): PHP treats a *relative*-qualified name (one with a
	 * `\` but no leading `\`) as rooted at the *current* namespace, not the
	 * global namespace, so without this normalization a schema author
	 * naming a genuinely different namespace would silently generate
	 * `class Child extends CurrentNamespace\Foo\Bar\Baz` -- the wrong
	 * class (or a "class not found" error), not the one they wrote.
	 * @return     string
	 */
	protected function getParentClasspath(): string
	{
		$ancestor = $this->getChild()->getAncestor();
		if (!$ancestor) {
			return $this->getObjectBuilder()->getClasspath();
		}
		if (str_contains($ancestor, '\\')) {
			return '\\' . ltrim($ancestor, '\\');
		}
		return $ancestor;
	}

	/**
	 * Returns classname of parent class.
	 * @return     string
	 */
	protected function getParentClassname(): string
	{
		return ClassTools::classname($this->getParentClasspath());
	}

	/**
	 * Gets the file path to the parent class.
	 * @return     string
	 */
	protected function getParentClassFilePath(): string
	{
		return ClassTools::getFilePath($this->getParentClasspath());
	}

	/**
	 * Adds the include() statements for files that this class depends on or utilizes.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addIncludes(&$script = null): void
	{
		// PHP 8.4 uses namespaces and autoloading, so includes are minimal
	}

	/**
	 * Adds class phpdoc comment and opening of class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassOpen(&$script): void
	{
		$table = $this->getTable();
		$tableName = $table->getName();
		$tableDesc = $table->getDescription();
		
		$script .= "
/**
 * Stub child class for representing a row from the '$tableName' table.
 *
 * $tableDesc
 *";
		if ($this->getBuildProperty('addTimeStamp')) {
			$now = datefmt_create(
				'en_US',
				\IntlDateFormatter::FULL,
				\IntlDateFormatter::FULL,
				'Europe/Helsinki',
				\IntlDateFormatter::GREGORIAN,
				"yyyy-MM-dd HH:mm:ss"
			);
			if (!$now) {
				throw new EngineException("Failed to create IntlDateFormatter for the generated-class timestamp comment.");
			}
			$version = $this->getBuildProperty('version');
			if (!is_string($version)) {
				throw new EngineException("The 'version' build property must be a string.");
			}
			$script .= "
 * This class was autogenerated by Propulsion " . $version . " on:
 *
 * " . datefmt_format($now, 0) . "
 *";
		}
		$script .= "
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 */
class ".$this->getClassname()." extends ".$this->getParentClassname()."
{
";
	}

	/**
	 * Specifies the methods that are added as part of the stub object class.
	 *
	 * Adds a constructor that sets the single-table-inheritance discriminator
	 * column to this child's CLASSKEY_* value -- without it, every instance
	 * (regardless of which child class was instantiated) would persist with
	 * the column's schema default, and querying for a specific child class
	 * would never match any row.
	 *
	 * @see        AbstractObjectBuilder::addClassBody()
	 */
	protected function addClassBody(&$script): void
	{
		$this->declareClassFromBuilder($this->getStubPeerBuilder());
		$child = $this->getChild();
		$col = $child->getColumn();
		$key = $child->getKey();
		if (!$col || $key === null) {
			throw new EngineException("Inheritance child '" . $child->getClassName() . "' has no discriminator column/key set -- addInheritance() should have set both before this builder ever runs.");
		}
		$cfc = $col->getPhpName();
		$const = "CLASSKEY_" . strtoupper($key);
		$classKeyExpr = $this->getPeerClassname() . "::$const";
		// The Peer's CLASSKEY_* constants are always declared as string literals
		// (PeerBuilder::addInheritanceColumnConstants(), regardless of the discriminator
		// column's actual type), but set<Column>()'s native parameter type matches the
		// column's real type (e.g. int for an INTEGER column) -- cast here so the value
		// handed to the setter actually matches what it declares.
		if ($col->isNumericType()) {
			$phpType = $col->getPhpType();
			$castType = match ($phpType) { 'double' => 'float', 'integer' => 'int', default => $phpType };
			$classKeyExpr = "($castType) $classKeyExpr";
		}

		$script .= "
	/**
	 * Constructs a new " . $this->getChild()->getClassname() . " class, setting the " . $col->getName() . " column to " . $this->getPeerClassname() . "::$const.
	 */
	public function __construct()
	{
		parent::__construct();
		\$this->set$cfc($classKeyExpr);
	}
";
	}

	/**
	 * Closes class definition.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassClose(&$script): void
	{
		$script .= "
}
";
	}

	public function build(): string
	{
		$script = '';
		
		if ($this->getNamespace()) {
			$script .= "<?php

namespace " . $this->getNamespace() . ";

";
		} else {
			$script .= "<?php

";
		}

		$this->addClassOpen($script);
		$this->addClassBody($script);
		$this->addClassClose($script);

		return $script;
	}
}
