<?php

/**
 * This file is part of the Propulsion package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propulsion\Generator\Builder\OM;

/**
 * Generates a PHP 8.4 tree nested set Peer class for user object model (OM).
 *
 * This class produces the base tree nested set peer class (e.g. BaseMyTableNestedSetPeer) which contains all
 * the custom-built query and manipulation methods with modern PHP 8.4 features:
 * - Static typed methods for tree operations
 * - Proper return types and parameter types
 * - Modern array operations and null coalescing
 * - Exception handling with typed exceptions
 *
 * @author     GitHub Copilot
 * @package    propel.generator.builder.om
 */
use Propulsion\Generator\Exception\EngineException;

class NestedSetPeerBuilder extends AbstractPeerBuilder
{

	/**
	 * Gets the package for the [base] object classes.
	 * @return     string
	 */
	public function getPackage(): string
	{
		return parent::getPackage() . ".om";
	}

	public function getNamespace(): ?string
	{
		if ($namespace = parent::getNamespace()) {
			if ($this->getGeneratorConfig() && $omns = $this->getGeneratorConfig()->getBuildProperty('namespaceOm')) {
				return $namespace . '\\' . $omns;
			} else {
				return $namespace;
			}
		}
		return null;
	}

	/**
	 * Returns the name of the current class being built.
	 * @return     string
	 */
	public function getUnprefixedClassname(): string
	{
		return $this->getBuildProperty('basePrefix') . $this->getStubObjectBuilder()->getUnprefixedClassname() . 'NestedSetPeer';
	}

	/**
	 * Adds the include() statements for files that this class depends on or utilizes.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addIncludes(&$script = null)
	{
		// PHP 8.4 uses namespaces and autoloading, so includes are minimal
	}

	/**
	 * Adds class phpdoc comment and opening of class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassOpen(&$script): void
	{
		$table = $this->getTable();
		$tableName = $table->getName();
		$tableDesc = $table->getDescription();

		$script .= "
/**
 * Base static class for performing query operations on the tree contained by the '$tableName' table.
 *
 * $tableDesc
 *";
		if ($this->getBuildProperty('addTimeStamp')) {
			$now = datefmt_create(
				'en_US',
				\IntlDateFormatter::FULL,
				\IntlDateFormatter::FULL,
				'Europe/Helsinki',
				\IntlDateFormatter::GREGORIAN,
				"yyyy-MM-dd HH:mm:ss"
			);
			$script .= "
 * This class was autogenerated by Propulsion " . $this->getBuildProperty('version') . " on:
 *
 * " . datefmt_format($now, 0) . "
 *";
		}
		$script .= "
 * @deprecated  Since Propulsion 1.5. Use the nested_set behavior instead of the NestedSet treeMode
 * @package    propel.generator.".$this->getPackage()."
 */
abstract class ".$this->getClassname()." extends ".$this->getPeerBuilder()->getClassName()." implements NodePeer
{
";
	}

	/**
	 * Specifies the methods that are added as part of the basic OM class.
	 * This can be overridden by subclasses that wish to add more methods.
	 * @see        AbstractObjectBuilder::addClassBody()
	 */
	protected function addClassBody(&$script): void
	{
		$this->addConstants($script);
		$this->addGetTree($script);
		$this->addRetrieveRoot($script);
		$this->addRetrieveTree($script);
		$this->addIsValid($script);
		$this->addDeleteTree($script);
		$this->addShiftLevel($script);
		$this->addShiftRLValues($script);
		$this->addShiftRLRange($script);
		$this->addMakeRoomForLeaf($script);
		$this->addFixLevels($script);
		$this->addGetMaxRight($script);
		$this->addGetLastScope($script);
	}

	/**
	 * Closes class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassClose(&$script): void
	{
		$script .= "
}
";
	}

	/**
	 * Adds class constants for tree operations.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addConstants(&$script): void
	{
		$script .= "
	/**
	 * Tree structure operation constants
	 */
	public const MOVE_UP = 1;
	public const MOVE_DOWN = 2;
	public const MOVE_LEFT = 3;
	public const MOVE_RIGHT = 4;
";
	}

	/**
	 * Adds getTree method with modern PHP 8.4 features.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addGetTree(&$script): void
	{
		$script .= "
	/**
	 * Get the tree structure as an array
	 */
	public static function getTree(?int \$scope = null): array
	{
		\$criteria = new Criteria();
		if (\$scope !== null) {
			\$criteria->add(static::SCOPE_COL, \$scope);
		}
		\$criteria->addAscendingOrderByColumn(static::LEFT_COL);
		
		return static::doSelect(\$criteria);
	}
";
	}

	// Placeholder methods - in a complete implementation, these would contain
	// the full modernized logic from the PHP5 version
	protected function addRetrieveRoot(&$script): void { /* Implementation */ }
	protected function addRetrieveTree(&$script): void { /* Implementation */ }
	protected function addIsValid(&$script): void { /* Implementation */ }
	protected function addDeleteTree(&$script): void { /* Implementation */ }
	protected function addShiftLevel(&$script): void { /* Implementation */ }
	protected function addShiftRLValues(&$script): void { /* Implementation */ }
	protected function addShiftRLRange(&$script): void { /* Implementation */ }
	protected function addMakeRoomForLeaf(&$script): void { /* Implementation */ }
	protected function addFixLevels(&$script): void { /* Implementation */ }
	protected function addGetMaxRight(&$script): void { /* Implementation */ }
	protected function addGetLastScope(&$script): void { /* Implementation */ }
}
