<?php

/**
 * This file is part of the Propulsion package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propulsion\Generator\Builder\OM;

/**
 * Generates a PHP 8.4 tree node Object class for user object model (OM) using Nested Set approach.
 *
 * This class produces the base tree node object class (e.g. BaseMyTableNestedSet) which contains all
 * the custom-built accessor and setter methods with modern PHP 8.4 features:
 * - Typed properties for tree structure data
 * - Readonly properties where appropriate
 * - Proper return types and parameter types
 * - Null coalescing operators
 * - Modern exception handling
 *
 * @author     GitHub Copilot
 */
class NestedSetBuilder extends AbstractObjectBuilder
{

	/**
	 * Gets the package for the [base] object classes.
	 * @return     string
	 */
	public function getPackage(): string
	{
		return parent::getPackage() . "." . $this->getOmPackageSegment();
	}

	public function getNamespace(): ?string
	{
		if ($namespace = parent::getNamespace()) {
			if ($omns = $this->getGeneratorConfig()->getBuildProperty('namespaceOm')) {
				return $namespace . '\\' . $omns;
			} else {
				return $namespace;
			}
		}
		return null;
	}

	/**
	 * Returns the name of the current class being built.
	 * @return     string
	 */
	public function getUnprefixedClassname(): string
	{
		return $this->getBuildProperty('basePrefix') . $this->getStubObjectBuilder()->getUnprefixedClassname() . 'NestedSet';
	}

	/**
	 * Adds the include() statements for files that this class depends on or utilizes.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addIncludes(&$script = null)
	{
		// PHP 8.4 uses namespaces and autoloading, but the generated code below still
		// references these short class names, so they must be declared here for the
		// framework to auto-generate the corresponding `use` statements (see
		// OMBuilder::declareClass()/getUseStatements()).
		$this->declareClass('Propulsion\\Connection\\PropulsionPDO');
		$this->declareClass('Propulsion\\OM\\NodeObject');
		$this->declareClass('Propulsion\\OM\\NestedSetRecursiveIterator');
		$this->declareClass('Propulsion\\Exception\\PropulsionException');
	}

	/**
	 * Adds class phpdoc comment and opening of class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassOpen(&$script): void
	{
		$table = $this->getTable();
		$tableName = $table->getName();
		$tableDesc = $table->getDescription();

		$script .= "
/**
 * Base class that represents a row from the '$tableName' table with nested set behavior.
 *
 * $tableDesc
 *";
		if ($this->getBuildProperty('addTimeStamp')) {
			$now = datefmt_create(
				'en_US',
				\IntlDateFormatter::FULL,
				\IntlDateFormatter::FULL,
				'Europe/Helsinki',
				\IntlDateFormatter::GREGORIAN,
				"yyyy-MM-dd HH:mm:ss"
			);
			$script .= "
 * This class was autogenerated by Propulsion " . $this->getBuildProperty('version') . " on:
 *
 * " . datefmt_format($now, 0) . "
 *";
		}
		$script .= "
 * @deprecated  Since Propulsion 1.5. Use the nested_set behavior instead of the NestedSet treeMode
 */
abstract class ".$this->getClassname()." extends ".$this->getObjectBuilder()->getClassname()." implements Propulsion\OM\NodeObject
{
";
	}

	/**
	 * Specifies the methods that are added as part of the basic OM class.
	 * This can be overridden by subclasses that wish to add more methods.
	 * @see        AbstractObjectBuilder::addClassBody()
	 */
	protected function addClassBody(&$script): void
	{
		$this->addAttributes($script);
		$this->addGetIterator($script);
		$this->addSave($script);
		$this->addDelete($script);
		$this->addMakeRoot($script);
		$this->addGetLevel($script);
		$this->addGetPath($script);
		$this->addGetNumberOfChildren($script);
		$this->addGetNumberOfDescendants($script);
		$this->addGetChildren($script);
		$this->addGetDescendants($script);
		$this->addSetLevel($script);
		$this->addSetChildren($script);
		$this->addSetParentNode($script);
		$this->addSetPrevSibling($script);
		$this->addSetNextSibling($script);
		$this->addIsRoot($script);
		$this->addIsLeaf($script);
		$this->addIsEqualTo($script);
		$this->addHasParent($script);
		$this->addHasChildren($script);
		$this->addHasPrevSibling($script);
		$this->addHasNextSibling($script);
		$this->addRetrieveParent($script);
		$this->addRetrieveFirstChild($script);
		$this->addRetrieveLastChild($script);
		$this->addRetrievePrevSibling($script);
		$this->addRetrieveNextSibling($script);
		$this->addInsertAsFirstChildOf($script);
		$this->addInsertAsLastChildOf($script);
		$this->addInsertAsPrevSiblingOf($script);
		$this->addInsertAsNextSiblingOf($script);
		$this->addMoveToFirstChildOf($script);
		$this->addMoveToLastChildOf($script);
		$this->addMoveToPrevSiblingOf($script);
		$this->addMoveToNextSiblingOf($script);
		$this->addInsertAsParentOf($script);
		$this->addGetLeft($script);
		$this->addGetRight($script);
		$this->addGetScopeId($script);
		$this->addSetLeft($script);
		$this->addSetRight($script);
		$this->addSetScopeId($script);
	}

	/**
	 * Closes class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassClose(&$script): void
	{
		$script .= "
}
";
	}

	/**
	 * Adds class attributes with modern PHP 8.4 typing.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addAttributes(&$script): void
	{
		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$script .= "
	/**
	 * Store level of node
	 */
	protected ?int \$level = null;

	/**
	 * Store if node has prev sibling
	 */
	protected ?bool \$hasPrevSibling = null;

	/**
	 * Store node if has prev sibling
	 */
	protected ?$objectClassName \$prevSibling = null;

	/**
	 * Store if node has next sibling
	 */
	protected ?bool \$hasNextSibling = null;

	/**
	 * Store node if has next sibling
	 */
	protected ?$objectClassName \$nextSibling = null;

	/**
	 * Store if node has parent node
	 */
	protected ?bool \$hasParentNode = null;

	/**
	 * Store the parent node
	 */
	protected ?$objectClassName \$parentNode = null;

	/**
	 * Store children of the node
	 */
	protected ?array \$children = null;
";
	}

	protected function addGetIterator(&$script): void
	{
		$script .= "
	/**
	 * Returns a pre-order iterator for this node and its children.
	 */
	public function getIterator(): \Traversable
	{
		return new NestedSetRecursiveIterator(\$this);
	}
";
	}

	protected function addSave(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Saves modified object data to the datastore.
	 * If object is saved without left/right values, set them as undefined (0)
	 *
	 * @param      PropulsionPDO \$con Connection to use.
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 *                 May be unreliable with parent/children/brother changes
	 * @throws     PropulsionException
	 */
	public function save(?PropulsionPDO \$con = null): int
	{
		\$left = \$this->getLeftValue();
		\$right = \$this->getRightValue();
		if (empty(\$left) || empty(\$right)) {
			\$root = $peerClassname::retrieveRoot(\$this->getScopeIdValue(), \$con);
			$peerClassname::insertAsLastChildOf(\$this, \$root, \$con);
		}

		return parent::save(\$con);
	}
";
	}

	protected function addDelete(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Removes this object and all descendants from datastore.
	 *
	 * @param      PropulsionPDO \$con Connection to use.
	 * @throws     PropulsionException
	 */
	public function delete(?PropulsionPDO \$con = null): void
	{
		// delete node first
		parent::delete(\$con);

		// delete descendants and then shift tree
		$peerClassname::deleteDescendants(\$this, \$con);
	}
";
	}

	protected function addMakeRoot(&$script): void
	{
		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Sets node properties to make it a root node.
	 *
	 * @return     $objectClassName The current object (for fluent API support)
	 * @throws     PropulsionException
	 */
	public function makeRoot()
	{
		$peerClassname::createRoot(\$this);
		return \$this;
	}
";
	}

	protected function addGetLevel(&$script): void
	{
		// Must accept an optional PropulsionPDO connection and lazily compute the level via the
		// Peer if not already set, to match the Propulsion\OM\NodeObject interface signature
		// (getLevel(?PropulsionPDO $con = null)) -- a naive property-only getter here fatals with
		// "Declaration ... must be compatible" the moment this builder is actually used, which
		// (being the PHP84 builder, promoted to canonical in Phase 3, see KNOWN_ISSUES.md) it
		// hadn't been until this phase's nested-set-behavior tests exercised it end-to-end.
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Get the level of the node in the tree if set, otherwise calculates and returns it.
	 */
	public function getLevel(?PropulsionPDO \$con = null): ?int
	{
		if (\$this->level === null) {
			\$this->level = $peerClassname::getLevel(\$this, \$con);
		}
		return \$this->level;
	}
";
	}

	protected function addGetPath(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Get the path to the node in the tree
	 */
	public function getPath(?PropulsionPDO \$con = null): array
	{
		return $peerClassname::getPath(\$this, \$con);
	}
";
	}

	protected function addGetNumberOfChildren(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Gets the number of children for the node (direct descendants)
	 */
	public function getNumberOfChildren(?PropulsionPDO \$con = null): int
	{
		return $peerClassname::getNumberOfChildren(\$this, \$con);
	}
";
	}

	protected function addGetNumberOfDescendants(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Gets the total number of descendants for the node
	 */
	public function getNumberOfDescendants(?PropulsionPDO \$con = null): int
	{
		return $peerClassname::getNumberOfDescendants(\$this, \$con);
	}
";
	}

	protected function addGetChildren(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Gets the children for the node
	 */
	public function getChildren(?PropulsionPDO \$con = null): array
	{
		\$this->getLevel();

		if (is_array(\$this->children)) {
			return \$this->children;
		}

		return $peerClassname::retrieveChildren(\$this, \$con);
	}
";
	}

	protected function addGetDescendants(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Gets the descendants for the node
	 */
	public function getDescendants(?PropulsionPDO \$con = null): array
	{
		\$this->getLevel();

		return $peerClassname::retrieveDescendants(\$this, \$con);
	}
";
	}

	protected function addSetLevel(&$script): void
	{
		// No return type here: Propulsion\OM\NodeObject::setLevel($level) is untyped, and
		// (for reasons that only surface once this builder is actually used to build a class
		// loaded through a nested autoloader callback, as the test suite's classmap
		// autoloader does) declaring ": static" here trips PHP's interface-compatibility
		// check with a nonsensical "must be compatible with ...: <unrelated class>" fatal.
		// Matching the interface's lack of a return type sidesteps it entirely.
		$script .= "
	/**
	 * Set the level of the node in the tree
	 */
	public function setLevel(\$level)
	{
		\$this->level = \$level;
		return \$this;
	}
";
	}

	protected function addSetChildren(&$script): void
	{
		$script .= "
	/**
	 * Sets the children array of the node in the tree
	 */
	public function setChildren(array \$children)
	{
		\$this->children = \$children;
		return \$this;
	}
";
	}

	protected function addSetParentNode(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Sets the parentNode of the node in the tree
	 */
	public function setParentNode(?NodeObject \$parent = null)
	{
		\$this->parentNode = (true === (\$this->hasParentNode = $peerClassname::isValid(\$parent))) ? \$parent : null;
		return \$this;
	}
";
	}

	protected function addSetPrevSibling(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Sets the previous sibling of the node in the tree
	 */
	public function setPrevSibling(?NodeObject \$node = null)
	{
		\$this->prevSibling = \$node;
		\$this->hasPrevSibling = $peerClassname::isValid(\$node);
		return \$this;
	}
";
	}

	protected function addSetNextSibling(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Sets the next sibling of the node in the tree
	 */
	public function setNextSibling(?NodeObject \$node = null)
	{
		\$this->nextSibling = \$node;
		\$this->hasNextSibling = $peerClassname::isValid(\$node);
		return \$this;
	}
";
	}

	protected function addIsRoot(&$script): void
	{
		$script .= "
	/**
	 * Check if node is root
	 */
	public function isRoot(): bool
	{
		return \$this->getLeft() === 1;
	}
";
	}

	protected function addIsLeaf(&$script): void
	{
		$script .= "
	/**
	 * Check if node is leaf (has no children)
	 */
	public function isLeaf(): bool
	{
		return (\$this->getRight() - \$this->getLeft()) === 1;
	}
";
	}

	protected function addIsEqualTo(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Tests if object is equal to \$node
	 */
	public function isEqualTo(NodeObject \$node): bool
	{
		return $peerClassname::isEqualTo(\$this, \$node);
	}
";
	}

	protected function addHasParent(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Tests if object has an ancestor
	 */
	public function hasParent(?PropulsionPDO \$con = null): bool
	{
		if (\$this->hasParentNode === null) {
			\$this->hasParentNode = $peerClassname::hasParent(\$this, \$con);
		}
		return \$this->hasParentNode;
	}
";
	}

	protected function addHasChildren(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Determines if the node has children / descendants
	 */
	public function hasChildren(): bool
	{
		return $peerClassname::hasChildren(\$this);
	}
";
	}

	protected function addHasPrevSibling(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Determines if the node has previous sibling
	 */
	public function hasPrevSibling(?PropulsionPDO \$con = null): bool
	{
		if (\$this->hasPrevSibling === null) {
			\$this->hasPrevSibling = $peerClassname::hasPrevSibling(\$this, \$con);
		}
		return \$this->hasPrevSibling;
	}
";
	}

	protected function addHasNextSibling(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Determines if the node has next sibling
	 */
	public function hasNextSibling(?PropulsionPDO \$con = null): bool
	{
		if (\$this->hasNextSibling === null) {
			\$this->hasNextSibling = $peerClassname::hasNextSibling(\$this, \$con);
		}
		return \$this->hasNextSibling;
	}
";
	}

	protected function addRetrieveParent(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Gets ancestor for the given node if it exists
	 *
	 * @return     mixed Propulsion object if exists else null
	 */
	public function retrieveParent(?PropulsionPDO \$con = null)
	{
		if (\$this->hasParentNode === null) {
			\$this->parentNode = $peerClassname::retrieveParent(\$this, \$con);
			\$this->hasParentNode = $peerClassname::isValid(\$this->parentNode);
		}
		return \$this->parentNode;
	}
";
	}

	protected function addRetrieveFirstChild(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Gets first child if it exists
	 *
	 * @return     mixed Propulsion object if exists else null
	 */
	public function retrieveFirstChild(?PropulsionPDO \$con = null)
	{
		if (\$this->hasChildren()) {
			if (is_array(\$this->children) && count(\$this->children) > 0) {
				return \$this->children[0];
			}

			return $peerClassname::retrieveFirstChild(\$this, \$con);
		}
		return null;
	}
";
	}

	protected function addRetrieveLastChild(&$script): void
	{
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Gets last child if it exists
	 *
	 * @return     mixed Propulsion object if exists else null
	 */
	public function retrieveLastChild(?PropulsionPDO \$con = null)
	{
		if (\$this->hasChildren()) {
			if (is_array(\$this->children) && count(\$this->children) > 0) {
				\$last = count(\$this->children) - 1;
				return \$this->children[\$last];
			}

			return $peerClassname::retrieveLastChild(\$this, \$con);
		}
		return null;
	}
";
	}

	protected function addRetrievePrevSibling(&$script): void
	{
		$script .= "
	/**
	 * Gets prev sibling for the given node if it exists
	 *
	 * @return     mixed Propulsion object if exists else null
	 */
	public function retrievePrevSibling(?PropulsionPDO \$con = null)
	{
		if (\$this->hasPrevSibling(\$con)) {
			return \$this->prevSibling;
		}
		return null;
	}
";
	}

	protected function addRetrieveNextSibling(&$script): void
	{
		$script .= "
	/**
	 * Gets next sibling for the given node if it exists
	 *
	 * @return     mixed Propulsion object if exists else null
	 */
	public function retrieveNextSibling(?PropulsionPDO \$con = null)
	{
		if (\$this->hasNextSibling(\$con)) {
			return \$this->nextSibling;
		}
		return null;
	}
";
	}

	protected function addInsertAsFirstChildOf(&$script): void
	{
		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Inserts as first child of given destination node \$parent
	 *
	 * @return     $objectClassName The current object (for fluent API support)
	 * @throws     PropulsionException - if this object already exists
	 */
	public function insertAsFirstChildOf(NodeObject \$parent, ?PropulsionPDO \$conn = null)
	{
		if (!\$this->isNew()) {
			throw new PropulsionException(\"$objectClassName must be new.\");
		}
		$peerClassname::insertAsFirstChildOf(\$this, \$parent, \$conn);
		return \$this;
	}
";
	}

	protected function addInsertAsLastChildOf(&$script): void
	{
		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Inserts as last child of given destination node \$parent
	 *
	 * @return     $objectClassName The current object (for fluent API support)
	 * @throws     PropulsionException - if this object already exists
	 */
	public function insertAsLastChildOf(NodeObject \$parent, ?PropulsionPDO \$conn = null)
	{
		if (!\$this->isNew()) {
			throw new PropulsionException(\"$objectClassName must be new.\");
		}
		$peerClassname::insertAsLastChildOf(\$this, \$parent, \$conn);
		return \$this;
	}
";
	}

	protected function addInsertAsPrevSiblingOf(&$script): void
	{
		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Inserts \$this as previous sibling to given destination node \$dest
	 *
	 * @return     $objectClassName The current object (for fluent API support)
	 * @throws     PropulsionException - if this object already exists
	 */
	public function insertAsPrevSiblingOf(NodeObject \$dest, ?PropulsionPDO \$conn = null)
	{
		if (!\$this->isNew()) {
			throw new PropulsionException(\"$objectClassName must be new.\");
		}
		$peerClassname::insertAsPrevSiblingOf(\$this, \$dest, \$conn);
		return \$this;
	}
";
	}

	protected function addInsertAsNextSiblingOf(&$script): void
	{
		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Inserts \$this as next sibling to given destination node \$dest
	 *
	 * @return     $objectClassName The current object (for fluent API support)
	 * @throws     PropulsionException - if this object already exists
	 */
	public function insertAsNextSiblingOf(NodeObject \$dest, ?PropulsionPDO \$conn = null)
	{
		if (!\$this->isNew()) {
			throw new PropulsionException(\"$objectClassName must be new.\");
		}
		$peerClassname::insertAsNextSiblingOf(\$this, \$dest, \$conn);
		return \$this;
	}
";
	}

	protected function addMoveToFirstChildOf(&$script): void
	{
		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Moves node to be first child of \$parent
	 *
	 * @return     $objectClassName The current object (for fluent API support)
	 */
	public function moveToFirstChildOf(NodeObject \$parent, ?PropulsionPDO \$conn = null)
	{
		if (\$this->isNew()) {
			throw new PropulsionException(\"$objectClassName must exist in tree.\");
		}
		$peerClassname::moveToFirstChildOf(\$parent, \$this, \$conn);
		return \$this;
	}
";
	}

	protected function addMoveToLastChildOf(&$script): void
	{
		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Moves node to be last child of \$parent
	 *
	 * @return     $objectClassName The current object (for fluent API support)
	 */
	public function moveToLastChildOf(NodeObject \$parent, ?PropulsionPDO \$conn = null)
	{
		if (\$this->isNew()) {
			throw new PropulsionException(\"$objectClassName must exist in tree.\");
		}
		$peerClassname::moveToLastChildOf(\$parent, \$this, \$conn);
		return \$this;
	}
";
	}

	protected function addMoveToPrevSiblingOf(&$script): void
	{
		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Moves node to be prev sibling to \$dest
	 *
	 * @return     $objectClassName The current object (for fluent API support)
	 */
	public function moveToPrevSiblingOf(NodeObject \$dest, ?PropulsionPDO \$conn = null)
	{
		if (\$this->isNew()) {
			throw new PropulsionException(\"$objectClassName must exist in tree.\");
		}
		$peerClassname::moveToPrevSiblingOf(\$dest, \$this, \$conn);
		return \$this;
	}
";
	}

	protected function addMoveToNextSiblingOf(&$script): void
	{
		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Moves node to be next sibling to \$dest
	 *
	 * @return     $objectClassName The current object (for fluent API support)
	 */
	public function moveToNextSiblingOf(NodeObject \$dest, ?PropulsionPDO \$conn = null)
	{
		if (\$this->isNew()) {
			throw new PropulsionException(\"$objectClassName must exist in tree.\");
		}
		$peerClassname::moveToNextSiblingOf(\$dest, \$this, \$conn);
		return \$this;
	}
";
	}

	protected function addInsertAsParentOf(&$script): void
	{
		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$peerClassname = $this->getStubPeerBuilder()->getClassname();
		$script .= "
	/**
	 * Inserts node as parent of given node.
	 *
	 * @return     $objectClassName The current object (for fluent API support)
	 */
	public function insertAsParentOf(NodeObject \$node, ?PropulsionPDO \$conn = null)
	{
		$peerClassname::insertAsParentOf(\$this, \$node, \$conn);
		return \$this;
	}
";
	}

	protected function addGetLeft(&$script): void
	{
		$table = $this->getTable();

		$left_col_getter_name = null;
		foreach ($table->getColumns() as $col) {
			if ($col->isNestedSetLeftKey()) {
				$left_col_getter_name = 'get'.$col->getPhpName();
				break;
			}
		}

		$script .= "
	/**
	 * Wraps the getter for the left value
	 *
	 * @return     int|null null until the node has been positioned in the tree
	 */
	public function getLeftValue(): ?int
	{
		return \$this->$left_col_getter_name();
	}

	/**
	 * Alias of getLeftValue(), matching the internal isRoot()/isLeaf() naming.
	 */
	public function getLeft(): ?int
	{
		return \$this->getLeftValue();
	}
";
	}

	protected function addGetRight(&$script): void
	{
		$table = $this->getTable();

		$right_col_getter_name = null;
		foreach ($table->getColumns() as $col) {
			if ($col->isNestedSetRightKey()) {
				$right_col_getter_name = 'get'.$col->getPhpName();
				break;
			}
		}

		$script .= "
	/**
	 * Wraps the getter for the right value
	 *
	 * @return     int|null null until the node has been positioned in the tree
	 */
	public function getRightValue(): ?int
	{
		return \$this->$right_col_getter_name();
	}

	/**
	 * Alias of getRightValue(), matching the internal isRoot()/isLeaf() naming.
	 */
	public function getRight(): ?int
	{
		return \$this->getRightValue();
	}
";
	}

	protected function addGetScopeId(&$script): void
	{
		$table = $this->getTable();

		$scope_col_getter_name = null;
		foreach ($table->getColumns() as $col) {
			if ($col->isTreeScopeKey()) {
				$scope_col_getter_name = 'get'.$col->getPhpName();
				break;
			}
		}

		$script .= "
	/**
	 * Wraps the getter for the scope value
	 *
	 * @return     int|null null if scope is disabled
	 */
	public function getScopeIdValue()
	{";
		if ($scope_col_getter_name) {
			$script .= "
		return \$this->$scope_col_getter_name();";
		} else {
			$script .= "
		return null;";
		}
		$script .= "
	}
";
	}

	protected function addSetLeft(&$script): void
	{
		$table = $this->getTable();

		$left_col_setter_name = null;
		foreach ($table->getColumns() as $col) {
			if ($col->isNestedSetLeftKey()) {
				$left_col_setter_name = 'set'.$col->getPhpName();
				break;
			}
		}

		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$script .= "
	/**
	 * Set the value of the left column
	 *
	 * @return     $objectClassName The current object (for fluent API support)
	 */
	public function setLeftValue(int \$v)
	{
		\$this->$left_col_setter_name(\$v);
		return \$this;
	}
";
	}

	protected function addSetRight(&$script): void
	{
		$table = $this->getTable();

		$right_col_setter_name = null;
		foreach ($table->getColumns() as $col) {
			if ($col->isNestedSetRightKey()) {
				$right_col_setter_name = 'set'.$col->getPhpName();
				break;
			}
		}

		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$script .= "
	/**
	 * Set the value of the right column
	 *
	 * @return     $objectClassName The current object (for fluent API support)
	 */
	public function setRightValue(int \$v)
	{
		\$this->$right_col_setter_name(\$v);
		return \$this;
	}
";
	}

	protected function addSetScopeId(&$script): void
	{
		$table = $this->getTable();

		$scope_col_setter_name = null;
		foreach ($table->getColumns() as $col) {
			if ($col->isTreeScopeKey()) {
				$scope_col_setter_name = 'set'.$col->getPhpName();
				break;
			}
		}

		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$script .= "
	/**
	 * Set the value of the scope column
	 *
	 * @return     $objectClassName The current object (for fluent API support)
	 */
	public function setScopeIdValue(\$v)
	{";
		if ($scope_col_setter_name) {
			$script .= "
		\$this->$scope_col_setter_name(\$v);";
		}
		$script .= "
		return \$this;
	}
";
	}
}
