<?php

/**
 * This file is part of the Propulsion package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propulsion\Generator\Builder\OM;

/**
 * Generates a PHP 8.4 tree node Object class for user object model (OM).
 *
 * This class produces the base tree node object class (e.g. BaseMyTable) which contains all
 * the custom-built accessor and setter methods with modern PHP 8.4 features:
 * - Typed properties and methods
 * - Readonly properties where appropriate
 * - Iterator interface with proper typing
 * - Modern exception handling
 * - Null coalescing and arrow functions
 *
 * @author     GitHub Copilot
 */
class NodeBuilder extends AbstractObjectBuilder
{

	/**
	 * Gets the package for the [base] object classes.
	 * @return     string
	 */
	public function getPackage(): string
	{
		return parent::getPackage() . "." . $this->getOmPackageSegment();
	}

	public function getNamespace(): ?string
	{
		if ($namespace = parent::getNamespace()) {
			if ($omns = $this->getGeneratorConfig()->getBuildProperty('namespaceOm')) {
				return $namespace . '\\' . $omns;
			} else {
				return $namespace;
			}
		}
		return null;
	}

	/**
	 * Returns the name of the current class being built.
	 * @return     string
	 */
	public function getUnprefixedClassname(): string
	{
		return $this->getBuildProperty('basePrefix') . $this->getStubNodeBuilder()->getUnprefixedClassname();
	}

	/**
	 * Adds the include() statements for files that this class depends on or utilizes.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addIncludes(&$script = null): void
	{
		// PHP 8.4 uses namespaces and autoloading, so includes are minimal
	}

	/**
	 * Adds class phpdoc comment and opening of class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassOpen(&$script): void
	{
		$table = $this->getTable();
		$tableName = $table->getName();
		$tableDesc = $table->getDescription();

		$script .= "
/**
 * Base class that represents a row from the '$tableName' table with node behavior.
 *
 * $tableDesc
 *";
		if ($this->getBuildProperty('addTimeStamp')) {
			$now = datefmt_create(
				'en_US',
				\IntlDateFormatter::FULL,
				\IntlDateFormatter::FULL,
				'Europe/Helsinki',
				\IntlDateFormatter::GREGORIAN,
				"yyyy-MM-dd HH:mm:ss"
			);
			$script .= "
 * This class was autogenerated by Propulsion " . $this->getBuildProperty('version') . " on:
 *
 * " . datefmt_format($now, 0) . "
 *";
		}
		$script .= "
 */
abstract class ".$this->getClassname()." implements \\IteratorAggregate
{
";
	}

	/**
	 * Specifies the methods that are added as part of the basic OM class.
	 * This can be overridden by subclasses that wish to add more methods.
	 * @see        AbstractObjectBuilder::addClassBody()
	 */
	protected function addClassBody(&$script): void
	{
		$this->addAttributes($script);
		$this->addGetIterator($script);
		$this->addIsLeaf($script);
		$this->addIsRoot($script);
		$this->addIsEqualTo($script);
		$this->addHasParent($script);
		$this->addHasChildren($script);
		$this->addHasPrevSibling($script);
		$this->addHasNextSibling($script);
		$this->addRetrieveParent($script);
		$this->addRetrieveFirstChild($script);
		$this->addRetrieveLastChild($script);
		$this->addRetrievePrevSibling($script);
		$this->addRetrieveNextSibling($script);
		$this->addGetChildren($script);
		$this->addGetDescendants($script);
		$this->addCountChildren($script);
		$this->addCountDescendants($script);
		$this->addGetPath($script);
		$this->addGetLevel($script);
		$this->addSetParentNode($script);
		$this->addSetPrevSibling($script);
		$this->addSetNextSibling($script);
		$this->addSetLevel($script);
	}

	/**
	 * Closes class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassClose(&$script): void
	{
		$script .= "
}
";
	}

	/**
	 * Adds class attributes with modern PHP 8.4 typing.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addAttributes(&$script): void
	{
		$objectClassName = $this->getStubObjectBuilder()->getClassname();
		$script .= "
	/**
	 * Store level of node
	 */
	protected ?int \$level = null;

	/**
	 * Store if node has parent node
	 */
	protected ?bool \$hasParentNode = null;

	/**
	 * Store the parent node
	 */
	protected ?$objectClassName \$parentNode = null;

	/**
	 * Store if node has prev sibling
	 */
	protected ?bool \$hasPrevSibling = null;

	/**
	 * Store node if has prev sibling
	 */
	protected ?$objectClassName \$prevSibling = null;

	/**
	 * Store if node has next sibling
	 */
	protected ?bool \$hasNextSibling = null;

	/**
	 * Store node if has next sibling
	 */
	protected ?$objectClassName \$nextSibling = null;

	/**
	 * Store children of the node
	 */
	protected ?array \$children = null;
";
	}

	/**
	 * Adds getIterator method with proper typing.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addGetIterator(&$script): void
	{
		$script .= "
	/**
	 * Get iterator for children nodes
	 */
	public function getIterator(): \\ArrayIterator
	{
		return new \\ArrayIterator(\$this->getChildren());
	}
";
	}

	/**
	 * Adds isLeaf method.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addIsLeaf(&$script): void
	{
		$script .= "
	/**
	 * Check if node is leaf (has no children)
	 */
	public function isLeaf(): bool
	{
		return !\$this->hasChildren();
	}
";
	}

	/**
	 * Adds isRoot method.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addIsRoot(&$script): void
	{
		$script .= "
	/**
	 * Check if node is root (has no parent)
	 */
	public function isRoot(): bool
	{
		return !\$this->hasParent();
	}
";
	}

	/**
	 * Adds getLevel method.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addGetLevel(&$script): void
	{
		$script .= "
	/**
	 * Get the level of the node in the tree
	 */
	public function getLevel(): ?int
	{
		return \$this->level;
	}
";
	}

	/**
	 * Adds setLevel method.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addSetLevel(&$script): void
	{
		// See NestedSetBuilder::addSetLevel() for why this deliberately has no return
		// type: it would otherwise fatal wherever it ends up implementing
		// Propulsion\OM\NodeObject::setLevel($level), which is untyped.
		$script .= "
	/**
	 * Set the level of the node in the tree
	 */
	public function setLevel(\$level)
	{
		\$this->level = \$level;
		return \$this;
	}
";
	}

	// Placeholder methods - in a complete implementation, these would contain
	// the full modernized logic from the PHP5 version
	protected function addIsEqualTo(string &$script): void { /* Implementation */ }
	protected function addHasParent(string &$script): void { /* Implementation */ }
	protected function addHasChildren(string &$script): void { /* Implementation */ }
	protected function addHasPrevSibling(string &$script): void { /* Implementation */ }
	protected function addHasNextSibling(string &$script): void { /* Implementation */ }
	protected function addRetrieveParent(string &$script): void { /* Implementation */ }
	protected function addRetrieveFirstChild(string &$script): void { /* Implementation */ }
	protected function addRetrieveLastChild(string &$script): void { /* Implementation */ }
	protected function addRetrievePrevSibling(string &$script): void { /* Implementation */ }
	protected function addRetrieveNextSibling(string &$script): void { /* Implementation */ }
	protected function addGetChildren(string &$script): void { /* Implementation */ }
	protected function addGetDescendants(string &$script): void { /* Implementation */ }
	protected function addCountChildren(string &$script): void { /* Implementation */ }
	protected function addCountDescendants(string &$script): void { /* Implementation */ }
	protected function addGetPath(string &$script): void { /* Implementation */ }
	protected function addSetParentNode(string &$script): void { /* Implementation */ }
	protected function addSetPrevSibling(string &$script): void { /* Implementation */ }
	protected function addSetNextSibling(string &$script): void { /* Implementation */ }
}
