<?php

/**
 * This file is part of the Propel package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propulsion\Generator\Builder\OM;

/**
 * Generates the empty PHP5 stub node object class for user object model (OM).
 *
 * This class produces the empty stub class that can be customized with application
 * business logic, custom behavior, etc.
 *
 * @author     Hans Lellelid <hans@xmpl.org>
 * @package    propel.generator.builder.om
 * @method void addConstantsAndAttributes(string &$script)
 * @method void addTranslateFieldName(string &$script)
 * @method void addGetFieldNames(string &$script)
 * @method void addGetValueSets(string &$script)
 * @method void addGetValueSet(string &$script)
 * @method void addAlias(string &$script)
 * @method void addGetTableMap(string &$script)
 * @method void addBuildTableMap(string &$script)
 * @method void addAddSelectColumns(string &$script)
 * @method void addDoCount(string &$script)
 * @method void addDoSelectOne(string &$script)
 * @method void addDoSelect(string &$script)
 * @method void addDoSelectStmt(string &$script)
 * @method void addAddInstanceToPool(string &$script)
 * @method void addRemoveInstanceFromPool(string &$script)
 * @method void addGetInstanceFromPool(string &$script)
 * @method void addClearInstancePool(string &$script)
 * @method void addClearRelatedInstancePool(string &$script)
 * @method void addGetPrimaryKeyHash(string &$script)
 * @method void addGetPrimaryKeyFromRow(string &$script)
 * @method void addPopulateObjects(string &$script)
 * @method void addPopulateObject(string &$script)
 * @method void addDoInsert(string &$script)
 * @method void addDoUpdate(string &$script)
 * @method void addDoDeleteAll(string &$script)
 * @method void addDoDelete(string &$script)
 * @method void addDoOnDeleteCascade(string &$script)
 * @method void addDoOnDeleteSetNull(string &$script)
 * @method void addDoValidate(string &$script)
 * @method void addRetrieveByPK_SinglePK(string &$script)
 * @method void addRetrieveByPKs_SinglePK(string &$script)
 * @method void addRetrieveByPK_MultiPK(string &$script)
 * @method void addGetOMClass_Inheritance(string &$script)
 * @method void addGetOMClass_NoInheritance_Abstract(string &$script)
 * @method void addGetOMClass_NoInheritance(string &$script)
 * @method void addTemporalAccessor(string &$script, $col)
 * @method void addObjectAccessor(string &$script, $col)
 * @method void addArrayAccessor(string &$script, $col)
 * @method void addEnumAccessor(string &$script, $col)
 * @method void addDefaultAccessor(string &$script, $col)
 * @method void addLazyLoader(string &$script, $col)
 * @method void addLobMutator(string &$script, $col)
 * @method void addHasArrayElement(string &$script, $col)
 * @method void addTemporalMutator(string &$script, $col)
 * @method void addObjectMutator(string &$script, $col)
 * @method void addArrayMutator(string &$script, $col)
 * @method void addEnumMutator(string &$script, $col)
 * @method void addBooleanMutator(string &$script, $col)
 * @method void addAddArrayElement(string &$script, $col)
 * @method void addRemoveArrayElement(string &$script, $col)
 */
class PHP5ExtensionNodeBuilder extends AbstractObjectBuilder
{

	/**
	 * Returns the name of the current class being built.
	 * @return     string
	 */
	public function getUnprefixedClassname()
	{
		return $this->getTable()->getPhpName() . 'Node';
	}

	/**
	 * Adds the include() statements for files that this class depends on or utilizes.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addIncludes(&$script = null)
	{
		$script .= "
require '".$this->getNodeBuilder()->getClassFilePath()."';
";
	} // addIncludes()

	/**
	 * Adds class phpdoc comment and openning of class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassOpen(&$script)
	{

		$table = $this->getTable();
		$tableName = $table->getName();
		$tableDesc = $table->getDescription();

		$baseClassname = $this->getNodeBuilder()->getClassname();

		$script .= "

/**
 * Skeleton subclass for representing a node from the '$tableName' table.
 *
 * $tableDesc
 *";
		if ($this->getBuildProperty('addTimeStamp')) {
			$now = datefmt_create(
				'en_US',
				\IntlDateFormatter::FULL,
				\IntlDateFormatter::FULL,
				'Europe/Helsinki',
				\IntlDateFormatter::GREGORIAN,
				"yyyy-MM-dd HH:mm:ss"
			);
			$script .= "
 * This class was autogenerated by Propel " . $this->getBuildProperty('version') . " on:
 *
 * " . datefmt_format($now, 0) . "
 *";
		}
		$script .= "
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.".$this->getPackage()."
 */
class ".$this->getClassname()." extends $baseClassname {
";
	}

	/**
	 * Specifies the methods that are added as part of the stub object class.
	 *
	 * By default there are no methods for the empty stub classes; override this method
	 * if you want to change that behavior.
	 *
	 * @see        AbstractObjectBuilder::addClassBody()
	 */
	protected function addClassBody(&$script)
	{
		// there is no class body
	}

	/**
	 * Closes class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassClose(&$script)
	{
		$script .= "
} // " . $this->getClassname() . "
";
	}

} // PHP5ExtensionObjectBuilder
