<?php

/**
 * This file is part of the Propel package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propel\Generator\Builder\OM;

/**
 * Generates a PHP 8.4 base Query class for user object model (OM).
 *
 * This class produces the base query class (e.g. BaseBookQuery) which contains all
 * the custom-built query methods using modern PHP 8.4 features.
 *
 * @author     Modernized for PHP 8.4
 * @package    propel.generator.builder.om
 */
use Propel\Generator\Model\PropelTypes;
use Propel\Generator\Model\ForeignKey;

class PHP84QueryBuilder extends QueryBuilder
{
	public function getPackage()
	{
		$pkg = ($this->getTable()->getPackage() ? $this->getTable()->getPackage() : $this->getDatabase()->getPackage());
		if (!$pkg) {
			$pkg = $this->getBuildProperty('targetPackage');
		}
		return $pkg . ".OM";
         
	}

    /**
     * Adds class phpdoc comment and opening of class with modern PHP 8.4 features.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addClassOpen(&$script): void
    {
        $table = $this->getTable();
        $tableName = $table->getName();
        $tableDesc = $table->getDescription();
        $queryClass = $this->getStubQueryBuilder()->getClassname();
        $modelClass = $this->getStubObjectBuilder()->getClassname();
        $parentClass = $this->getBehaviorContent('parentClass');
        $parentClass = $parentClass ?? 'ModelCriteria';
        
        $script .= "
/**
 * Base class that represents a query for the '$tableName' table.
 *
 * $tableDesc
 *";
        if ($this->getBuildProperty('addTimeStamp')) {
            $now = datefmt_create(
                'en_US',
                \IntlDateFormatter::FULL,
                \IntlDateFormatter::FULL,
                'Europe/Helsinki',
                \IntlDateFormatter::GREGORIAN,
                "yyyy-MM-dd HH:mm:ss"
            );
            $script .= "
 * This class was autogenerated by Propel " . $this->getBuildProperty('version') . " on:
 *
 * " . datefmt_format($now, time()) . "
 *";
        }

        // Modern typed magic orderBy() methods for IDE completion
        foreach ($this->getTable()->getColumns() as $column) {
            $script .= "
 * @method     $queryClass orderBy" . $column->getPhpName() . "(string \$order = Criteria::ASC) Order by the " . $column->getName() . " column";
        }
        $script .= "
 *";

        // Modern typed magic groupBy() methods for IDE completion
        foreach ($this->getTable()->getColumns() as $column) {
            $script .= "
 * @method     $queryClass groupBy" . $column->getPhpName() . "() Group by the " . $column->getName() . " column";
        }
        $script .= "
 *";

        // Modern typed magic filterBy() methods for IDE completion
        // Note: filterBy methods accept the column type OR array (for IN queries, ranges, etc.)
        foreach ($this->getTable()->getColumns() as $column) {
            $phpType = $this->getModernPhpType($column);
            // Convert ?T to T|null for union types (PHPDoc doesn't support ?T in unions)
            $baseType = ltrim($phpType, '?');
            $filterType = $baseType . '|array' . (str_starts_with($phpType, '?') ? '|null' : '');
            $script .= "
 * @method     $queryClass filterBy" . $column->getPhpName() . "($filterType \$" . $column->getName() . ", ?string \$comparison = null) Filter by the " . $column->getName() . " column";
        }

        // Override signatures with modern type hints
        $script .= "
 *
 * @method     $queryClass leftJoin(string \$relation) Adds a LEFT JOIN clause to the query
 * @method     $queryClass rightJoin(string \$relation) Adds a RIGHT JOIN clause to the query
 * @method     $queryClass innerJoin(string \$relation) Adds a INNER JOIN clause to the query
 * @method     $queryClass joinWith(string \$relation, ?string \$joinType = null) Adds a join with the columns of the related table
 * @method     $queryClass addJoinObject(\\Propel\\Query\\ModelJoin \$join, ?string \$name = null) Adds a join object to the query
 * @method     $queryClass useQuery(string \$relationName, ?string \$secondTableAlias = null) Use the relation as sub query
 * @method     $queryClass mergeWith(\\Propel\\Query\\Criteria \$criteria) Merge the conditions of another Criteria into this one
 * @method     $queryClass addUsingAlias(string \$column, mixed \$value, ?string \$comparison = null) Add a condition using a column alias
 *";

        // Modern typed XXXjoinYYY() methods for IDE completion
        foreach ($this->getTable()->getForeignKeys() as $fk) {
            $relationName = $this->getFKPhpNameAffix($fk);
            $script .= "
 * @method     $queryClass leftJoin" . $relationName . "(?string \$relationAlias = null) Adds a LEFT JOIN clause using the " . $relationName . " relation
 * @method     $queryClass rightJoin" . $relationName . "(?string \$relationAlias = null) Adds a RIGHT JOIN clause using the " . $relationName . " relation
 * @method     $queryClass innerJoin" . $relationName . "(?string \$relationAlias = null) Adds a INNER JOIN clause using the " . $relationName . " relation
 * @method     $queryClass joinWith" . $relationName . "(?string \$joinType = null) Adds a join with the " . $relationName . " relation columns
 *";
        }
        
        foreach ($this->getTable()->getReferrers() as $refFK) {
            $relationName = $this->getRefFKPhpNameAffix($refFK);
            $script .= "
 * @method     $queryClass leftJoin" . $relationName . "(?string \$relationAlias = null) Adds a LEFT JOIN clause using the " . $relationName . " relation
 * @method     $queryClass rightJoin" . $relationName . "(?string \$relationAlias = null) Adds a RIGHT JOIN clause using the " . $relationName . " relation
 * @method     $queryClass innerJoin" . $relationName . "(?string \$relationAlias = null) Adds a INNER JOIN clause using the " . $relationName . " relation
 *";
        }

        // Modern typed findOne() methods
        $script .= "
 * @method     ?$modelClass findOne(?PropelPDO \$con = null) Return the first $modelClass matching the query
 * @method     $modelClass findOneOrCreate(?PropelPDO \$con = null) Return the first $modelClass matching the query, or a new $modelClass object
 * @method     PropelObjectCollection<$modelClass> find(?PropelPDO \$con = null) Return $modelClass objects based on current query
 * @method     ?$modelClass findPk(mixed \$key, ?PropelPDO \$con = null) Return the $modelClass matching the primary key
 * @method     PropelObjectCollection<$modelClass> findPks(mixed \$keys, ?PropelPDO \$con = null) Return $modelClass objects matching the primary keys
 * @method     int count(?PropelPDO \$con = null) Count the number of matching records
 * @method     \\Propel\\Util\\PropelModelPager paginate(int \$page = 1, int \$maxPerPage = 10, ?PropelPDO \$con = null) Paginate the results
 * @method     int delete(?PropelPDO \$con = null) Delete matching records
 * @method     int update(array \$values, ?PropelPDO \$con = null, bool \$forceIndividualSaves = false) Update matching records
 *";

        // Modern typed findBy() methods with proper type hints
        foreach ($this->getTable()->getColumns() as $column) {
            $phpType = $this->getModernPhpType($column);
            $script .= "
 * @method     ?$modelClass findOneBy" . $column->getPhpName() . "($phpType \$" . $column->getName() . ") Return the first $modelClass filtered by the " . $column->getName() . " column";
        }
        $script .= "
 *";
        
        foreach ($this->getTable()->getColumns() as $column) {
            $phpType = $this->getModernPhpType($column);
            $script .= "
 * @method     array<$modelClass> findBy" . $column->getPhpName() . "($phpType \$" . $column->getName() . ") Return $modelClass objects filtered by the " . $column->getName() . " column";
        }

        // Add useQuery methods for foreign key relationships
        foreach ($this->getTable()->getForeignKeys() as $fk) {
            $relationName = $this->getFKPhpNameAffix($fk);
            $relatedQueryClass = $this->getNewStubQueryBuilder($fk->getForeignTable())->getFullyQualifiedClassname();
            $script .= "
 * @method     \\$relatedQueryClass use" . $relationName . "Query(?string \$relationAlias = null) Use the " . $relationName . " relation query object";
        }
        
        foreach ($this->getTable()->getReferrers() as $refFK) {
            $relationName = $this->getRefFKPhpNameAffix($refFK);
            $relatedQueryClass = $this->getNewStubQueryBuilder($refFK->getTable())->getFullyQualifiedClassname();
            $script .= "
 * @method     \\$relatedQueryClass use" . $relationName . "Query(?string \$relationAlias = null) Use the " . $relationName . " relation query object";
        }

        // Add findOneBy and findBy magic methods for foreign key relationships (accept relation objects)
        // Note: filterBy methods are generated as real methods, not magic methods
        $script .= "
 *";
        foreach ($this->getTable()->getForeignKeys() as $fk) {
            $relationName = $this->getFKPhpNameAffix($fk);
            $relatedModelClass = $this->getNewStubObjectBuilder($fk->getForeignTable())->getFullyQualifiedClassname();
            $script .= "
 * @method     ?$modelClass findOneBy" . $relationName . "(\\$relatedModelClass \$" . lcfirst($relationName) . ") Return the first $modelClass filtered by the " . $relationName . " relation
 * @method     array<$modelClass> findBy" . $relationName . "(\\$relatedModelClass \$" . lcfirst($relationName) . ") Return $modelClass objects filtered by the " . $relationName . " relation";
        }
        
        foreach ($this->getTable()->getReferrers() as $refFK) {
            $relationName = $this->getRefFKPhpNameAffix($refFK);
            $relatedModelClass = $this->getNewStubObjectBuilder($refFK->getTable())->getFullyQualifiedClassname();
            $script .= "
 * @method     ?$modelClass findOneBy" . $relationName . "(\\$relatedModelClass \$" . lcfirst($relationName) . ") Return the first $modelClass filtered by the " . $relationName . " relation
 * @method     array<$modelClass> findBy" . $relationName . "(\\$relatedModelClass \$" . lcfirst($relationName) . ") Return $modelClass objects filtered by the " . $relationName . " relation";
        }

        // Add @method annotations for inherited Criteria methods to fix fluent interface
        $script .= "
 *
 * @method     $queryClass add(string \$column, mixed \$value = null, ?string \$comparison = null) Add a condition to the query
 * @method     $queryClass addCond(string \$name, string \$column, mixed \$value = null, ?string \$comparison = null) Add a named condition
 * @method     $queryClass addOr(string \$column, mixed \$value = null, ?string \$comparison = null) Add an OR condition
 * @method     $queryClass addAnd(string \$column, mixed \$value = null, ?string \$comparison = null) Add an AND condition
 * @method     $queryClass where(string|array \$clause, mixed \$value = null) Add a WHERE clause to the query
 * @method     $queryClass condition(string \$conditionName, string \$clause, mixed \$value = null) Add a named condition
 * @method     $queryClass mergeWith(\\Propel\\Query\\Criteria \$criteria) Merge conditions from another Criteria object
 * @method     $queryClass addJoin(string \$left, string \$right, ?string \$joinType = null) Add a join condition
 * @method     $queryClass addGroupByColumn(string \$column) Add a GROUP BY column
 * @method     $queryClass addSelectColumn(string \$column) Add a column to the SELECT clause
 * @method     $queryClass addSelfSelectColumns() Add the columns of the current table to the SELECT clause
 * @method     $queryClass addHaving(\\Propel\\Query\\Criterion \$having) Add a HAVING condition
 * @method     $queryClass addAscendingOrderByColumn(string \$column) Add ascending order by column
 * @method     $queryClass addDescendingOrderByColumn(string \$column) Add descending order by column
 * @method     $queryClass setIgnoreCase(bool \$ignoreCase) Set ignore case flag for string comparisons
 * @method     $queryClass setDistinct() Add DISTINCT modifier to the query
 * @method     $queryClass setLimit(int \$limit) Set the maximum number of records to return
 * @method     $queryClass setOffset(int \$offset) Set the number of records to skip
 * @method     $queryClass setComment(?string \$comment) Set a comment for the query
 * @method     $queryClass limit(int \$limit) Alias for setLimit()
 * @method     $queryClass offset(int \$offset) Alias for setOffset()
 * @method     $queryClass distinct() Alias for setDistinct()
 *
 * @package    propel.generator.".$this->getPackage()."
 */
abstract class ".$this->getClassname()." extends " . $parentClass . "
{
    ";
    }

    /**
     * Get modern PHP 8.4 type for a column
     */
    protected function getModernPhpType($column): string
    {
        if ($column->isTemporalType()) {
            $this->declareClass('\\DateTimeInterface');
            return $column->isNotNull() ? 'DateTimeInterface' : '?DateTimeInterface';
        }
        
        // Check the actual Propel type for better type hints
        // For BIGINT, use int since we're on 64-bit PHP 8.4 (handles up to 2^63-1)
        $propelType = $column->getType();
        
        if ($propelType === PropelTypes::BIGINT || $propelType === PropelTypes::INTEGER || 
            $propelType === PropelTypes::SMALLINT || $propelType === PropelTypes::TINYINT) {
            return $column->isNotNull() ? 'int' : '?int';
        }
        
        // Fall back to the PHP type mapping
        $phpType = $column->getPhpType();
        
        if ($phpType === 'DateTime') {
            $this->declareClass('\\DateTimeInterface');
            return $column->isNotNull() ? 'DateTimeInterface' : '?DateTimeInterface';
        }
		
        // Convert to modern nullable types where appropriate
        if ($column->isNotNull()) {
            return match($phpType) {
                'int' => 'int',
                'string' => 'string',
                'boolean' => 'bool',
                'double' => 'float',
                'resource' => 'resource',
                default => $phpType
            };
        }
		
        return match($phpType) {
            'int' => '?int',
            'string' => '?string',
            'boolean' => '?bool',
            'double' => '?float',
            'resource' => '?resource',
            default => '?' . $phpType
        };
    }

    /**
     * Adds the constructor with modern PHP 8.4 features.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addConstructor(&$script): void
    {
        $script .= "
    /**
     * Initializes internal state of " . $this->getClassname() . " object.
     * @param      ?string \$dbName The database name
     * @param      ?string \$modelName The phpName of a model, e.g. 'Book'
     * @param      ?string \$modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct(?string \$dbName = '" . $this->getTable()->getDatabase()->getName() . "', ?string \$modelName = '" . addslashes($this->getStubObjectBuilder()->getFullyQualifiedClassname()) . "', ?string \$modelAlias = null)
    {
        parent::__construct(\$dbName, \$modelName, \$modelAlias);
    }
";
    }

    /**
     * Adds factory method with modern typing.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFactory(&$script): void
    {
        $script .= "
    /**
     * Returns a new " . $this->getStubQueryBuilder()->getClassname() . " object.
     *
     * @param      ?string \$modelAlias The alias of a model in the query
     * @param      ?Criteria \$criteria Optional Criteria to build the query from
     *
     * @return     " . $this->getStubQueryBuilder()->getClassname() . "
     */
    public static function create(?string \$modelAlias = null, ?Criteria \$criteria = null): " . $this->getStubQueryBuilder()->getClassname() . "
    {
        if (\$criteria instanceof " . $this->getStubQueryBuilder()->getClassname() . ") {
            return \$criteria;
        }
        \$query = new " . $this->getStubQueryBuilder()->getClassname() . "();
        if (null !== \$modelAlias) {
            /** @var ModelCriteria \$query */
            \$query->setModelAlias(\$modelAlias);
        }
        if (\$criteria instanceof Criteria) {
            /** @var Criteria \$query */
            \$query->mergeWith(\$criteria);
        }
        return \$query;
    }
";
    }

    /**
     * Adds findPk method with modern typing.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFindPk(&$script): void
    {
        $pks = $this->getTable()->getPrimaryKey();
        if (count($pks) == 1) {
            $pk = $pks[0];
            $script .= "
    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * @param      mixed \$key Primary key to use for the query
     * @param      ?PropelPDO \$con An optional connection object
     *
     * @return     " . $this->getObjectBuilder()->getClassname() . "|" . $this->getObjectBuilder()->getClassname() . "[]|null|mixed The result, formatted by the current formatter
     */
    public function findPk(mixed \$key, ?PropelPDO \$con = null): mixed
    {
        if (\$key === null) {
            return null;
        }
        if ((null !== (\$obj = " . $this->getPeerBuilder()->getClassname() . "::getInstanceFromPool((string) \$key))) && !\$this->formatter) {
            // the object is alredy in the instance pool
            return \$obj;
        }
        if (\$con === null) {
            \$con = Propel::getConnection(" . $this->getPeerBuilder()->getClassname() . "::DATABASE_NAME, Propel::CONNECTION_READ);
        }";
        
        // Set up pool key hash parameters
        if (count($pks) === 1) {
            $poolKeyHashParams = '$key';
        } else {
            $poolKeyHashParams = array();
            for ($i = 0, $count = count($pks); $i < $count; $i++) {
                $poolKeyHashParams[]= '$key[' . $i . ']';
            }
        }
        
        $script .= "
        if ((null !== (\$obj = " . $this->getPeerBuilder()->getClassname() . "::getInstanceFromPool(".$this->getPeerBuilder()->getInstancePoolKeySnippet($poolKeyHashParams)."))) && \$this->getFormatter()->isObjectFormatter()) {
            // the object is already in the instance pool
            return \$obj;
        } else {
            // the object has not been requested yet, or the formatter is not an object formatter
            \$criteria = \$this->isKeepQuery() ? clone \$this : \$this;
            \$stmt = \$criteria
                ->filterByPrimaryKey(\$key)
                ->getSelectStatement(\$con);
            return \$criteria->getFormatter()->init(\$criteria)->formatOne(\$stmt);
        }
    }
";
        } else {
            // Composite primary key
            $pkParams = [];
            foreach ($pks as $pk) {
                $pkParams[] = 'mixed $' . $pk->getName();
            }
            $pkParamsStr = implode(', ', $pkParams);
            
            $script .= "
    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param      $pkParamsStr Primary keys to use for the query
     * @param      ?PropelPDO \$con A connection object
     *
     * @return     ?" . $this->getObjectBuilder()->getClassname() . " A model object, or null if the key is not found
     */
    protected function findPkSimple($pkParamsStr, ?PropelPDO \$con): ?" . $this->getObjectBuilder()->getClassname() . "
    {
        // Implementation would be generated here
        throw new PropelException('Composite primary key not yet implemented for PHP84QueryBuilder');
    }
";
        }
        
        // Add findPkSimple method for single primary key tables
        if (count($pks) == 1) {
            $this->addFindPkSimple($script);
        }
    }

    /**
     * Adds findPkSimple method for single primary key tables with modern typing.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFindPkSimple(&$script): void
    {
        $script .= "
    /**
     * Find object by primary key using a simple approach for fast queries.
     * Bypass unnecessary complexity when the query conditions are simple.
     *
     * @param      mixed \$key Primary key to use for the query
     * @param      ?PropelPDO \$con A connection object
     *
     * @return     ?" . $this->getObjectBuilder()->getClassname() . " A model object, or null if the key is not found
     */
    protected function findPkSimple(mixed \$key, ?PropelPDO \$con): ?" . $this->getObjectBuilder()->getClassname() . "
    {
        \$criteria = \$this->isKeepQuery() ? clone \$this : \$this;
        \$stmt = \$criteria
            ->filterByPrimaryKey(\$key)
            ->getSelectStatement(\$con);
        return \$criteria->getFormatter()->init(\$criteria)->formatOne(\$stmt);
    }
";
    }

    /**
     * Adds the main class body with essential imports for Query classes.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addClassBody(&$script): void
    {
        // Declare essential classes for Base*Query classes with proper namespaces
        $this->declareClass('Propel\Query\ModelCriteria');
        $this->declareClass('Propel\Connection\PropelPDO');
        $this->declareClass('Propel\Query\Criteria');
        $this->declareClass('Propel\Exception\PropelException');
        $this->declareClass('Propel\Collection\PropelCollection');
        $this->declareClass('Propel\Collection\PropelObjectCollection');
        $this->declareClass('Propel\Query\ModelJoin');
        $this->declareClass('Propel\Propel');
        
        // Declare related builders for type hints and relationships
        $this->declareClassFromBuilder($this->getStubPeerBuilder());
        $this->declareClassFromBuilder($this->getStubObjectBuilder());
        
        // Call parent implementation to add the standard query methods
        // Note: Parent adds some legacy class declarations that may create duplicates,
        // but our explicit declarations above take precedence for use statements
        parent::addClassBody($script);
        
        // Add __call delegation for tables that have a foreign key to Item
        $this->addItemDelegationCallMethod($script);
    }

    /**
     * Override getUseStatements to provide PHP 8.4 compatible use statements with deduplication
     */
    public function getUseStatements($ignoredNamespace = null)
    {
        $script = '';
        $declaredClasses = $this->declaredClasses;
        unset($declaredClasses[$ignoredNamespace]);
        
        // Build a map of class names to their preferred fully qualified names
        $classMap = [];
        $preferredNamespaces = [
            'PropelException' => 'Propel\\Exception\\PropelException',
            'BasePeer' => 'Propel\\Util\\BasePeer',
            'Criteria' => 'Propel\\Query\\Criteria',
            'ModelCriteria' => 'Propel\\Query\\ModelCriteria',
            'ModelJoin' => 'Propel\\Query\\ModelJoin',
            'PropelPDO' => 'Propel\\Connection\\PropelPDO',
            'PropelCollection' => 'Propel\\Collection\\PropelCollection',
            'PropelObjectCollection' => 'Propel\\Collection\\PropelObjectCollection',
            'Propel' => 'Propel\\Propel',
            'BaseObject' => 'Propel\\OM\\BaseObject',
            'Persistent' => 'Propel\\OM\\Persistent'
        ];
        
        // Collect all classes and prefer properly namespaced versions
        foreach ($declaredClasses as $namespace => $classes) {
            foreach ($classes as $class) {
                $fullName = $namespace ? $namespace . '\\' . $class : $class;
                
                // Skip root namespace classes that have preferred namespaced versions
                if ($namespace === '' && isset($preferredNamespaces[$class])) {
                    continue;
                }
                
                // Use the class name as the key for deduplication
                $classMap[$class] = $fullName;
            }
        }
        
        // Sort by fully qualified name for consistency
        asort($classMap);
        
        foreach ($classMap as $className => $fullName) {
            if (strpos($fullName, '\\') === 0) {
                // Global namespace class (starts with \)
                $script .= sprintf("use %s;\n", $fullName);
            } else {
                // Namespaced class
                $script .= sprintf("use %s;\n", $fullName);
            }
        }
        
        return $script;
    }

    /**
     * Override the addFilterByCrossFK method to generate both direct and cross-reference filter methods
     * 
     * For backward compatibility, we need to generate BOTH:
     * 1. Direct filter method: filterByUser($user) 
     * 2. Cross-reference filter method: filterByUserViaCrossReference($user)
     */
    protected function addFilterByCrossFK(&$script, ForeignKey $refFK, ForeignKey $crossFK): void
    {
        $queryClass = $this->getStubQueryBuilder()->getClassname();
        $crossRefTable = $crossFK->getTable();
        $foreignTable = $crossFK->getForeignTable();
        $fkPhpName = $foreignTable->getPhpName();
        $fkFQCN = '\\' . $this->getNewStubObjectBuilder($foreignTable)->getFullyQualifiedClassname();
        $crossTableName = $crossRefTable->getName();
        $relName = $this->getFKPhpNameAffix($crossFK, false) . 'ViaCrossReference';
        $directRelName = $this->getFKPhpNameAffix($crossFK, false);
        $objectName = '$' . $foreignTable->getStudlyPhpName();
        $relationName = $this->getRefFKPhpNameAffix($refFK, false);

        // Generate the DIRECT filter method for backward compatibility
        $script .= "
    /**
     * Filter the query by a related $fkPhpName object
     * via the cross-reference table
     *
     * @param     $fkFQCN $objectName the related object to use as filter
     * @param     string \$comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return    $queryClass The current query, for fluid interface
     */
    public function filterBy{$directRelName}($objectName, \$comparison = Criteria::EQUAL): $queryClass
    {
        return \$this
            ->use{$relationName}Query()
            ->filterBy{$directRelName}($objectName, \$comparison)
            ->endUse();
    }
";

        // Generate the EXPLICIT cross-reference filter method
        $script .= "
    /**
     * Filter the query by a related $fkPhpName object
     * using the $crossTableName table as cross reference
     *
     * @param     $fkFQCN $objectName the related object to use as filter
     * @param     string \$comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return    $queryClass The current query, for fluid interface
     */
    public function filterBy{$relName}($objectName, \$comparison = Criteria::EQUAL): $queryClass
    {
        return \$this
            ->use{$relationName}Query()
            ->filterBy{$directRelName}($objectName, \$comparison)
            ->endUse();
    }
";
    }

    /**
     * Gets the appropriate PHP 8.4 type hint for filterBy method parameters
     * @param Column $col
     * @return string
     */
    protected function getFilterByParamTypeHint($col): string
    {
        // Check for temporal types first
        if ($col->isTemporalType()) {
            // Ensure DateTimeInterface is imported
            $this->declareClass('\\DateTimeInterface');
            // Accept DateTimeInterface, ints (timestamps), strings, arrays (ranges) or null
            return 'DateTimeInterface|int|string|array|null';
        }
        
        // Check the actual Propel type for better type hints
        // For BIGINT, use int since we're on 64-bit PHP 8.4
        $propelType = $col->getType();
        
        if ($propelType === PropelTypes::BIGINT || $propelType === PropelTypes::INTEGER || 
            $propelType === PropelTypes::SMALLINT || $propelType === PropelTypes::TINYINT) {
            // numeric-like columns accept an int, an array for IN/range queries, or null
            return 'int|array|null';
        }

        if ($propelType === PropelTypes::BOOLEAN) {
            // booleans can be passed as bool or common string representations
            return 'bool|string|null';
        }

        if ($propelType === PropelTypes::PHP_ARRAY) {
            // explicit PHP array column
            return 'array|null';
        }

        if ($col->isTextType()) {
            // text columns accept string or array (IN queries), and may be null
            return 'string|array|null';
        }

        // Fallback: convert the modern PHP type to an explicit union that allows null
        $phpType = $this->getModernPhpType($col);
        // getModernPhpType may return a nullable form like '?string' or '?int'
        if (str_starts_with($phpType, '?')) {
            $base = substr($phpType, 1);
            return $base . '|null';
        }
        // non-null form (e.g. 'int' or 'DateTimeInterface') -> allow null as filter param
        return $phpType . '|null';
    }

    /**
     * Override to add PHP 8.4 type hints to filterBy methods
     */
    protected function addFilterByCol(&$script, $col)
    {
        $colPhpName = $col->getPhpName();
        $colName = $col->getName();
        $variableName = $col->getStudlyPhpName();
        $qualifiedName = $this->getColumnConstant($col);
        $typeHint = $this->getFilterByParamTypeHint($col);
        
        $script .= "
    /**
     * Filter the query on the $colName column
     *";
        if ($col->isNumericType()) {
            $script .= "
     * Example usage:
     * <code>
     * \$query->filterBy$colPhpName(1234); // WHERE $colName = 1234
     * \$query->filterBy$colPhpName(array(12, 34)); // WHERE $colName IN (12, 34)
     * \$query->filterBy$colPhpName(array('min' => 12)); // WHERE $colName > 12
     * </code>";
            if ($col->isForeignKey()) {
                foreach ($col->getForeignKeys() as $fk) {
                    $script .= "
     *
     * @see       filterBy" . $this->getFKPhpNameAffix($fk) . "()";
                }
            }
            $script .= "
     *
         * @param     " . $typeHint . " \$$variableName The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => \$minValue, 'max' => \$maxValue) for intervals.";
        } elseif ($col->isTemporalType()) {
            $script .= "
     * Example usage:
     * <code>
     * \$query->filterBy$colPhpName('2011-03-14'); // WHERE $colName = '2011-03-14'
     * \$query->filterBy$colPhpName('now'); // WHERE $colName = '2011-03-14'
     * \$query->filterBy$colPhpName(array('max' => 'yesterday')); // WHERE $colName > '2011-03-13'
     * </code>
     *
         * @param     " . $typeHint . " \$$variableName The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => \$minValue, 'max' => \$maxValue) for intervals.";
        } elseif ($col->getType() == PropelTypes::PHP_ARRAY) {
            $script .= "
         * @param     " . $typeHint . " \$$variableName The values to use as filter.";
        } elseif ($col->isTextType()) {
            $script .= "
     * Example usage:
     * <code>
     * \$query->filterBy$colPhpName('fooValue');   // WHERE $colName = 'fooValue'
     * \$query->filterBy$colPhpName('%fooValue%'); // WHERE $colName LIKE '%fooValue%'
     * </code>
     *
         * @param     " . $typeHint . " \$$variableName The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE).
     *              Can be an array for IN queries.";
        } elseif ($col->isBooleanType()) {
            $script .= "
     * Example usage:
     * <code>
     * \$query->filterBy$colPhpName(true); // WHERE $colName = true
     * \$query->filterBy$colPhpName('yes'); // WHERE $colName = true
     * </code>
     *
         * @param     " . $typeHint . " \$$variableName The value to use as filter.
     *              Non-boolean arguments are converted using the following rules:
     *                * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *                * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     *              Check on string values is case insensitive (so 'FaLsE' is seen as 'false').";
        } else {
            $script .= "
         * @param     " . $typeHint . " \$$variableName The value to use as filter";
        }
        $script .= "
     * @param     string|null \$comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return    static The current query, for fluid interface
     */
    public function filterBy$colPhpName($typeHint \$$variableName = null, ?string \$comparison = null): static
    {";
        if ($col->isPrimaryKey() && ($col->getType() == PropelTypes::INTEGER || $col->getType() == PropelTypes::BIGINT)) {
            $script .= "
        if (is_array(\$$variableName) && null === \$comparison) {
            \$comparison = Criteria::IN;
        }";
        } elseif ($col->isNumericType() || $col->isTemporalType()) {
            $script .= "
        if (is_array(\$$variableName)) {
            \$useMinMax = false;
            if (isset(\${$variableName}['min'])) {
                \$this->addUsingAlias($qualifiedName, \${$variableName}['min'], Criteria::GREATER_EQUAL);
                \$useMinMax = true;
            }
            if (isset(\${$variableName}['max'])) {
                \$this->addUsingAlias($qualifiedName, \${$variableName}['max'], Criteria::LESS_EQUAL);
                \$useMinMax = true;
            }
            if (\$useMinMax) {
                return \$this;
            }
            if (null === \$comparison) {
                \$comparison = Criteria::IN;
            }
        }";
        } elseif ($col->getType() == PropelTypes::PHP_ARRAY) {
            $script .= "
        \$key = \$this->getAliasedColName($qualifiedName);
        if (null === \$comparison || \$comparison == Criteria::CONTAINS_ALL) {
            foreach ((array) \$$variableName as \$value) {
                \$value = '%| ' . \$value . ' |%';
                if (\$this->containsKey(\$key)) {
                    \$this->addAnd(\$key, \$value, Criteria::LIKE);
                } else {
                    \$this->add(\$key, \$value, Criteria::LIKE);
                }
            }

            return \$this;
        } elseif (\$comparison == Criteria::CONTAINS_SOME) {
            foreach ((array) \$$variableName as \$value) {
                \$value = '%| ' . \$value . ' |%';
                if (\$this->containsKey(\$key)) {
                    \$this->addOr(\$key, \$value, Criteria::LIKE);
                } else {
                    \$this->add(\$key, \$value, Criteria::LIKE);
                }
            }

            return \$this;
        } elseif (\$comparison == Criteria::CONTAINS_NONE) {
            foreach ((array) \$$variableName as \$value) {
                \$value = '%| ' . \$value . ' |%';
                if (\$this->containsKey(\$key)) {
                    \$this->addAnd(\$key, \$value, Criteria::NOT_LIKE);
                } else {
                    \$this->add(\$key, \$value, Criteria::NOT_LIKE);
                }
            }
            \$this->addOr(\$key, null, Criteria::ISNULL);

            return \$this;
        }";
        } elseif ($col->isTextType()) {
            $script .= "
        if (null === \$comparison) {
            if (is_array(\$$variableName)) {
                \$comparison = Criteria::IN;
            } elseif (\$$variableName !== null && preg_match('/[\%\*]/', \$$variableName)) {
                \$$variableName = str_replace('*', '%', \$$variableName);
                \$comparison = Criteria::LIKE;
            }
        }";
        } elseif ($col->isBooleanType()) {
            $script .= "
        if (is_string(\$$variableName)) {
            \$boolVal = in_array(strtolower(\$$variableName), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
            \$$variableName = \$boolVal;
        }";
        }
        $script .= "

        return \$this->addUsingAlias($qualifiedName, \$$variableName, \$comparison);
    }
";
    } // addFilterByCol
    
    /**
     * Add __call method to delegate unknown filterBy* calls to a foreign relation
     * if the table has a "delegate" behavior configured.
     * This allows tables to act as if they "extend" another table by delegating
     * column filters to the related table's query.
     *
     * @param string &$script The script will be modified in this method.
     */
    protected function addItemDelegationCallMethod(&$script): void
    {
        // Check if this table has a "delegate" behavior
        $delegateBehavior = null;
        $delegateToTable = null;
        
        foreach ($this->getTable()->getBehaviors() as $behavior) {
            if ($behavior->getName() === 'delegate') {
                $delegateBehavior = $behavior;
                // Get the "to" parameter which specifies which table to delegate to
                $delegateToTable = $behavior->getParameter('to');
                break;
            }
        }
        
        // Only add the __call method if there's a delegate behavior
        if ($delegateBehavior === null || !$delegateToTable) {
            return;
        }
        
        // Find the foreign key that references the delegate table
        $delegateForeignKey = null;
        foreach ($this->getTable()->getForeignKeys() as $fk) {
            if ($fk->getForeignTableName() === $delegateToTable) {
                $delegateForeignKey = $fk;
                break;
            }
        }
        
        if ($delegateForeignKey === null) {
            return;
        }
        
        // Get the phpName of the foreign key to use in useXXXQuery()
        $fkPhpName = $this->getFKPhpNameAffix($delegateForeignKey);
        $useMethodName = 'use' . $fkPhpName . 'Query';
        
        $script .= "
    /**
     * Delegate unknown method calls to the {$fkPhpName} relation query.
     * This allows filtering by {$fkPhpName} columns even though they don't exist on this table.
     * This is enabled by the 'delegate' behavior in the schema.
     *
     * @param string \$name The method name
     * @param array \$arguments The method arguments
     * @return mixed
     * @throws \\Propel\\Exception\\PropelException
     */
    public function __call(\$name, \$arguments)
    {
        // Try to handle it via the parent's __call first (for standard magic methods)
        try {
            return parent::__call(\$name, \$arguments);
        } catch (\\Propel\\Exception\\PropelException \$e) {
            // If it's a filterBy* method that failed, try delegating to the related table
            if (str_starts_with(\$name, 'filterBy')) {
                // Attempt to delegate to the related query
                try {
                    \$relatedQuery = \$this->{$useMethodName}();
                    \$result = call_user_func_array([\$relatedQuery, \$name], \$arguments);
                    return \$result->endUse();
                } catch (\\Exception \$delegateException) {
                    // If that also fails, throw the original exception
                    throw \$e;
                }
            }
            
            // If it's not a filterBy method, throw the original exception
            throw \$e;
        }
    }
";
    }
}