<?php

/**
 * This file is part of the Propel package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propel\Generator\Builder\OM;

/**
 * Generates the empty PHP 8.4 stub object class for use with inheritance in the user object model (OM).
 *
 * This class produces the empty stub class that can be customized with application
 * business logic, custom behavior, etc. with modern PHP 8.4 features:
 * - Proper namespace usage
 * - Typed properties and methods
 * - Constructor property promotion where applicable
 * - Modern inheritance patterns
 *
 * @author     GitHub Copilot
 * @package    propel.generator.builder.om
 */
use Propel\Generator\Model\Inheritance;
use Phing\Exception\BuildException;

class PHP84MultiExtendObjectBuilder extends ObjectBuilder
{

	/**
	 * The current child "object" we are operating on.
	 */
	private ?Inheritance $child = null;

	/**
	 * Returns the name of the current class being built.
	 * @return     string
	 */
	public function getUnprefixedClassname(): string
	{
		return $this->getChild()->getClassname();
	}

	/**
	 * Override method to return child package, if specified.
	 * @return     string
	 */
	public function getPackage(): string
	{
		return $this->child?->getPackage() ?: parent::getPackage();
	}

	public function getNamespace(): ?string
	{
		if ($namespace = parent::getNamespace()) {
			if ($this->getGeneratorConfig() && $omns = $this->getGeneratorConfig()->getBuildProperty('namespaceOm')) {
				return $namespace . '\\' . $omns;
			} else {
				return $namespace;
			}
		}
		return null;
	}

	/**
	 * Set the child object that we're operating on currently.
	 * @param      Inheritance $child
	 */
	public function setChild(Inheritance $child): void
	{
		$this->child = $child;
	}

	/**
	 * Returns the child object we're operating on currently.
	 * @return     Inheritance
	 * @throws     BuildException - if child was not set.
	 */
	public function getChild(): Inheritance
	{
		if (!$this->child) {
			throw new BuildException("The PHP84MultiExtendObjectBuilder needs to be told which child class to build (via setChild() method) before it can build the stub class.");
		}
		return $this->child;
	}

	/**
	 * Returns classpath to parent class.
	 * @return     string
	 */
	protected function getParentClasspath(): string
	{
		return $this->getChild()->getAncestor() ?: $this->getObjectBuilder()->getClasspath();
	}

	/**
	 * Returns classname of parent class.
	 * @return     string
	 */
	protected function getParentClassname(): string
	{
		return ClassTools::classname($this->getParentClasspath());
	}

	/**
	 * Gets the file path to the parent class.
	 * @return     string
	 */
	protected function getParentClassFilePath(): string
	{
		return ClassTools::getFilePath($this->getParentClasspath());
	}

	/**
	 * Adds the include() statements for files that this class depends on or utilizes.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addIncludes(&$script = null): void
	{
		// PHP 8.4 uses namespaces and autoloading, so includes are minimal
	}

	/**
	 * Adds class phpdoc comment and opening of class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassOpen(&$script): void
	{
		$table = $this->getTable();
		$tableName = $table->getName();
		$tableDesc = $table->getDescription();
		
		$script .= "
/**
 * Stub child class for representing a row from the '$tableName' table.
 *
 * $tableDesc
 *";
		if ($this->getBuildProperty('addTimeStamp')) {
			$now = datefmt_create(
				'en_US',
				\IntlDateFormatter::FULL,
				\IntlDateFormatter::FULL,
				'Europe/Helsinki',
				\IntlDateFormatter::GREGORIAN,
				"yyyy-MM-dd HH:mm:ss"
			);
			$script .= "
 * This class was autogenerated by Propel " . $this->getBuildProperty('version') . " on:
 *
 * " . datefmt_format($now, 0) . "
 *";
		}
		$script .= "
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.".$this->getPackage()."
 */
class ".$this->getClassname()." extends ".$this->getParentClassname()."
{
";
	}

	/**
	 * Specifies the methods that are added as part of the stub object class.
	 *
	 * By default there are no methods for the empty stub classes; override this method
	 * if you want to change that behavior.
	 *
	 * @see        ObjectBuilder::addClassBody()
	 */
	protected function addClassBody(&$script): void
	{
		// Stub class body is intentionally empty
	}

	/**
	 * Closes class definition.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassClose(&$script): void
	{
		$script .= "
}
";
	}

	public function build(): string
	{
		$script = '';
		
		if ($this->getNamespace()) {
			$script .= "<?php

namespace " . $this->getNamespace() . ";

";
		} else {
			$script .= "<?php

";
		}

		$this->addClassOpen($script);
		$this->addClassBody($script);
		$this->addClassClose($script);

		return $script;
	}
}
