<?php

/**
 * This file is part of the Propulsion package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propulsion\Generator\Builder\OM;

/**
 * Generates the base Query class for user object model (OM).
 *
 * This class produces the base query class (e.g. BaseBookQuery) which contains all
 * the custom-built query methods, using modern PHP 8.4 features (typed properties,
 * typed method signatures, etc). The legacy untyped equivalent lives on as
 * PHP5QueryBuilder for anyone who explicitly opts into propulsion.targetPlatform=php5.
 *
 * @author     Francois Zaninotto
 * @author     Modernized for PHP 8.4
 */
use Propulsion\Generator\Model\PropulsionTypes;
use Propulsion\Generator\Model\ForeignKey;
class QueryBuilder extends OMBuilder
{

    /**
     * Gets the package for the [base] object classes.
     * @return     string
     */
    public function getPackage()
    {
        $pkg = ($this->getTable()->getPackage() ? $this->getTable()->getPackage() : $this->getDatabase()->getPackage());
        if (!$pkg) {
            $pkg = $this->getBuildProperty('targetPackage');
        }
        return $pkg . ".om";
    }

    public function getNamespace()
    {
        if ($namespace = parent::getNamespace()) {
            if ($omns = $this->getGeneratorConfig()->getBuildProperty('namespaceOm')) {
                return $namespace . '\\' . $omns;
            } else {
                return $namespace;
            }
        }
        return null;
    }

    /**
     * Returns the name of the current class being built.
     * @return     string
     */
    public function getUnprefixedClassname()
    {
        return $this->getBuildProperty('basePrefix') . $this->getStubQueryBuilder()->getUnprefixedClassname();
    }

    /**
     * Adds the include() statements for files that this class depends on or utilizes.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addIncludes(&$script = null)
    {
    }

    /**
     * Adds class phpdoc comment and opening of class with modern PHP 8.4 features.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addClassOpen(&$script): void
    {
        $table = $this->getTable();
        $tableName = $table->getName();
        $tableDesc = $table->getDescription();
        $queryClass = $this->getStubQueryBuilder()->getClassname();
        $modelClass = $this->getStubObjectBuilder()->getClassname();
        $parentClass = $this->getBehaviorContent('parentClass');
        $parentClass = $parentClass ?? 'ModelCriteria';

        $script .= "
/**
 * Base class that represents a query for the '$tableName' table.
 *
 * $tableDesc
 *";
        if ($this->getBuildProperty('addTimeStamp')) {
            $now = datefmt_create(
                'en_US',
                \IntlDateFormatter::FULL,
                \IntlDateFormatter::FULL,
                'Europe/Helsinki',
                \IntlDateFormatter::GREGORIAN,
                "yyyy-MM-dd HH:mm:ss"
            );
            $script .= "
 * This class was autogenerated by Propulsion " . $this->getBuildProperty('version') . " on:
 *
 * " . datefmt_format($now, time()) . "
 *";
        }

        // Modern typed magic orderBy() methods for IDE completion
        foreach ($this->getTable()->getColumns() as $column) {
            $script .= "
 * @method     $queryClass orderBy" . $column->getPhpName() . "(string \$order = Criteria::ASC) Order by the " . $column->getName() . " column";
        }
        $script .= "
 *";

        // Modern typed magic groupBy() methods for IDE completion
        foreach ($this->getTable()->getColumns() as $column) {
            $script .= "
 * @method     $queryClass groupBy" . $column->getPhpName() . "() Group by the " . $column->getName() . " column";
        }
        $script .= "
 *";

        // Modern typed magic filterBy() methods for IDE completion
        // Note: filterBy methods accept the column type OR array (for IN queries, ranges, etc.)
        foreach ($this->getTable()->getColumns() as $column) {
            $phpType = $this->getModernPhpType($column);
            // Convert ?T to T|null for union types (PHPDoc doesn't support ?T in unions)
            $baseType = ltrim($phpType, '?');
            $filterType = $baseType . '|array' . (str_starts_with($phpType, '?') ? '|null' : '');
            $script .= "
 * @method     $queryClass filterBy" . $column->getPhpName() . "($filterType \$" . $column->getName() . ", ?string \$comparison = null) Filter by the " . $column->getName() . " column";
        }

        // Override signatures with modern type hints
        $script .= "
 *
 * @method     $queryClass leftJoin(string \$relation) Adds a LEFT JOIN clause to the query
 * @method     $queryClass rightJoin(string \$relation) Adds a RIGHT JOIN clause to the query
 * @method     $queryClass innerJoin(string \$relation) Adds a INNER JOIN clause to the query
 * @method     $queryClass joinWith(string \$relation, ?string \$joinType = null) Adds a join with the columns of the related table
 * @method     $queryClass addJoinObject(\\Propulsion\\Query\\ModelJoin \$join, ?string \$name = null) Adds a join object to the query
 * @method     $queryClass useQuery(string \$relationName, ?string \$secondTableAlias = null) Use the relation as sub query
 * @method     $queryClass mergeWith(\\Propulsion\\Query\\Criteria \$criteria) Merge the conditions of another Criteria into this one
 * @method     $queryClass addUsingAlias(string \$column, mixed \$value, ?string \$comparison = null) Add a condition using a column alias
 *";

        // Modern typed XXXjoinYYY() methods for IDE completion
        foreach ($this->getTable()->getForeignKeys() as $fk) {
            $relationName = $this->getFKPhpNameAffix($fk);
            $script .= "
 * @method     $queryClass leftJoin" . $relationName . "(?string \$relationAlias = null) Adds a LEFT JOIN clause using the " . $relationName . " relation
 * @method     $queryClass rightJoin" . $relationName . "(?string \$relationAlias = null) Adds a RIGHT JOIN clause using the " . $relationName . " relation
 * @method     $queryClass innerJoin" . $relationName . "(?string \$relationAlias = null) Adds a INNER JOIN clause using the " . $relationName . " relation
 * @method     $queryClass joinWith" . $relationName . "(?string \$joinType = null) Adds a join with the " . $relationName . " relation columns
 *";
        }

        foreach ($this->getTable()->getReferrers() as $refFK) {
            $relationName = $this->getRefFKPhpNameAffix($refFK);
            $script .= "
 * @method     $queryClass leftJoin" . $relationName . "(?string \$relationAlias = null) Adds a LEFT JOIN clause using the " . $relationName . " relation
 * @method     $queryClass rightJoin" . $relationName . "(?string \$relationAlias = null) Adds a RIGHT JOIN clause using the " . $relationName . " relation
 * @method     $queryClass innerJoin" . $relationName . "(?string \$relationAlias = null) Adds a INNER JOIN clause using the " . $relationName . " relation
 *";
        }

        // Modern typed findOne() methods
        $script .= "
 * @method     ?$modelClass findOne(?PropulsionPDO \$con = null) Return the first $modelClass matching the query
 * @method     $modelClass findOneOrCreate(?PropulsionPDO \$con = null) Return the first $modelClass matching the query, or a new $modelClass object
 * @method     PropulsionObjectCollection<$modelClass> find(?PropulsionPDO \$con = null) Return $modelClass objects based on current query
 * @method     ?$modelClass findPk(mixed \$key, ?PropulsionPDO \$con = null) Return the $modelClass matching the primary key
 * @method     PropulsionObjectCollection<$modelClass> findPks(mixed \$keys, ?PropulsionPDO \$con = null) Return $modelClass objects matching the primary keys
 * @method     int count(?PropulsionPDO \$con = null) Count the number of matching records
 * @method     \\Propulsion\\Util\\PropulsionModelPager paginate(int \$page = 1, int \$maxPerPage = 10, ?PropulsionPDO \$con = null) Paginate the results
 * @method     int delete(?PropulsionPDO \$con = null) Delete matching records
 * @method     int update(array \$values, ?PropulsionPDO \$con = null, bool \$forceIndividualSaves = false) Update matching records
 *";

        // Modern typed findBy() methods with proper type hints
        foreach ($this->getTable()->getColumns() as $column) {
            $phpType = $this->getModernPhpType($column);
            $script .= "
 * @method     ?$modelClass findOneBy" . $column->getPhpName() . "($phpType \$" . $column->getName() . ") Return the first $modelClass filtered by the " . $column->getName() . " column";
        }
        $script .= "
 *";

        foreach ($this->getTable()->getColumns() as $column) {
            $phpType = $this->getModernPhpType($column);
            $script .= "
 * @method     array<$modelClass> findBy" . $column->getPhpName() . "($phpType \$" . $column->getName() . ") Return $modelClass objects filtered by the " . $column->getName() . " column";
        }

        // Add useQuery methods for foreign key relationships
        foreach ($this->getTable()->getForeignKeys() as $fk) {
            $relationName = $this->getFKPhpNameAffix($fk);
            $relatedQueryClass = $this->getNewStubQueryBuilder($fk->getForeignTable())->getFullyQualifiedClassname();
            $script .= "
 * @method     \\$relatedQueryClass use" . $relationName . "Query(?string \$relationAlias = null) Use the " . $relationName . " relation query object";
        }

        foreach ($this->getTable()->getReferrers() as $refFK) {
            $relationName = $this->getRefFKPhpNameAffix($refFK);
            $relatedQueryClass = $this->getNewStubQueryBuilder($refFK->getTable())->getFullyQualifiedClassname();
            $script .= "
 * @method     \\$relatedQueryClass use" . $relationName . "Query(?string \$relationAlias = null) Use the " . $relationName . " relation query object";
        }

        // Add findOneBy and findBy magic methods for foreign key relationships (accept relation objects)
        // Note: filterBy methods are generated as real methods, not magic methods
        $script .= "
 *";
        foreach ($this->getTable()->getForeignKeys() as $fk) {
            $relationName = $this->getFKPhpNameAffix($fk);
            $relatedModelClass = $this->getNewStubObjectBuilder($fk->getForeignTable())->getFullyQualifiedClassname();
            $script .= "
 * @method     ?$modelClass findOneBy" . $relationName . "(\\$relatedModelClass \$" . lcfirst($relationName) . ") Return the first $modelClass filtered by the " . $relationName . " relation
 * @method     array<$modelClass> findBy" . $relationName . "(\\$relatedModelClass \$" . lcfirst($relationName) . ") Return $modelClass objects filtered by the " . $relationName . " relation";
        }

        foreach ($this->getTable()->getReferrers() as $refFK) {
            $relationName = $this->getRefFKPhpNameAffix($refFK);
            $relatedModelClass = $this->getNewStubObjectBuilder($refFK->getTable())->getFullyQualifiedClassname();
            $script .= "
 * @method     ?$modelClass findOneBy" . $relationName . "(\\$relatedModelClass \$" . lcfirst($relationName) . ") Return the first $modelClass filtered by the " . $relationName . " relation
 * @method     array<$modelClass> findBy" . $relationName . "(\\$relatedModelClass \$" . lcfirst($relationName) . ") Return $modelClass objects filtered by the " . $relationName . " relation";
        }

        // Add @method annotations for inherited Criteria methods to fix fluent interface
        $script .= "
 *
 * @method     $queryClass add(string \$column, mixed \$value = null, ?string \$comparison = null) Add a condition to the query
 * @method     $queryClass addCond(string \$name, string \$column, mixed \$value = null, ?string \$comparison = null) Add a named condition
 * @method     $queryClass addOr(string \$column, mixed \$value = null, ?string \$comparison = null) Add an OR condition
 * @method     $queryClass addAnd(string \$column, mixed \$value = null, ?string \$comparison = null) Add an AND condition
 * @method     $queryClass where(string|array \$clause, mixed \$value = null) Add a WHERE clause to the query
 * @method     $queryClass condition(string \$conditionName, string \$clause, mixed \$value = null) Add a named condition
 * @method     $queryClass mergeWith(\\Propulsion\\Query\\Criteria \$criteria) Merge conditions from another Criteria object
 * @method     $queryClass addJoin(string \$left, string \$right, ?string \$joinType = null) Add a join condition
 * @method     $queryClass addGroupByColumn(string \$column) Add a GROUP BY column
 * @method     $queryClass addSelectColumn(string \$column) Add a column to the SELECT clause
 * @method     $queryClass addSelfSelectColumns() Add the columns of the current table to the SELECT clause
 * @method     $queryClass addHaving(\\Propulsion\\Query\\Criterion \$having) Add a HAVING condition
 * @method     $queryClass addAscendingOrderByColumn(string \$column) Add ascending order by column
 * @method     $queryClass addDescendingOrderByColumn(string \$column) Add descending order by column
 * @method     $queryClass setIgnoreCase(bool \$ignoreCase) Set ignore case flag for string comparisons
 * @method     $queryClass setDistinct() Add DISTINCT modifier to the query
 * @method     $queryClass setLimit(int \$limit) Set the maximum number of records to return
 * @method     $queryClass setOffset(int \$offset) Set the number of records to skip
 * @method     $queryClass setComment(?string \$comment) Set a comment for the query
 * @method     $queryClass limit(int \$limit) Alias for setLimit()
 * @method     $queryClass offset(int \$offset) Alias for setOffset()
 * @method     $queryClass distinct() Alias for setDistinct()
 *
 */
abstract class ".$this->getClassname()." extends " . $parentClass . "
{
    ";
    }

    /**
     * Get modern PHP 8.4 type for a column
     */
    protected function getModernPhpType($column): string
    {
        if ($column->isTemporalType()) {
            $this->declareClass('\\DateTimeInterface');
            return $column->isNotNull() ? 'DateTimeInterface' : '?DateTimeInterface';
        }

        // Check the actual Propulsion type for better type hints
        // For BIGINT, use int since we're on 64-bit PHP 8.4 (handles up to 2^63-1)
        $propelType = $column->getType();

        if ($propelType === PropulsionTypes::BIGINT || $propelType === PropulsionTypes::INTEGER ||
            $propelType === PropulsionTypes::SMALLINT || $propelType === PropulsionTypes::TINYINT) {
            return $column->isNotNull() ? 'int' : '?int';
        }

        // Fall back to the PHP type mapping
        $phpType = $column->getPhpType();

        if ($phpType === 'DateTime') {
            $this->declareClass('\\DateTimeInterface');
            return $column->isNotNull() ? 'DateTimeInterface' : '?DateTimeInterface';
        }

        // Convert to modern nullable types where appropriate
        if ($column->isNotNull()) {
            return match($phpType) {
                'int' => 'int',
                'string' => 'string',
                'boolean' => 'bool',
                'double' => 'float',
                'resource' => 'resource',
                default => $phpType
            };
        }

        return match($phpType) {
            'int' => '?int',
            'string' => '?string',
            'boolean' => '?bool',
            'double' => '?float',
            'resource' => '?resource',
            default => '?' . $phpType
        };
    }

    /**
     * Override getUseStatements to provide PHP 8.4 compatible use statements with deduplication
     */
    public function getUseStatements($ignoredNamespace = null)
    {
        $script = '';
        $declaredClasses = $this->declaredClasses;
        unset($declaredClasses[$ignoredNamespace]);

        // Build a map of class names to their preferred fully qualified names.
        // These Propulsion\* core classes are aliased into the *global* namespace by
        // runtime/Lib/legacy-class-map.php, so a bare reference to e.g. `Criteria` only
        // resolves correctly on its own when the referencing class has no namespace of its
        // own -- inside a real `namespace Foo\Bar;` block, an unimported bare name resolves
        // relative to that namespace (`Foo\Bar\Criteria`), not globally, so a real `use`
        // import is still required there.
        $classMap = [];
        $preferredNamespaces = [
            'PropulsionException' => 'Propulsion\\Exception\\PropulsionException',
            'BasePeer' => 'Propulsion\\Util\\BasePeer',
            'Criteria' => 'Propulsion\\Query\\Criteria',
            'ModelCriteria' => 'Propulsion\\Query\\ModelCriteria',
            'ModelJoin' => 'Propulsion\\Query\\ModelJoin',
            'PropulsionPDO' => 'Propulsion\\Connection\\PropulsionPDO',
            'PropulsionCollection' => 'Propulsion\\Collection\\PropulsionCollection',
            'PropulsionObjectCollection' => 'Propulsion\\Collection\\PropulsionObjectCollection',
            'Propulsion' => 'Propulsion\\Propulsion',
            'BaseObject' => 'Propulsion\\OM\\BaseObject',
            'Persistent' => 'Propulsion\\OM\\Persistent'
        ];
        // True for the flat/legacy-style generation target (e.g. the bookstore fixture, or
        // any PropulsionQuickBuilder-built schema): no `namespace` statement of its own, so bare
        // core-class references already resolve via the global alias above with no import
        // needed -- and PropulsionQuickBuilder concatenates many such classes into a single
        // eval()'d script with no namespace block between them, so emitting the same
        // `use Fully\Qualified\Name;` once per class (as addClassBody()'s FQCN
        // declareClass() calls would otherwise cause here) is a fatal redeclaration.
        $isFlat = !$this->getNamespace();

        // Collect all classes and prefer properly namespaced versions
        foreach ($declaredClasses as $namespace => $classes) {
            foreach ($classes as $class) {
                $fullName = $namespace ? $namespace . '\\' . $class : $class;

                if ($isFlat && isset($preferredNamespaces[$class])
                    && ($namespace === '' || $fullName === $preferredNamespaces[$class])) {
                    // Flat target referencing a globally-aliased core class: no import needed.
                    continue;
                }

                if (!$isFlat && $namespace === '' && isset($preferredNamespaces[$class])) {
                    // Namespaced target with a legacy bare declare of a core class: import its
                    // real FQCN, since a bare reference here would resolve relative to this
                    // class's own namespace instead.
                    $fullName = $preferredNamespaces[$class];
                }

                // Use the class name as the key for deduplication
                $classMap[$class] = $fullName;
            }
        }

        // Sort by fully qualified name for consistency
        asort($classMap);

        foreach ($classMap as $className => $fullName) {
            $script .= sprintf("use %s;\n", $fullName);
        }

        return $script;
    }

    /**
     * Specifies the methods that are added as part of the stub object class.
     *
     * By default there are no methods for the empty stub classes; override this method
     * if you want to change that behavior.
     *
     * @see        AbstractObjectBuilder::addClassBody()
     */
    protected function addClassBody(&$script): void
    {
        // Declare essential classes for Base*Query classes with proper namespaces
        $this->declareClass('Propulsion\Query\ModelCriteria');
        $this->declareClass('Propulsion\Connection\PropulsionPDO');
        $this->declareClass('Propulsion\Query\Criteria');
        $this->declareClass('Propulsion\Exception\PropulsionException');
        $this->declareClass('Propulsion\Collection\PropulsionCollection');
        $this->declareClass('Propulsion\Collection\PropulsionObjectCollection');
        $this->declareClass('Propulsion\Query\ModelJoin');
        $this->declareClass('Propulsion\Propulsion');

        // Declare related builders for type hints and relationships
        $this->declareClassFromBuilder($this->getStubPeerBuilder());
        $this->declareClassFromBuilder($this->getStubObjectBuilder());

        // namespaces
        $this->declareClasses('ModelCriteria', 'Criteria', 'ModelJoin');
        $this->declareClassFromBuilder($this->getStubQueryBuilder());
        $this->declareClassFromBuilder($this->getStubPeerBuilder());

        // apply behaviors
        $this->applyBehaviorModifier('queryAttributes', $script, "	");
        $this->addConstructor($script);
        $this->addFactory($script);
        $this->addFindPk($script);
        $this->addFindPks($script);
        $this->addFilterByPrimaryKey($script);
        $this->addFilterByPrimaryKeys($script);
        foreach ($this->getTable()->getColumns() as $col) {
            $this->addFilterByCol($script, $col);
            if ($col->getType() === PropulsionTypes::PHP_ARRAY && $col->isNamePlural()) {
                $this->addFilterByArrayCol($script, $col);
            }
        }
        foreach ($this->getTable()->getForeignKeys() as $fk) {
            $this->addFilterByFK($script, $fk);
            $this->addJoinFk($script, $fk);
            $this->addUseFKQuery($script, $fk);
        }
        foreach ($this->getTable()->getReferrers() as $refFK) {
            $this->addFilterByRefFK($script, $refFK);
            $this->addJoinRefFk($script, $refFK);
            $this->addUseRefFKQuery($script, $refFK);
        }
        foreach ($this->getTable()->getCrossFks() as $fkList) {
            list($refFK, $crossFK) = $fkList;
            $this->addFilterByCrossFK($script, $refFK, $crossFK);
        }
        $this->addPrune($script);
        $this->addBasePreSelect($script);
        $this->addBasePreDelete($script);
        $this->addBasePostDelete($script);
        $this->addBasePreUpdate($script);
        $this->addBasePostUpdate($script);
        // apply behaviors
        $this->applyBehaviorModifier('queryMethods', $script, "	");

        // Add __call delegation for tables that have a foreign key to Item
        $this->addItemDelegationCallMethod($script);
    }

    /**
     * Closes class.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addClassClose(&$script)
    {
        $script .= "
} // " . $this->getClassname() . "";
        $this->applyBehaviorModifier('queryFilter', $script, "");
    }

    /**
     * Adds the constructor with modern PHP 8.4 features.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addConstructor(&$script): void
    {
        $script .= "
    /**
     * Initializes internal state of " . $this->getClassname() . " object.
     * @param      ?string \$dbName The database name
     * @param      ?string \$modelName The phpName of a model, e.g. 'Book'
     * @param      ?string \$modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct(?string \$dbName = '" . $this->getTable()->getDatabase()->getName() . "', ?string \$modelName = '" . addslashes($this->getStubObjectBuilder()->getFullyQualifiedClassname()) . "', ?string \$modelAlias = null)
    {
        parent::__construct(\$dbName, \$modelName, \$modelAlias);
    }
";
    }

    /**
     * Adds the comment for the constructor (unused by addConstructor() above,
     * kept only in case a behavior calls it directly).
     * @param      string &$script The script will be modified in this method.
     **/
    protected function addConstructorComment(&$script)
    {
        $script .= "
    /**
     * Initializes internal state of ".$this->getClassname()." object.
     *
     * @param     string \$dbName The dabase name
     * @param     string \$modelName The phpName of a model, e.g. 'Book'
     * @param     string \$modelAlias The alias for the model in this query, e.g. 'b'
     */";
    }

    /**
     * Adds the function declaration for the constructor
     * @param      string &$script The script will be modified in this method.
     **/
    protected function addConstructorOpen(&$script)
    {
        $table = $this->getTable();
        $script .= "
    public function __construct(\$dbName = '" . $table->getDatabase()->getName() . "', \$modelName = '" . addslashes($this->getNewStubObjectBuilder($table)->getFullyQualifiedClassname()) . "', \$modelAlias = null)
    {";
    }

    /**
     * Adds the function body for the constructor
     * @param      string &$script The script will be modified in this method.
     **/
    protected function addConstructorBody(&$script)
    {
        $script .= "
        parent::__construct(\$dbName, \$modelName, \$modelAlias);";
    }

    /**
     * Adds the function close for the constructor
     * @param      string &$script The script will be modified in this method.
     **/
    protected function addConstructorClose(&$script)
    {
        $script .= "
    }
";
    }

    /**
     * Adds factory method with modern typing.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFactory(&$script): void
    {
        $script .= "
    /**
     * Returns a new " . $this->getStubQueryBuilder()->getClassname() . " object.
     *
     * @param      ?string \$modelAlias The alias of a model in the query
     * @param      ?Criteria \$criteria Optional Criteria to build the query from
     *
     * @return     " . $this->getStubQueryBuilder()->getClassname() . "
     */
    public static function create(?string \$modelAlias = null, ?Criteria \$criteria = null): " . $this->getStubQueryBuilder()->getClassname() . "
    {
        if (\$criteria instanceof " . $this->getStubQueryBuilder()->getClassname() . ") {
            return \$criteria;
        }
        \$query = new " . $this->getStubQueryBuilder()->getClassname() . "();
        if (null !== \$modelAlias) {
            \$query->setModelAlias(\$modelAlias);
        }
        if (\$criteria instanceof Criteria) {
            \$query->mergeWith(\$criteria);
        }
        return \$query;
    }
";
    }

    /**
     * Adds the comment for the factory (unused by addFactory() above, kept
     * only in case a behavior calls it directly).
     * @param      string &$script The script will be modified in this method.
     **/
    protected function addFactoryComment(&$script)
    {
        $classname = $this->getNewStubQueryBuilder($this->getTable())->getClassname();
        $script .= "
    /**
     * Returns a new " . $classname . " object.
     *
     * @param     string \$modelAlias The alias of a model in the query
     * @param     Criteria \$criteria Optional Criteria to build the query from
     *
     * @return    " . $classname . "
     */";
    }

    /**
     * Adds the function declaration for the factory
     * @param      string &$script The script will be modified in this method.
     **/
    protected function addFactoryOpen(&$script)
    {
        $script .= "
    public static function create(\$modelAlias = null, \$criteria = null)
    {";
    }

    /**
     * Adds the function body for the factory
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFactoryBody(&$script)
    {
        $classname = $this->getNewStubQueryBuilder($this->getTable())->getClassname();
        $script .= "
        if (\$criteria instanceof " . $classname . ") {
            return \$criteria;
        }
        \$query = new " . $classname . "();
        if (null !== \$modelAlias) {
            \$query->setModelAlias(\$modelAlias);
        }
        if (\$criteria instanceof Criteria) {
            \$query->mergeWith(\$criteria);
        }
        return \$query;";
    }

    /**
     * Adds the function close for the factory
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFactoryClose(&$script)
    {
        $script .= "
    }
";
    }

    /**
     * Adds the findPk method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFindPk(&$script)
    {
        $table = $this->getTable();
        $pks = $table->getPrimaryKey();
        $class = $class = $this->getStubObjectBuilder()->getClassname();
        $this->declareClasses('PropulsionPDO');
        $script .= "
    /**
     * Find object by primary key";
        if (count($pks) === 1) {
            $pkType = 'mixed';
            $script .= "
     * Use instance pooling to avoid a database query if the object exists
     * <code>
     * \$obj  = \$c->findPk(12, \$con);";
        } else {
            $examplePk = array_slice(array(12, 34, 56, 78, 91), 0, count($pks));
            $colNames = array();
            foreach ($pks as $col) {
                $colNames[]= '$' . $col->getName();
            }
            $pkType = 'array['. join(', ', $colNames) . ']';
            $script .= "
     * <code>
     * \$obj = \$c->findPk(array(" . join(', ', $examplePk) . "), \$con);";
        }
        $script .= "
     * </code>
     * @param     " . $pkType . " \$key Primary key to use for the query
     * @param     PropulsionPDO \$con an optional connection object
     *
     * @return    mixed the result, formatted by the current formatter (null if not found)
     */
    public function findPk(mixed \$key, ?PropulsionPDO \$con = null) : mixed
    {";
        if (count($pks) === 1) {
            $poolKeyHashParams = '$key';
        } else {
            $poolKeyHashParams = array();
            for ($i = 0, $count = count($pks); $i < $count; $i++) {
                $poolKeyHashParams[]= '$key[' . $i . ']';
            }
        }
        // tip: we don't use findOne() to avoid putting an unecessary LIMIT 1 statement,
        // which may be costly on platforms not natively supporting LIMIT (like Oracle)
        $peerBuilder = $this->getPeerBuilder();
        $instancePoolKeySnippet = $peerBuilder instanceof PeerBuilder ? $peerBuilder->getInstancePoolKeySnippet($poolKeyHashParams) : '';
        $script .= "
        if ((null !== (\$obj = ".$this->getPeerClassname()."::getInstanceFromPool(".$instancePoolKeySnippet."))) && \$this->getFormatter()->isObjectFormatter()) {
            // the object is alredy in the instance pool
            return \$obj;
        } else {
            // the object has not been requested yet, or the formatter is not an object formatter
            \$criteria = \$this->isKeepQuery() ? clone \$this : \$this;
            \$stmt = \$criteria
                ->filterByPrimaryKey(\$key)
                ->getSelectStatement(\$con);
            return \$criteria->getFormatter()->init(\$criteria)->formatOne(\$stmt);
        }
    }
";
    }

    /**
     * Adds the findPks method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFindPks(&$script)
    {
        $this->declareClasses('PropulsionPDO', 'PropulsionObjectCollection');
        $table = $this->getTable();
        $pks = $table->getPrimaryKey();
        $count = count($pks);
        $script .= "
    /**
     * Find objects by primary key
     * <code>";
        if ($count === 1) {
            $script .= "
     * \$objs = \$c->findPks(array(12, 56, 832), \$con);";
        } else {
            $script .= "
     * \$objs = \$c->findPks(array(array(12, 56), array(832, 123), array(123, 456)), \$con);";
        }
        $script .= "
     * </code>
     * @param     array \$keys Primary keys to use for the query
     * @param     PropulsionPDO \$con an optional connection object
     *
     * @return    PropulsionObjectCollection the list of results, formatted by the current formatter
     */
    public function findPks(mixed \$keys, ?PropulsionPDO \$con = null) : PropulsionObjectCollection
    {
        \$criteria = \$this->isKeepQuery() ? clone \$this : \$this;
        return \$this
            ->filterByPrimaryKeys(\$keys)
            ->find(\$con);
    }
";
    }

    /**
     * Adds the filterByPrimaryKey method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFilterByPrimaryKey(&$script)
    {
        $script .= "
    /**
     * Filter the query by primary key
     *
     * @param     mixed \$key Primary key to use for the query
     *
     * @return    static The current query, for fluid interface
     */
    public function filterByPrimaryKey(\$key)
    {";
        $table = $this->getTable();
        $pks = $table->getPrimaryKey();
        if (count($pks) === 1) {
            // simple primary key
            $col = $pks[0];
            $const = $this->getColumnConstant($col);
            $script .= "
        return \$this->addUsingAlias($const, \$key, Criteria::EQUAL);";
        } else {
            // composite primary key
            $i = 0;
            foreach ($pks as $col) {
                $const = $this->getColumnConstant($col);
                $script .= "
        \$this->addUsingAlias($const, \$key[$i], Criteria::EQUAL);";
                $i++;
            }
            $script .= "

        return \$this;";
        }
        $script .= "
    }
";
    }

    /**
     * Adds the filterByPrimaryKey method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFilterByPrimaryKeys(&$script)
    {
        $script .= "
    /**
     * Filter the query by a list of primary keys
     *
     * @param     array \$keys The list of primary key to use for the query
     *
     * @return    static The current query, for fluid interface
     */
    public function filterByPrimaryKeys(\$keys)
    {";
        $table = $this->getTable();
        $pks = $table->getPrimaryKey();
        if (count($pks) === 1) {
            // simple primary key
            $col = $pks[0];
            $const = $this->getColumnConstant($col);
            $script .= "
        return \$this->addUsingAlias($const, \$keys, Criteria::IN);";
        } else {
            // composite primary key
            $script .= "
        if (empty(\$keys)) {
            return \$this->add(null, '1<>1', Criteria::CUSTOM);
        }
        foreach (\$keys as \$key) {";
            $i = 0;
            foreach ($pks as $col) {
                $const = $this->getColumnConstant($col);
                $script .= "
            \$cton$i = \$this->getNewCriterion($const, \$key[$i], Criteria::EQUAL);";
                if ($i>0) {
                    $script .= "
            \$cton0->addAnd(\$cton$i);";
                }
                $i++;
            }
            $script .= "
            \$this->addOr(\$cton0);
        }";
        $script .= "

        return \$this;";
        }
        $script .= "
    }
";
    }

    /**
     * Adds the filterByCol method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFilterByCol(&$script, $col)
    {
        $colPhpName = $col->getPhpName();
        $colName = $col->getName();
        $variableName = $col->getStudlyPhpName();
        $qualifiedName = $this->getColumnConstant($col);
        $script .= "
    /**
     * Filter the query on the $colName column
     *";
        if ($col->isNumericType()) {
            $script .= "
     * Example usage:
     * <code>
     * \$query->filterBy$colPhpName(1234); // WHERE $colName = 1234
     * \$query->filterBy$colPhpName(array(12, 34)); // WHERE $colName IN (12, 34)
     * \$query->filterBy$colPhpName(array('min' => 12)); // WHERE $colName > 12
     * </code>";
            if ($col->isForeignKey()) {
                foreach ($col->getForeignKeys() as $fk) {
                    $script .= "
     *
     * @see       filterBy" . $this->getFKPhpNameAffix($fk) . "()";
                }
            }
            $script .= "
     *
     * @param     mixed \$$variableName The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => \$minValue, 'max' => \$maxValue) for intervals.";
        } elseif ($col->isTemporalType()) {
            $script .= "
     * Example usage:
     * <code>
     * \$query->filterBy$colPhpName('2011-03-14'); // WHERE $colName = '2011-03-14'
     * \$query->filterBy$colPhpName('now'); // WHERE $colName = '2011-03-14'
     * \$query->filterBy$colPhpName(array('max' => 'yesterday')); // WHERE $colName > '2011-03-13'
     * </code>
     *
     * @param     mixed \$$variableName The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => \$minValue, 'max' => \$maxValue) for intervals.";
        } elseif ($col->getType() == PropulsionTypes::PHP_ARRAY) {
            $script .= "
     * @param     array \$$variableName The values to use as filter.";
        } elseif ($col->isTextType()) {
            $script .= "
     * Example usage:
     * <code>
     * \$query->filterBy$colPhpName('fooValue');   // WHERE $colName = 'fooValue'
     * \$query->filterBy$colPhpName('%fooValue%'); // WHERE $colName LIKE '%fooValue%'
     * </code>
     *
     * @param     string \$$variableName The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)";
        } elseif ($col->isBooleanType()) {
            $script .= "
     * Example usage:
     * <code>
     * \$query->filterBy$colPhpName(true); // WHERE $colName = true
     * \$query->filterBy$colPhpName('yes'); // WHERE $colName = true
     * </code>
     *
     * @param     boolean|string \$$variableName The value to use as filter.
     *              Non-boolean arguments are converted using the following rules:
     *                * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *                * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     *              Check on string values is case insensitive (so 'FaLsE' is seen as 'false').";
        } else {
            $script .= "
     * @param     mixed \$$variableName The value to use as filter";
        }
        $script .= "
     * @param     string \$comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return    static The current query, for fluid interface
     */
    public function filterBy$colPhpName(\$$variableName = null, \$comparison = null)
    {";
        if ($col->isPrimaryKey() && ($col->getType() == PropulsionTypes::INTEGER || $col->getType() == PropulsionTypes::BIGINT)) {
            $script .= "
        if (is_array(\$$variableName) && null === \$comparison) {
            \$comparison = Criteria::IN;
        }";
        } elseif ($col->isNumericType() || $col->isTemporalType()) {
            $script .= "
        if (is_array(\$$variableName)) {
            \$useMinMax = false;
            if (isset(\${$variableName}['min'])) {
                \$this->addUsingAlias($qualifiedName, \${$variableName}['min'], Criteria::GREATER_EQUAL);
                \$useMinMax = true;
            }
            if (isset(\${$variableName}['max'])) {
                \$this->addUsingAlias($qualifiedName, \${$variableName}['max'], Criteria::LESS_EQUAL);
                \$useMinMax = true;
            }
            if (\$useMinMax) {
                return \$this;
            }
            if (null === \$comparison) {
                \$comparison = Criteria::IN;
            }
        }";
        } elseif ($col->getType() == PropulsionTypes::OBJECT) {
            $script .= "
        if (is_object(\$$variableName)) {
            \$$variableName = serialize(\$$variableName);
        }";
        } elseif ($col->getType() == PropulsionTypes::PHP_ARRAY) {
            $script .= "
        \$key = \$this->getAliasedColName($qualifiedName);
        if (null === \$comparison || \$comparison == Criteria::CONTAINS_ALL) {
            foreach (\$$variableName as \$value) {
                \$value = '%| ' . \$value . ' |%';
                if(\$this->containsKey(\$key)) {
                    \$this->addAnd(\$key, \$value, Criteria::LIKE);
                } else {
                    \$this->add(\$key, \$value, Criteria::LIKE);
                }
            }
            return \$this;
        } elseif (\$comparison == Criteria::CONTAINS_SOME) {
            foreach (\$$variableName as \$value) {
                \$value = '%| ' . \$value . ' |%';
                if(\$this->containsKey(\$key)) {
                    \$this->addOr(\$key, \$value, Criteria::LIKE);
                } else {
                    \$this->add(\$key, \$value, Criteria::LIKE);
                }
            }
            return \$this;
        } elseif (\$comparison == Criteria::CONTAINS_NONE) {
            foreach (\$$variableName as \$value) {
                \$value = '%| ' . \$value . ' |%';
                if(\$this->containsKey(\$key)) {
                    \$this->addAnd(\$key, \$value, Criteria::NOT_LIKE);
                } else {
                    \$this->add(\$key, \$value, Criteria::NOT_LIKE);
                }
            }
            \$this->addOr(\$key, null, Criteria::ISNULL);
            return \$this;
        }";
        } elseif ($col->getType() == PropulsionTypes::ENUM) {
            $script .= "
        \$valueSet = " . $this->getPeerClassname() . "::getValueSet(" . $this->getColumnConstant($col) . ");
        if (is_scalar(\$$variableName)) {
            if (!in_array(\$$variableName, \$valueSet)) {
                throw new PropulsionException(sprintf('Value \"%s\" is not accepted in this enumerated column', \$$variableName));
            }
            \$$variableName = array_search(\$$variableName, \$valueSet);
        } elseif (is_array(\$$variableName)) {
            \$convertedValues = array();
            foreach (\$$variableName as \$value) {
                if (!in_array(\$value, \$valueSet)) {
                    throw new PropulsionException(sprintf('Value \"%s\" is not accepted in this enumerated column', \$value));
                }
                \$convertedValues []= array_search(\$value, \$valueSet);
            }
            \$$variableName = \$convertedValues;
            if (null === \$comparison) {
                \$comparison = Criteria::IN;
            }
        }";
        } elseif ($col->isTextType()) {
            $script .= "
        if (null === \$comparison) {
            if (is_array(\$$variableName)) {
                \$comparison = Criteria::IN;
            } elseif (\$$variableName !== null && preg_match('/[\%\*]/', \$$variableName)) {
                \$$variableName = str_replace('*', '%', \$$variableName);
                \$comparison = Criteria::LIKE;
            }
        }";
        } elseif ($col->isBooleanType()) {
            $script .= "
        if (is_string(\$$variableName)) {
            \$$colName = in_array(strtolower(\$$variableName), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
        }";
        }
        $script .= "
        return \$this->addUsingAlias($qualifiedName, \$$variableName, \$comparison);
    }
";
    }

    /**
     * Add __call method to delegate unknown filterBy* calls to a foreign relation
     * if the table has a "delegate" behavior configured.
     * This allows tables to act as if they "extend" another table by delegating
     * column filters to the related table's query.
     *
     * @param string &$script The script will be modified in this method.
     */
    protected function addItemDelegationCallMethod(&$script): void
    {
        // Check if this table has a "delegate" behavior
        $delegateBehavior = null;
        $delegateToTable = null;

        foreach ($this->getTable()->getBehaviors() as $behavior) {
            if ($behavior->getName() === 'delegate') {
                $delegateBehavior = $behavior;
                // Get the "to" parameter which specifies which table to delegate to
                $delegateToTable = $behavior->getParameter('to');
                break;
            }
        }

        // Only add the __call method if there's a delegate behavior
        if ($delegateBehavior === null || !$delegateToTable) {
            return;
        }

        // Find the foreign key that references the delegate table
        $delegateForeignKey = null;
        foreach ($this->getTable()->getForeignKeys() as $fk) {
            if ($fk->getForeignTableName() === $delegateToTable) {
                $delegateForeignKey = $fk;
                break;
            }
        }

        if ($delegateForeignKey === null) {
            return;
        }

        // Get the phpName of the foreign key to use in useXXXQuery()
        $fkPhpName = $this->getFKPhpNameAffix($delegateForeignKey);
        $useMethodName = 'use' . $fkPhpName . 'Query';

        $script .= "
    /**
     * Delegate unknown method calls to the {$fkPhpName} relation query.
     * This allows filtering by {$fkPhpName} columns even though they don't exist on this table.
     * This is enabled by the 'delegate' behavior in the schema.
     *
     * @param string \$name The method name
     * @param array \$arguments The method arguments
     * @return mixed
     * @throws \\Propulsion\\Exception\\PropulsionException
     */
    public function __call(\$name, \$arguments)
    {
        // Try to handle it via the parent's __call first (for standard magic methods)
        try {
            return parent::__call(\$name, \$arguments);
        } catch (\\Propulsion\\Exception\\PropulsionException \$e) {
            // If it's a filterBy* method that failed, try delegating to the related table
            if (str_starts_with(\$name, 'filterBy')) {
                // Attempt to delegate to the related query
                try {
                    \$relatedQuery = \$this->{$useMethodName}();
                    \$result = call_user_func_array([\$relatedQuery, \$name], \$arguments);
                    return \$result->endUse();
                } catch (\\Exception \$delegateException) {
                    // If that also fails, throw the original exception
                    throw \$e;
                }
            }

            // If it's not a filterBy method, throw the original exception
            throw \$e;
        }
    }
";
    }

    /**
     * Adds the singular filterByCol method for an Arry column.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFilterByArrayCol(&$script, $col)
    {
        $colPhpName = $col->getPhpName();
        $singularPhpName = rtrim($colPhpName, 's');
        $colName = $col->getName();
        $variableName = $col->getStudlyPhpName();
        $qualifiedName = $this->getColumnConstant($col);
        $script .= "
    /**
     * Filter the query on the $colName column
     * @param     mixed \$$variableName The value to use as filter
     * @param     string \$comparison Operator to use for the column comparison, defaults to Criteria::CONTAINS_ALL
     *
     * @return    static The current query, for fluid interface
     */
    public function filterBy$singularPhpName(\$$variableName = null, \$comparison = null)
    {
        if (null === \$comparison || \$comparison == Criteria::CONTAINS_ALL) {
            if (is_scalar(\$$variableName)) {
                \$$variableName = '%| ' . \$$variableName . ' |%';
                \$comparison = Criteria::LIKE;
            }
        } elseif (\$comparison == Criteria::CONTAINS_NONE) {
            \$$variableName = '%| ' . \$$variableName . ' |%';
            \$comparison = Criteria::NOT_LIKE;
            \$key = \$this->getAliasedColName($qualifiedName);
            if(\$this->containsKey(\$key)) {
                \$this->addAnd(\$key, \$$variableName, \$comparison);
            } else {
                \$this->addAnd(\$key, \$$variableName, \$comparison);
            }
            \$this->addOr(\$key, null, Criteria::ISNULL);
            return \$this;
        }
        return \$this->addUsingAlias($qualifiedName, \$$variableName, \$comparison);
    }
";
    }

    /**
     * Adds the filterByFk method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFilterByFk(&$script, $fk)
    {
        $this->declareClasses('PropulsionObjectCollection', 'PropulsionException');
        $table = $this->getTable();
        $queryClass = $this->getStubQueryBuilder()->getClassname();
        $fkTable = $fk->getForeignTable();
        $fkStubObjectBuilder = $this->getNewStubObjectBuilder($fkTable);
        $this->declareClassFromBuilder($fkStubObjectBuilder);
        $fkPhpName = $fkStubObjectBuilder->getClassname();
        $relationName = $this->getFKPhpNameAffix($fk);
        $objectName = '$' . $fkTable->getStudlyPhpName();
        $script .= "
    /**
     * Filter the query by a related $fkPhpName object
     *";
        if ($fk->isComposite()) {
            $script .= "
     * @param     $fkPhpName $objectName The related object to use as filter";
        } else {
            $script .= "
     * @param     $fkPhpName|PropulsionObjectCollection $objectName The related object(s) to use as filter";
        }
        $script .= "
     * @param     string \$comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return    static The current query, for fluid interface
     */
    public function filterBy$relationName($objectName, \$comparison = null)
    {
        if ($objectName instanceof $fkPhpName) {
            return \$this";
        foreach ($fk->getLocalForeignMapping() as $localColumn => $foreignColumn) {
            $localColumnObject = $table->getColumn($localColumn);
            $foreignColumnObject = $fkTable->getColumn($foreignColumn);
            $script .= "
                ->addUsingAlias(" . $this->getColumnConstant($localColumnObject) . ", " . $objectName . "->get" . $foreignColumnObject->getPhpName() . "(), \$comparison)";
        }
        $script .= ";";
        if (!$fk->isComposite()) {
            $localColumnConstant = $this->getColumnConstant($fk->getLocalColumn());
            $foreignColumnName = $fk->getForeignColumn()->getPhpName();
            $script .= "
        } elseif ($objectName instanceof PropulsionObjectCollection) {
            if (null === \$comparison) {
                \$comparison = Criteria::IN;
            }
            return \$this
                ->addUsingAlias($localColumnConstant, {$objectName}->toKeyValue('PrimaryKey', '$foreignColumnName'), \$comparison);";
        }
        $script .= "
        } else {";
        if ($fk->isComposite()) {
            $script .= "
            throw new PropulsionException('filterBy$relationName() only accepts arguments of type $fkPhpName');";
        } else {
            $script .= "
            throw new PropulsionException('filterBy$relationName() only accepts arguments of type $fkPhpName or PropulsionObjectCollection');";
        }
        $script .= "
        }
    }
";
    }

    /**
     * Adds the filterByRefFk method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFilterByRefFk(&$script, $fk)
    {
        $this->declareClasses('PropulsionObjectCollection', 'PropulsionException');
        $table = $this->getTable();
        $queryClass = $this->getStubQueryBuilder()->getClassname();
        $fkTable = $this->getTable()->getDatabase()->getTable($fk->getTableName());
        $fkStubObjectBuilder = $this->getNewStubObjectBuilder($fkTable);
        $this->declareClassFromBuilder($fkStubObjectBuilder);
        $fkPhpName = $fkStubObjectBuilder->getClassname();
        $relationName = $this->getRefFKPhpNameAffix($fk);
        $objectName = '$' . $fkTable->getStudlyPhpName();
        $script .= "
    /**
     * Filter the query by a related $fkPhpName object
     *
     * @param     $fkPhpName $objectName  the related object to use as filter
     * @param     string \$comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return    static The current query, for fluid interface
     */
    public function filterBy$relationName($objectName, \$comparison = null)
    {
        if ($objectName instanceof $fkPhpName) {
            return \$this";
        foreach ($fk->getForeignLocalMapping() as $localColumn => $foreignColumn) {
            $localColumnObject = $table->getColumn($localColumn);
            $foreignColumnObject = $fkTable->getColumn($foreignColumn);
            $script .= "
                ->addUsingAlias(" . $this->getColumnConstant($localColumnObject) . ", " . $objectName . "->get" . $foreignColumnObject->getPhpName() . "(), \$comparison)";
        }
        $script .= ";";
        if (!$fk->isComposite()) {
            $script .= "
        } elseif ($objectName instanceof PropulsionObjectCollection) {
            return \$this
                ->use{$relationName}Query()
                ->filterByPrimaryKeys({$objectName}->getPrimaryKeys())
                ->endUse();";
        }
        $script .= "
        } else {";
        if ($fk->isComposite()) {
            $script .= "
            throw new PropulsionException('filterBy$relationName() only accepts arguments of type $fkPhpName');";
        } else {
            $script .= "
            throw new PropulsionException('filterBy$relationName() only accepts arguments of type $fkPhpName or PropulsionObjectCollection');";
        }
        $script .= "
        }
    }
";
    }

    /**
     * Adds the joinFk method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addJoinFk(&$script, ForeignKey $fk)
    {
        $table = $this->getTable();
        $queryClass = $this->getStubQueryBuilder()->getClassname();
        $fkTable = $fk->getForeignTable();
        $relationName = $this->getFKPhpNameAffix($fk);
        $joinType = $this->getJoinType($fk);
        $this->addJoinRelated($script, $fkTable, $queryClass, $relationName, $joinType);
    }

    /**
     * Adds the joinRefFk method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addJoinRefFk(&$script, ForeignKey $fk)
    {
        $table = $this->getTable();
        $queryClass = $this->getStubQueryBuilder()->getClassname();
        $fkTable = $this->getTable()->getDatabase()->getTable($fk->getTableName());
        $relationName = $this->getRefFKPhpNameAffix($fk);
        $joinType = $this->getJoinType($fk);
        $this->addJoinRelated($script, $fkTable, $queryClass, $relationName, $joinType);
    }

    /**
     * Adds a joinRelated method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addJoinRelated(&$script, $fkTable, $queryClass, $relationName, $joinType)
    {
        $script .= "
    /**
     * Adds a JOIN clause to the query using the " . $relationName . " relation
     *
     * @param     string \$relationAlias optional alias for the relation
     * @param     string \$joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return    static The current query, for fluid interface
     */
    public function join" . $relationName . "(\$relationAlias = null, \$joinType = " . $joinType . ")
    {
        \$tableMap = \$this->getTableMap();
        \$relationMap = \$tableMap->getRelation('" . $relationName . "');

        // create a ModelJoin object for this join
        \$join = new ModelJoin();
        \$join->setJoinType(\$joinType);
        \$join->setRelationMap(\$relationMap, \$this->useAliasInSQL ? \$this->getModelAlias() : null, \$relationAlias);
        if (\$previousJoin = \$this->getPreviousJoin()) {
            \$join->setPreviousJoin(\$previousJoin);
        }

        // add the ModelJoin to the current object
        if(\$relationAlias) {
            \$this->addAlias(\$relationAlias, \$relationMap->getRightTable()->getName());
            \$this->addJoinObject(\$join, \$relationAlias);
        } else {
            \$this->addJoinObject(\$join, '" . $relationName . "');
        }

        return \$this;
    }
";
    }

    /**
     * Adds the useFkQuery method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addUseFkQuery(&$script, ForeignKey $fk)
    {
        $table = $this->getTable();
        $fkTable = $fk->getForeignTable();
        $fkQueryBuilder = $this->getNewStubQueryBuilder($fkTable);
        $queryClass = $fkQueryBuilder->getClassname();
        if ($namespace = $fkQueryBuilder->getNamespace()) {
            $queryClass = '\\' . $namespace . '\\' . $queryClass;
        }
        $relationName = $this->getFKPhpNameAffix($fk);
        $joinType = $this->getJoinType($fk);
        $this->addUseRelatedQuery($script, $fkTable, $queryClass, $relationName, $joinType);
    }

    /**
     * Adds the useFkQuery method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addUseRefFkQuery(&$script, ForeignKey $fk)
    {
        $table = $this->getTable();
        $fkTable = $this->getTable()->getDatabase()->getTable($fk->getTableName());
        $fkQueryBuilder = $this->getNewStubQueryBuilder($fkTable);
        $queryClass = $fkQueryBuilder->getClassname();
        if ($namespace = $fkQueryBuilder->getNamespace()) {
            $queryClass = '\\' . $namespace . '\\' . $queryClass;
        }
        $relationName = $this->getRefFKPhpNameAffix($fk);
        $joinType = $this->getJoinType($fk);
        $this->addUseRelatedQuery($script, $fkTable, $queryClass, $relationName, $joinType);
    }

    /**
     * Adds a useRelatedQuery method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addUseRelatedQuery(&$script, $fkTable, $queryClass, $relationName, $joinType)
    {
        $script .= "
    /**
     * Use the $relationName relation " . $fkTable->getPhpName() . " object
     *
     * @see       useQuery()
     *
     * @param     string \$relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string \$joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return    $queryClass A secondary query class using the current class as primary query
     */
    public function use" . $relationName . "Query(\$relationAlias = null, \$joinType = " . $joinType . ")
    {
        return \$this
            ->join" . $relationName . "(\$relationAlias, \$joinType)
            ->useQuery(\$relationAlias ? \$relationAlias : '$relationName', '$queryClass');
    }
";
    }

    /**
     * Adds the filterByCrossFK method(s) with modern typing (FQCN param type hints).
     *
     * For backward compatibility, generates BOTH:
     * 1. Direct filter method: filterByUser($user)
     * 2. Cross-reference filter method: filterByUserViaCrossReference($user)
     *
     * @param      string &$script The script will be modified in this method.
     */
    protected function addFilterByCrossFK(&$script, ForeignKey $refFK, ForeignKey $crossFK): void
    {
        $queryClass = $this->getStubQueryBuilder()->getClassname();
        $crossRefTable = $crossFK->getTable();
        $foreignTable = $crossFK->getForeignTable();
        $fkPhpName = $foreignTable->getPhpName();
        $fkFQCN = '\\' . $this->getNewStubObjectBuilder($foreignTable)->getFullyQualifiedClassname();
        $crossTableName = $crossRefTable->getName();
        $relName = $this->getFKPhpNameAffix($crossFK, false) . 'ViaCrossReference';
        $directRelName = $this->getFKPhpNameAffix($crossFK, false);
        $objectName = '$' . $foreignTable->getStudlyPhpName();
        $relationName = $this->getRefFKPhpNameAffix($refFK, false);

        // Generate the DIRECT filter method (this is what generated getters/counters on the
        // related object call, e.g. BaseBookClubList::getBooks() calls filterByBookClubList())
        $script .= "
    /**
     * Filter the query by a related $fkPhpName object
     * via the cross-reference table
     *
     * @param     $fkFQCN $objectName the related object to use as filter
     * @param     string \$comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return    static The current query, for fluid interface
     */
    public function filterBy{$directRelName}($objectName, \$comparison = Criteria::EQUAL): $queryClass
    {
        return \$this
            ->use{$relationName}Query()
            ->filterBy{$directRelName}($objectName, \$comparison)
            ->endUse();
    }
";

        // Generate the explicit cross-reference filter method (an alias, for callers that
        // want to be unambiguous about which relation is being filtered on).
        $script .= "
    /**
     * Filter the query by a related $fkPhpName object
     * using the $crossTableName table as cross reference
     *
     * @param     $fkFQCN $objectName the related object to use as filter
     * @param     string \$comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return    static The current query, for fluid interface
     */
    public function filterBy{$relName}($objectName, \$comparison = Criteria::EQUAL): $queryClass
    {
        return \$this
            ->use{$relationName}Query()
            ->filterBy{$directRelName}($objectName, \$comparison)
            ->endUse();
    }
";
    }

    /**
     * Adds the prune method for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addPrune(&$script)
    {
        $table = $this->getTable();
        $class = $this->getStubObjectBuilder()->getClassname();
        $objectName = '$' . $table->getStudlyPhpName();
        $script .= "
    /**
     * Exclude object from result
     *
     * @param     $class $objectName Object to remove from the list of results
     *
     * @return    static The current query, for fluid interface
     */
    public function prune($objectName = null)
    {
        if ($objectName) {";
        $pks = $table->getPrimaryKey();
        if (count($pks) > 1) {
            $i = 0;
            $conditions = array();
            foreach ($pks as $col) {
                $const = $this->getColumnConstant($col);
                $condName = "'pruneCond" . $i . "'";
                $conditions[]= $condName;
                $script .= "
            \$this->addCond(". $condName . ", \$this->getAliasedColName($const), " . $objectName . "->get" . $col->getPhpName() . "(), Criteria::NOT_EQUAL);";
                $i++;
            }
            $conditionsString = implode(', ', $conditions);
            $script .= "
            \$this->combine(array(" . $conditionsString . "), Criteria::LOGICAL_OR);";
        } else {
            $col = $pks[0];
            $const = $this->getColumnConstant($col);
            $script .= "
            \$this->addUsingAlias($const, " . $objectName . "->get" . $col->getPhpName() . "(), Criteria::NOT_EQUAL);";
        }
        $script .= "
        }

        return \$this;
    }
";
    }

    /**
     * Adds the basePreSelect hook for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addBasePreSelect(&$script)
    {
        $behaviorCode = '';
        $this->applyBehaviorModifier('preSelectQuery', $behaviorCode, "		");
        if (!$behaviorCode) {
            return;
        }
        $script .= "
    /**
     * Code to execute before every SELECT statement
     *
     * @param     PropulsionPDO \$con The connection object used by the query
     */
    protected function basePreSelect(PropulsionPDO \$con): mixed
    {" . $behaviorCode . "

        return \$this->preSelect(\$con);
    }
";
    }

    /**
     * Adds the basePreDelete hook for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addBasePreDelete(&$script)
    {
        $behaviorCode = '';
        $this->applyBehaviorModifier('preDeleteQuery', $behaviorCode, "		");
        if (!$behaviorCode) {
            return;
        }
        $script .= "
    /**
     * Code to execute before every DELETE statement
     *
     * @param     PropulsionPDO \$con The connection object used by the query
     */
    protected function basePreDelete(PropulsionPDO \$con)
    {" . $behaviorCode . "

        return \$this->preDelete(\$con);
    }
";
    }

    /**
     * Adds the basePostDelete hook for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addBasePostDelete(&$script)
    {
        $behaviorCode = '';
        $this->applyBehaviorModifier('postDeleteQuery', $behaviorCode, "		");
        if (!$behaviorCode) {
            return;
        }
        $script .= "
    /**
     * Code to execute after every DELETE statement
     *
     * @param     int \$affectedRows the number of deleted rows
     * @param     PropulsionPDO \$con The connection object used by the query
     */
    protected function basePostDelete(\$affectedRows, PropulsionPDO \$con)
    {" . $behaviorCode . "

        return \$this->postDelete(\$affectedRows, \$con);
    }
";
    }

    /**
     * Adds the basePreUpdate hook for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addBasePreUpdate(&$script)
    {
        $behaviorCode = '';
        $this->applyBehaviorModifier('preUpdateQuery', $behaviorCode, "		");
        if (!$behaviorCode) {
            return;
        }
        $script .= "
    /**
     * Code to execute before every UPDATE statement
     *
     * @param     array \$values The associatiove array of columns and values for the update
     * @param     PropulsionPDO \$con The connection object used by the query
     * @param     boolean \$forceIndividualSaves If false (default), the resulting call is a BasePeer::doUpdate(), ortherwise it is a series of save() calls on all the found objects
     */
    protected function basePreUpdate(&\$values, PropulsionPDO \$con, \$forceIndividualSaves = false)
    {" . $behaviorCode . "

        return \$this->preUpdate(\$values, \$con, \$forceIndividualSaves);
    }
";
    }

    /**
     * Adds the basePostUpdate hook for this object.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addBasePostUpdate(&$script)
    {
        $behaviorCode = '';
        $this->applyBehaviorModifier('postUpdateQuery', $behaviorCode, "		");
        if (!$behaviorCode) {
            return;
        }
        $script .= "
    /**
     * Code to execute after every UPDATE statement
     *
     * @param     int \$affectedRows the number of udated rows
     * @param     PropulsionPDO \$con The connection object used by the query
     */
    protected function basePostUpdate(\$affectedRows, PropulsionPDO \$con)
    {" . $behaviorCode . "

        return \$this->postUpdate(\$affectedRows, \$con);
    }
";
    }

    /**
     * Checks whether any registered behavior on that table has a modifier for a hook
     * @param string $hookName The name of the hook as called from one of this class methods, e.g. "preSave"
     * @return boolean
     */
    public function hasBehaviorModifier($hookName, $modifier = null)
    {
        return parent::hasBehaviorModifier($hookName, 'QueryBuilderModifier');
    }

    /**
     * Checks whether any registered behavior on that table has a modifier for a hook
     * @param string $hookName The name of the hook as called from one of this class methods, e.g. "preSave"
     * @param string &$script The script will be modified in this method.
     */
    public function applyBehaviorModifier($hookName, &$script, $tab = "		")
    {
        return $this->applyBehaviorModifierBase($hookName, 'QueryBuilderModifier', $script, $tab);
    }

    /**
     * Checks whether any registered behavior content creator on that table exists a contentName
     * @param string $contentName The name of the content as called from one of this class methods, e.g. "parentClassname"
     */
    public function getBehaviorContent($contentName)
    {
        return $this->getBehaviorContentBase($contentName, 'QueryBuilderModifier');
    }

}
