<?php

/**
 * This file is part of the Propulsion package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propulsion\Generator\Builder\OM;

/**
 * Generates the empty PHP5 stub query class for use with single table inheritance.
 *
 * This class produces the empty stub class that can be customized with application
 * business logic, custom behavior, etc.
 *
 *
 * @author     François Zaninotto
 */
use Propulsion\Generator\Model\Inheritance;
use Propulsion\Generator\Exception\EngineException;
class QueryInheritanceBuilder extends OMBuilder
{

	/**
	 * The current child "object" we are operating on.
	 */
	protected ?Inheritance $child = null;

	/**
	 * Returns the name of the current class being built.
	 * @return     string
	 */
	public function getUnprefixedClassname()
	{
		$basePrefix = $this->getBuildProperty('basePrefix');
		return (is_string($basePrefix) ? $basePrefix : '') . $this->getNewStubQueryInheritanceBuilder($this->getChild())->getUnprefixedClassname();
	}

	/**
	 * Gets the package for the [base] object classes.
	 * @return     string
	 */
	public function getPackage(): string
	{
		$childPackage = $this->getChild()->getPackage();
		$pkg = $childPackage ?: parent::getPackage();
		return $pkg . "." . $this->getOmPackageSegment();
	}

	public function getNamespace(): ?string
	{
		if ($namespace = parent::getNamespace()) {
			$omns = $this->getGeneratorConfig()->getBuildProperty('namespaceOm');
			if (is_string($omns) && $omns !== '') {
				return $namespace . '\\' . $omns;
			} else {
				return $namespace;
			}
		}
		return null;
	}

	/**
	 * Set the child object that we're operating on currrently.
	 * @param      $child Inheritance
	 */
	public function setChild(Inheritance $child): void
	{
		$this->child = $child;
	}

	/**
	 * Returns the child object we're operating on currently.
	 * @return     Inheritance
	 * @throws     EngineException - if child was not set.
	 */
	public function getChild()
	{
		if (!$this->child) {
			throw new EngineException("The PHP5MultiExtendObjectBuilder needs to be told which child class to build (via setChild() method) before it can build the stub class.");
		}
		return $this->child;
	}

	/**
	 * Returns classpath to parent class.
	 * @return     string
	 */
	protected function getParentClassName(): ?string
	{
		$ancestorClassName = ClassTools::classname($this->getChild()->getAncestor());
		if ($this->getDatabase()->hasTableByPhpName($ancestorClassName)) {
			$ancestorTable = $this->getDatabase()->getTableByPhpName($ancestorClassName);
			if ($ancestorTable === null) {
				throw new EngineException(sprintf('No table with phpName "%s" found in database', $ancestorClassName));
			}
			return $this->getNewStubQueryBuilder($ancestorTable)->getClassname();
		} else {
			// find the inheritance for the parent class
			$childrenColumn = $this->getTable()->getChildrenColumn();
			if ($childrenColumn === null) {
				throw new EngineException(sprintf(
					'Table "%s" has no inheritance column configured; QueryInheritanceBuilder can only be used on tables with single table inheritance',
					$this->getTable()->getName() ?? '(unnamed)'
				));
			}
			foreach ($childrenColumn->getChildren() ?? [] as $child) {
				if ($child->getClassName() == $ancestorClassName) {
					return $this->getNewStubQueryInheritanceBuilder($child)->getClassname();
				}
			}
		}
		return null;
	}

	/**
	 * Adds the include() statements for files that this class depends on or utilizes.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addIncludes(&$script = null): void
	{
		$requiredClassFilePath = $this->getStubQueryBuilder()->getClassFilePath();

		$script .="
require '".$requiredClassFilePath."';
";
	} // addIncludes()

	/**
	 * Adds class phpdoc comment and openning of class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassOpen(&$script): void
	{
		$table = $this->getTable();
		$tableName = $table->getName();
		$tableDesc = $table->getDescription();

		$baseBuilder = $this->getStubQueryBuilder();
		$this->declareClassFromBuilder($baseBuilder);
		$baseClassname = $this->getParentClassName();

		$script .= "
/**
 * Skeleton subclass for representing a query for one of the subclasses of the '$tableName' table.
 *
 * $tableDesc
 *";
		if ($this->getBuildProperty('addTimeStamp')) {
			$now = datefmt_create(
				'en_US',
				\IntlDateFormatter::FULL,
				\IntlDateFormatter::FULL,
				'Europe/Helsinki',
				\IntlDateFormatter::GREGORIAN,
				"yyyy-MM-dd HH:mm:ss"
			);
			$version = $this->getBuildProperty('version');
			$formattedNow = $now !== null ? datefmt_format($now, 0) : false;
			$script .= "
 * This class was autogenerated by Propulsion " . (is_string($version) ? $version : '') . " on:
 *
 * " . ($formattedNow !== false ? $formattedNow : '') . "
 *";
		}
		$script .= "
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 */
class "  .$this->getClassname() . " extends " . $baseClassname . " {
";
	}

	/**
	 * Specifies the methods that are added as part of the stub object class.
	 *
	 * By default there are no methods for the empty stub classes; override this method
	 * if you want to change that behavior.
	 *
	 * @see        AbstractObjectBuilder::addClassBody()
	 */
	protected function addClassBody(string &$script): void
	{
		$this->declareClassFromBuilder($this->getStubPeerBuilder());
		$this->declareClasses('PropulsionPDO', 'Criteria');
		$this->addFactory($script);
		$this->addPreSelect($script);
		$this->addPreUpdate($script);
		$this->addPreDelete($script);
		$this->addDoDeleteAll($script);
	}

	/**
	 * Adds the factory for this object.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addFactory(&$script): void
	{
		$builder = $this->getNewStubQueryInheritanceBuilder($this->getChild());
		$this->declareClassFromBuilder($builder);
		$classname = $builder->getClassname();
		// The base BaseXxxQuery class this stub extends was generated by
		// QueryBuilder, which declares a typed create(?string, ?Criteria): self
		// signature -- match it, or PHP fatals on an incompatible override.
		$signature = "public static function create(?string \$modelAlias = null, ?Criteria \$criteria = null): " . $classname;
		$script .= "
	/**
	 * Returns a new " . $classname . " object.
	 *
	 * @param     string \$modelAlias The alias of a model in the query
	 * @param     Criteria \$criteria Optional Criteria to build the query from
	 *
	 * @return    " . $classname . "
	 */
	" . $signature . "
	{";
		$script .= "
		if (\$criteria instanceof " . $classname . ") {
			return \$criteria;
		}
		\$query = new " . $classname . "();
		if (null !== \$modelAlias) {
			\$query->setModelAlias(\$modelAlias);
		}
		if (\$criteria instanceof Criteria) {
			\$query->mergeWith(\$criteria);
		}
		return \$query;
	}
";
	}

	protected function addPreSelect(string &$script): void
	{
		$child = $this->getChild();
		$col = $child->getColumn();

		$script .= "
	/**
	 * Filters the query to target only " . $child->getClassname() . " objects.
	 */
	public function preSelect(PropulsionPDO \$con): mixed
	{
		" . $this->getClassKeyCondition() . "
		return null;
	}
";
	}

	protected function addPreUpdate(string &$script): void
	{
		$child = $this->getChild();
		$col = $child->getColumn();

		$script .= "
	/**
	 * Filters the query to target only " . $child->getClassname() . " objects.
	 *
	 * @param     array<string, mixed> \$values
	 * @param     bool \$forceIndividualSaves
	 */
	public function preUpdate(array &\$values, PropulsionPDO \$con, \$forceIndividualSaves = false): void
	{
		" . $this->getClassKeyCondition() . "
	}
";
	}

	protected function addPreDelete(string &$script): void
	{
		$child = $this->getChild();
		$col = $child->getColumn();

		$script .= "
	/**
	 * Filters the query to target only " . $child->getClassname() . " objects.
	 */
	public function preDelete(PropulsionPDO \$con): void
	{
		" . $this->getClassKeyCondition() . "
	}
";
	}

	protected function getClassKeyCondition(): string
	{
		$child = $this->getChild();
		$col = $child->getColumn();
		if ($col === null) {
			throw new EngineException(sprintf(
				'Inheritance child "%s" has no key column configured; QueryInheritanceBuilder cannot filter by class key without it',
				$child->getClassName()
			));
		}
		return "\$this->addUsingAlias(" . $col->getConstantName() . ", " . $this->getPeerClassname()."::CLASSKEY_".strtoupper((string) $child->getKey()).");";
	}

	protected function addDoDeleteAll(string &$script): void
	{
		$child = $this->getChild();

		$script .= "
	/**
	 * Issue a DELETE query based on the current ModelCriteria deleting all rows in the table
	 * Having the " . $child->getClassname() . " class.
	 * This method is called by ModelCriteria::deleteAll() inside a transaction
	 *
	 * @param PropulsionPDO \$con a connection object
	 *
	 * @return integer the number of deleted rows
	 */
	public function doDeleteAll(\$con)
	{
		// condition on class key is already added in preDelete()
		return parent::doDelete(\$con);
	}
";
	}

	/**
	 * Closes class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassClose(&$script): void
	{
		$script .= "
} // " . $this->getClassname() . "
";
	}

} // MultiExtensionQueryBuilder
