<?php

/**
 * This file is part of the Propulsion package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */
namespace Propulsion\Generator\Builder\OM;

/**
 * Generates the empty PHP5 stub query class for use with single table inheritance.
 *
 * This class produces the empty stub class that can be customized with application
 * business logic, custom behavior, etc.
 *
 *
 * @author     François Zaninotto
 */
use Propulsion\Generator\Model\Inheritance;
use Propulsion\Generator\Exception\EngineException;
class QueryInheritanceBuilder extends OMBuilder
{

	/**
	 * The current child "object" we are operating on.
	 */
	protected ?Inheritance $child = null;

	/**
	 * Returns the name of the current class being built.
	 * @return     string
	 */
	public function getUnprefixedClassname()
	{
		return $this->getStringBuildProperty('basePrefix') . $this->getNewStubQueryInheritanceBuilder($this->getChild())->getUnprefixedClassname();
	}

	/**
	 * Gets the package for the [base] object classes.
	 * @return     string
	 */
	public function getPackage(): string
	{
		$childPackage = $this->getChild()->getPackage();
		return ($childPackage ?: parent::getPackage()) . "." . $this->getOmPackageSegment();
	}

	public function getNamespace(): ?string
	{
		if ($namespace = parent::getNamespace()) {
			if ($omns = $this->getStringBuildProperty('namespaceOm')) {
				return $namespace . '\\' . $omns;
			} else {
				return $namespace;
			}
		}
		return null;
	}

	/**
	 * Set the child object that we're operating on currrently.
	 * @param      $child Inheritance
	 */
	public function setChild(Inheritance $child): void
	{
		$this->child = $child;
	}

	/**
	 * Returns the child object we're operating on currently.
	 * @return     Inheritance
	 * @throws     EngineException - if child was not set.
	 */
	public function getChild()
	{
		if (!$this->child) {
			throw new EngineException("The PHP5MultiExtendObjectBuilder needs to be told which child class to build (via setChild() method) before it can build the stub class.");
		}
		return $this->child;
	}

	/**
	 * Returns classpath to parent class.
	 *
	 * declareClassFromBuilder()s whichever builder actually answers the name --
	 * not necessarily $this->getStubQueryBuilder() (this table's own root query
	 * stub): a deeper inheritance chain (a child extending another child, not
	 * the table's root class) resolves to a different QueryInheritanceBuilder
	 * instance instead, and only declaring the root stub left that case
	 * emitting `extends SomeOtherChildQuery` with no `use` for it.
	 * @return     string
	 */
	protected function getParentClassName(): ?string
	{
		$ancestorClassName = ClassTools::classname(self::requireNotNull($this->getChild()->getAncestor(), sprintf("Inheritance child '%s' ancestor class name", $this->getChild()->getClassName())));
		$ancestorTable = $this->getDatabase()->getTableByPhpName($ancestorClassName);
		if ($ancestorTable !== null) {
			$builder = $this->getNewStubQueryBuilder($ancestorTable);
			$this->declareClassFromBuilder($builder);
			return $builder->getClassname();
		} else {
			// find the inheritance for the parent class
			$childrenColumn = self::requireNotNull(
				$this->getTable()->getChildrenColumn(),
				sprintf("Table '%s' has no inheritance column", $this->getTable()->getName() ?? '(unnamed)')
			);
			foreach ($childrenColumn->getChildren() ?? [] as $child) {
				if ($child->getClassName() == $ancestorClassName) {
					$builder = $this->getNewStubQueryInheritanceBuilder($child);
					$this->declareClassFromBuilder($builder);
					return $builder->getClassname();
				}
			}
		}
		return null;
	}

	/**
	 * Adds the include() statements for files that this class depends on or utilizes.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addIncludes(&$script = null): void
	{
		$requiredClassFilePath = $this->getStubQueryBuilder()->getClassFilePath();

		$script .="
require '".$requiredClassFilePath."';
";
	} // addIncludes()

	/**
	 * Adds class phpdoc comment and openning of class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassOpen(&$script): void
	{
		$table = $this->getTable();
		$tableName = $table->getName();
		$tableDesc = $table->getDescription();

		$baseClassname = $this->getParentClassName();

		$script .= "
/**
 * Skeleton subclass for representing a query for one of the subclasses of the '$tableName' table.
 *
 * $tableDesc
 *";
		if ($this->getBuildProperty('addTimeStamp')) {
			$now = $this->createGeneratedTimestampFormatter();
			$script .= "
 * This class was autogenerated by Propulsion " . $this->getStringBuildProperty('version') . " on:
 *
 * " . datefmt_format($now, 0) . "
 *";
		}
		$script .= "
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 */
class "  .$this->getClassname() . " extends " . $baseClassname . " {
";
	}

	/**
	 * Specifies the methods that are added as part of the stub object class.
	 *
	 * By default there are no methods for the empty stub classes; override this method
	 * if you want to change that behavior.
	 *
	 * @see        AbstractObjectBuilder::addClassBody()
	 */
	protected function addClassBody(string &$script): void
	{
		$this->declareClassFromBuilder($this->getStubPeerBuilder());
		$this->declareClasses('PropulsionPDO', 'Criteria');
		$this->addFactory($script);
		$this->addPreSelect($script);
		$this->addPreUpdate($script);
		$this->addPreDelete($script);
		$this->addDoDeleteAll($script);
	}

	/**
	 * Adds the factory for this object.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addFactory(&$script): void
	{
		$builder = $this->getNewStubQueryInheritanceBuilder($this->getChild());
		$this->declareClassFromBuilder($builder);
		$classname = $builder->getClassname();
		// The base BaseXxxQuery class this stub extends was generated by
		// QueryBuilder, which declares a typed create(?string, ?Criteria): self
		// signature -- match it, or PHP fatals on an incompatible override.
		$signature = "public static function create(?string \$modelAlias = null, ?Criteria \$criteria = null): " . $classname;
		$script .= "
	/**
	 * Returns a new " . $classname . " object.
	 *
	 * @param     string \$modelAlias The alias of a model in the query
	 * @param     Criteria \$criteria Optional Criteria to build the query from
	 *
	 * @return    " . $classname . "
	 */
	" . $signature . "
	{";
		$script .= "
		if (\$criteria instanceof " . $classname . ") {
			return \$criteria;
		}
		\$query = new " . $classname . "();
		if (null !== \$modelAlias) {
			\$query->setModelAlias(\$modelAlias);
		}
		if (\$criteria instanceof Criteria) {
			\$query->mergeWith(\$criteria);
		}
		return \$query;
	}
";
	}

	protected function addPreSelect(string &$script): void
	{
		$child = $this->getChild();
		$col = $child->getColumn();

		$script .= "
	/**
	 * Filters the query to target only " . $child->getClassname() . " objects.
	 */
	public function preSelect(PropulsionPDO \$con): mixed
	{
		" . $this->getClassKeyCondition() . "
		return null;
	}
";
	}

	protected function addPreUpdate(string &$script): void
	{
		$child = $this->getChild();
		$col = $child->getColumn();

		$script .= "
	/**
	 * Filters the query to target only " . $child->getClassname() . " objects.
	 *
	 * @param     array<string, mixed> \$values
	 * @param     bool \$forceIndividualSaves
	 */
	public function preUpdate(array &\$values, PropulsionPDO \$con, \$forceIndividualSaves = false): void
	{
		" . $this->getClassKeyCondition() . "
	}
";
	}

	protected function addPreDelete(string &$script): void
	{
		$child = $this->getChild();
		$col = $child->getColumn();

		$script .= "
	/**
	 * Filters the query to target only " . $child->getClassname() . " objects.
	 */
	public function preDelete(PropulsionPDO \$con): void
	{
		" . $this->getClassKeyCondition() . "
	}
";
	}

	protected function getClassKeyCondition(): string
	{
		$child = $this->getChild();
		$col = self::requireNotNull($child->getColumn(), "Inheritance child's key column");
		$key = self::requireNotNull($child->getKey(), "Inheritance child's key");
		return "\$this->addUsingAlias(" . $col->getConstantName() . ", " . $this->getPeerClassname()."::CLASSKEY_".strtoupper($key).");";
	}

	protected function addDoDeleteAll(string &$script): void
	{
		$child = $this->getChild();

		$script .= "
	/**
	 * Issue a DELETE query based on the current ModelCriteria deleting all rows in the table
	 * Having the " . $child->getClassname() . " class.
	 * This method is called by ModelCriteria::deleteAll() inside a transaction
	 *
	 * @param PropulsionPDO \$con a connection object
	 *
	 * @return integer the number of deleted rows
	 */
	public function doDeleteAll(\$con)
	{
		// condition on class key is already added in preDelete()
		return parent::doDelete(\$con);
	}
";
	}

	/**
	 * Closes class.
	 * @param      string &$script The script will be modified in this method.
	 */
	protected function addClassClose(&$script): void
	{
		$script .= "
} // " . $this->getClassname() . "
";
	}

} // MultiExtensionQueryBuilder
