<?php

/*
 * This file is part of the Propulsion package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */

namespace Propulsion\Generator\Builder\OM;

/**
 * Generates the PHP 8.4 table map class for user object model (OM).
 *
 * This class produces table mapping classes with modern PHP 8.4 features
 * including typed properties, readonly constants, and enhanced type safety.
 *
 * @author     Modernized for PHP 8.4
 * @package    propel.generator.builder.om
 */
use Propulsion\Generator\Model\IDMethod;
use Propulsion\Generator\Platform\PropelPlatformInterface;
use Propulsion\Generator\Model\Validator;

class TableMapBuilder extends OMBuilder
{

    /**
	 * Gets the package for the map builder classes.
	 * @return     string
	 */
	public function getPackage()
	{
		$pkg = ($this->getTable()->getPackage() ? $this->getTable()->getPackage() : $this->getDatabase()->getPackage());
		if (!$pkg) {
			$pkg = $this->getBuildProperty('targetPackage');
		}
		// Capitalized "Map" (not the legacy PHP5TableMapBuilder's lowercase "map") is
		// intentional, for PSR-4-friendly <SchemaName>/Map (and .../OM) directory naming.
		// Legacy require_once()-based tests that hardcode the old lowercase "bookstore/map/"
		// path need updating to match, rather than this being reverted -- see
		// FieldnameRelatedTest and TableBehaviorTest.
		return $pkg . ".Map";
    }

    /**
     * Returns the name of the current class being built.
     * Inlined from the legacy PHP5TableMapBuilder base -- this class no
     * longer extends it (see KNOWN_ISSUES.md Phase 3).
     * @return     string
     */
    public function getUnprefixedClassname()
    {
        return $this->getTable()->getPhpName() . 'TableMap';
    }

    /**
     * Adds the include() statements for files that this class depends on or utilizes.
     * Inlined from the legacy PHP5TableMapBuilder base.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addIncludes(&$script = null)
    {
    } // addIncludes()

    /**
     * Closes class.
     * Inlined from the legacy PHP5TableMapBuilder base.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addClassClose(&$script)
    {
        $script .= "
} // " . $this->getClassname() . "
";
        $this->applyBehaviorModifier('tableMapFilter', $script, "");
    }

    /**
     * Checks whether any registered behavior on that table has a modifier for a hook.
     * Inlined from the legacy PHP5TableMapBuilder base.
     * @param string $hookName The name of the hook as called from one of this class methods, e.g. "preSave"
     * @return boolean
     */
    public function hasBehaviorModifier($hookName, $modifier = null)
    {
        return parent::hasBehaviorModifier($hookName, 'TableMapBuilderModifier');
    }

    /**
     * Checks whether any registered behavior on that table has a modifier for a hook.
     * Inlined from the legacy PHP5TableMapBuilder base.
     * @param string $hookName The name of the hook as called from one of this class methods, e.g. "preSave"
     * @param string &$script The script will be modified in this method.
     */
    public function applyBehaviorModifier($hookName, &$script, $tab = "\t\t")
    {
        return $this->applyBehaviorModifierBase($hookName, 'TableMapBuilderModifier', $script, $tab);
    }

    /**
     * Adds class phpdoc comment and opening of class with modern PHP 8.4 features.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addClassOpen(&$script): void
    {
        $table = $this->getTable();
        $script .= "

/**
 * This class defines the structure of the '".$table->getName()."' table.
 *
 *";
        if ($this->getBuildProperty('addTimeStamp')) {
            $now = datefmt_create(
                'en_US',
                \IntlDateFormatter::FULL,
                \IntlDateFormatter::FULL,
                'Europe/Helsinki',
                \IntlDateFormatter::GREGORIAN,
                "yyyy-MM-dd HH:mm:ss"
            );
            $script .= "
 * This class was autogenerated by Propulsion " . $this->getBuildProperty('version') . " on:
 *
 * " . datefmt_format($now, time()) . "
 *";
        }
        $script .= "
 *
 * This map class is used by Propulsion to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.".$this->getPackage()."
 */
class ".$this->getClassname()." extends \Propulsion\Map\TableMap
{
";
    }

    /**
     * Adds the class body with modern PHP 8.4 features.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addClassBody(&$script): void
    {
        // Declare all required Propulsion classes with proper namespaces
        $this->declareClass('Propulsion\\Map\\TableMap');
        $this->declareClass('Propulsion\\Map\\RelationMap');
        $this->declareClass('Propulsion\\Propulsion');
        $this->declareClass('Propulsion\\Exception\\PropelException');
        $this->declareClass('\\PDO');
        
        $this->addConstants($script);
        $this->addAttributes($script);
        $this->addInitialize($script);
        $this->addBuildRelations($script);
        $this->addGetBehaviors($script);
    
    }

    /**
     * Adds constants with modern readonly properties.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addConstants(&$script): void
    {
        $table = $this->getTable();
        $platform = $this->getPlatform();
        // Use the stub (concrete) object builder for the correct class name
        $stubObjectBuilder = $this->getStubObjectBuilder();
        $fullyQualifiedClassName = $stubObjectBuilder->getFullyQualifiedClassname();
        
        // Table name constants as readonly properties
        $script .= "
    /**
     * The (class) name of the model this TableMap maps to.
     */
    public const CLASS_NAME = '" . addslashes($fullyQualifiedClassName) . "';

    /**
     * The default database name for this class
     */
    public const DATABASE_NAME = '" . $table->getDatabase()->getName() . "';

    /**
     * The table name for this class
     */
    public const TABLE_NAME = '" . $table->getName() . "';

    /**
     * The related Propulsion class for this table
     */
    public const OM_CLASS = '" . addslashes($fullyQualifiedClassName) . "';

    /**
     * A class that can be returned by this tableMap
     */
    public const CLASS_DEFAULT = '" . $stubObjectBuilder->getClassname() . "';

    /**
     * The total number of columns
     */
    public const NUM_COLUMNS = " . count($table->getColumns()) . ";

    /**
     * The number of lazy-loaded columns
     */
    public const NUM_LAZY_LOAD_COLUMNS = " . count($this->getLazyLoadColumns()) . ";

    /**
     * The number of columns to hydrate (NUM_COLUMNS - NUM_LAZY_LOAD_COLUMNS)
     */
    public const NUM_HYDRATE_COLUMNS = " . (count($table->getColumns()) - count($this->getLazyLoadColumns())) . ";
";

        // Add column constants
        $colIdx = 0;
        foreach ($table->getColumns() as $col) {
            $script .= "
    /**
     * the column name for the " . strtoupper($col->getName()) . " field
     */
    public const " . strtoupper($col->getName()) . " = '" . $table->getName() . '.' . $col->getName() . "';
";
            $colIdx++;
        }

        // Add column position constants
        $colIdx = 0;
        foreach ($table->getColumns() as $col) {
            $script .= "
    /**
     * The default string format for model objects of the related table
     */
    public const " . strtoupper($col->getName()) . "_NUM = " . $colIdx . ";
";
            $colIdx++;
        }
    }

    /**
     * Adds typed static properties for table metadata.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addAttributes(&$script): void
    {
        $table = $this->getTable();
        
        $script .= "
    /**
     * Array of column names mapped to their positions
     * @var array<string, int>
     */
    public static array \$fieldNames = [";
        
        $first = true;
        foreach ($table->getColumns() as $col) {
            if (!$first) {
                $script .= ",";
            }
            $script .= "\n        '" . strtoupper($col->getName()) . "' => " . (array_search($col, $table->getColumns()));
            $first = false;
        }
        
        $script .= "
    ];

    /**
     * Array of column types mapped to their positions
     * @var array<int, string>
     */
    public static array \$fieldKeys = [";
        
        $first = true;
        foreach ($table->getColumns() as $col) {
            if (!$first) {
                $script .= ",";
            }
            $script .= "\n        " . (array_search($col, $table->getColumns())) . " => '" . strtoupper($col->getName()) . "'";
            $first = false;
        }
        
        $script .= "
    ];
";
    }

    /**
     * Adds the addInitialize method with modern typing.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addInitialize(&$script): void
    {
        $table = $this->getTable();
        $platform = $this->getPlatform();
        
        $script .= "
    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws \\Exception
     */
    public function initialize(): void
    {
        // attributes
        \$this->setName('" . $table->getName() . "');
        \$this->setPhpName('" . $table->getPhpName() . "');
        \$this->setClassname('" . addslashes($this->getStubObjectBuilder()->getFullyQualifiedClassname()) . "');
        \$this->setPackage('" . $this->getPackage() . "');";

        if ($table->getIdMethod() == IDMethod::NATIVE) {
            $script .= "
        \$this->setUseIdGenerator(true);";
            
            if ($table->getIdMethodParameters()) {
                $params = $table->getIdMethodParameters();
                $imp = $params[0];
                $script .= "
        \$this->setPrimaryKeyMethodInfo('" . $imp->getValue() . "');";
            } elseif ($platform->getNativeIdMethod() == PropelPlatformInterface::SEQUENCE || $platform->getNativeIdMethod() == PropelPlatformInterface::SERIAL) {
                $script .= "
        \$this->setPrimaryKeyMethodInfo('" . $platform->getSequenceName($table) . "');";
            }
        } else {
            $script .= "
        \$this->setUseIdGenerator(false);";
        }

        if ($table->getIsCrossRef()) {
            $script .= "
        \$this->setIsCrossRef(true);";
        }

        if ($table->getChildrenColumn()) {
            $script .= "
        \$this->setSingleTableInheritance(true);";
        }

        $script .= "
        // columns";
        
        foreach ($table->getColumns() as $col) {
            $cup = strtoupper($col->getName());
            $cfc = $col->getPhpName();
            if (!$col->getSize()) {
                $size = "null";
            } else {
                $size = $col->getSize();
            }
            $default = $col->getDefaultValueString();
            
            if ($col->isPrimaryKey()) {
                if ($col->isForeignKey()) {
                    foreach ($col->getForeignKeys() as $fk) {
                        $script .= "
        \$this->addForeignPrimaryKey('$cup', '$cfc', '".$col->getType()."' , '".$fk->getForeignTableName()."', '".strtoupper($fk->getMappedForeignColumn($col->getName()))."', ".($col->isNotNull() ? 'true' : 'false').", ".$size.", $default);";
                    }
                } else {
                    $script .= "
        \$this->addPrimaryKey('$cup', '$cfc', '".$col->getType()."', ".var_export($col->isNotNull(), true).", ".$size.", $default);";
                }
            } else {
                if ($col->isForeignKey()) {
                    foreach ($col->getForeignKeys() as $fk) {
                        $script .= "
        \$this->addForeignKey('$cup', '$cfc', '".$col->getType()."', '".$fk->getForeignTableName()."', '".strtoupper($fk->getMappedForeignColumn($col->getName()))."', ".($col->isNotNull() ? 'true' : 'false').", ".$size.", $default);";
                    }
                } else {
                    $script .= "
        \$this->addColumn('$cup', '$cfc', '".$col->getType()."', ".var_export($col->isNotNull(), true).", ".$size.", $default);";
                }
            }
            
            if ($col->isEnumType()) {
                $script .= "
        \$this->getColumn('$cup')->setValueSet(" . var_export($col->getValueSet(), true). ");";
            }
            if ($col->isPrimaryString()) {
                $script .= "
        \$this->getColumn('$cup')->setPrimaryString(true);";
            }
        }

        // validators
        $script .= "
        // validators";
        foreach ($table->getValidators() as $val) {
            $col = $val->getColumn();
            $cup = strtoupper($col->getName());
            foreach ($val->getRules() as $rule) {
                if ($val->getTranslate() !== Validator::TRANSLATE_NONE) {
                    $script .= "
        \$this->addValidator('$cup', '".$rule->getName()."', '".$rule->getClass()."', '".str_replace("'", "\'", $rule->getValue())."', ".$val->getTranslate()."('".str_replace("'", "\'", $rule->getMessage())."'));";
                } else {
                    $script .= "
        \$this->addValidator('$cup', '".$rule->getName()."', '".$rule->getClass()."', '".str_replace("'", "\'", $rule->getValue())."', '".str_replace("'", "\'", $rule->getMessage())."');";
                }
            }
        }

        $script .= "
    } // initialize()
";
    }

    /**
     * Adds the buildRelations method with modern typing.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addBuildRelations(&$script): void
    {
        // Collect all related classes that need to be imported
        $relatedClasses = [];
        
        foreach ($this->getTable()->getForeignKeys() as $fkey) {
            $relatedClasses[] = $this->getNewStubObjectBuilder($fkey->getForeignTable())->getFullyQualifiedClassname();
        }
        foreach ($this->getTable()->getReferrers() as $fkey) {
            $relatedClasses[] = $this->getNewStubObjectBuilder($fkey->getTable())->getFullyQualifiedClassname();
        }
        foreach ($this->getTable()->getCrossFks() as $fkList) {
            list($refFK, $crossFK) = $fkList;
            $relatedClasses[] = $this->getNewStubObjectBuilder($crossFK->getForeignTable())->getFullyQualifiedClassname();
        }
        
        // Add imports for all related classes
        foreach (array_unique($relatedClasses) as $className) {
            $this->declareClass($className);
        }
        
        $script .= "
    /**
     * Build the RelationMap objects for this table relationships
     *
     * @return void
     */
    public function buildRelations(): void
    {";
        foreach ($this->getTable()->getForeignKeys() as $fkey) {
            $columnMapping = 'array(';
            foreach ($fkey->getLocalForeignMapping() as $key => $value) {
                $columnMapping .= "'" . strtoupper($key) . "' => '" . strtoupper($value) . "', ";
            }
            $columnMapping .= ')';
            $onDelete = $fkey->hasOnDelete() ? "'" . $fkey->getOnDelete() . "'" : 'null';
            $onUpdate = $fkey->hasOnUpdate() ? "'" . $fkey->getOnUpdate() . "'" : 'null';
            $relatedClassName = $this->getNewStubObjectBuilder($fkey->getForeignTable())->getClassname();
            $script .= "
        \$this->addRelation('" . $this->getFKPhpNameAffix($fkey) . "', $relatedClassName::class, RelationMap::MANY_TO_ONE, $columnMapping, $onDelete, $onUpdate);";
        }
        foreach ($this->getTable()->getReferrers() as $fkey) {
            $relationName = $this->getRefFKPhpNameAffix($fkey);
            $columnMapping = 'array(';
            foreach ($fkey->getForeignLocalMapping() as $key => $value) {
                $columnMapping .= "'" . strtoupper($key) . "' => '" . strtoupper($value) . "', ";
            }
            $columnMapping .= ')';
            $onDelete = $fkey->hasOnDelete() ? "'" . $fkey->getOnDelete() . "'" : 'null';
            $onUpdate = $fkey->hasOnUpdate() ? "'" . $fkey->getOnUpdate() . "'" : 'null';
            $relatedClassName = $this->getNewStubObjectBuilder($fkey->getTable())->getClassname();
            $script .= "
        \$this->addRelation('$relationName', $relatedClassName::class, RelationMap::ONE_TO_" . ($fkey->isLocalPrimaryKey() ? "ONE" : "MANY") .", $columnMapping, $onDelete, $onUpdate";
            if ($fkey->isLocalPrimaryKey()) {
                $script .= ");";
            } else {
                $script .= ", '" . $this->getRefFKPhpNameAffix($fkey, true) . "');";
            }
        }
        foreach ($this->getTable()->getCrossFks() as $fkList) {
            list($refFK, $crossFK) = $fkList;
            $relationName = $this->getFKPhpNameAffix($crossFK);
            $pluralName = "'" . $this->getFKPhpNameAffix($crossFK, true) . "'";
            $onDelete = $crossFK->hasOnDelete() ? "'" . $crossFK->getOnDelete() . "'" : 'null';
            $onUpdate = $crossFK->hasOnUpdate() ? "'" . $crossFK->getOnUpdate() . "'" : 'null';
            $relatedClassName = $this->getNewStubObjectBuilder($crossFK->getForeignTable())->getClassname();
            $script .= "
        \$this->addRelation('$relationName', $relatedClassName::class, RelationMap::MANY_TO_MANY, array(), $onDelete, $onUpdate, $pluralName);";
        }
        $script .= "
    } // buildRelations()
";
    }

    /**
     * Adds behaviors getter with modern array typing.
     * @param      string &$script The script will be modified in this method.
     */
    protected function addGetBehaviors(&$script): void
    {
        $script .= "
    /**
     * Gets the behaviors of this table.
     *
     * @return array<string, array<string, mixed>> A hash with behavior name as key and behavior configuration as values.
     */
    public function getBehaviors(): array
    {
        return [";
        
        foreach ($this->getTable()->getBehaviors() as $behavior) {
            $script .= "
            '" . $behavior->getName() . "' => [";
            foreach ($behavior->getParameters() as $key => $value) {
                $script .= "
                '" . $key . "' => '" . $value . "',";
            }
            $script .= "
            ],";
        }
        
        $script .= "
        ];
    } // getBehaviors()
";
    }
    
    /**
     * Helper method to get lazy load columns
     * @return array
     */
    protected function getLazyLoadColumns()
    {
        $lazyColumns = [];
        foreach ($this->getTable()->getColumns() as $col) {
            if ($col->isLazyLoad()) {
                $lazyColumns[] = $col;
            }
        }
        return $lazyColumns;
    }
}