<?php

/**
 * This file is part of the Propulsion package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @license    MIT License
 */

use PHPUnit\Framework\TestCase;
use Phing\Io\File as PhingFile;
use Propulsion\Generator\Task\PropulsionOMTask;
use Propulsion\Generator\Config\GeneratorConfig;
use Propulsion\Generator\Manager\ModelManager;
use Phing\Type\FileSet as PropulsionFileSet;

require_once dirname(__DIR__, 3) . '/tools/helpers/PhingGeneratorTaskTestHelper.php';

/**
 * Output-parity coverage for the legacy Phing PropulsionOMTask against the modern
 * `bin/propulsion model:build` console path (Propulsion\Generator\Manager\ModelManager) --
 * see KNOWN_ISSUES.md's "Phing Task classes" entry. Uses a small, purpose-built
 * fixture (test/fixtures/generator-parity/schema.xml: two tables, one FK, one
 * built-in behavior) rather than the full bookstore schema, since bookstore also
 * exercises custom dot-path behavior classes that resolve differently depending on
 * which of the two paths' current-working-directory convention is in effect (see
 * that fixture's build.properties) -- an orthogonal concern to whether the two
 * generators themselves agree on output for a given already-loaded data model.
 */
class PropulsionOMTaskTest extends TestCase
{
    private string $fixtureDir;
    private string $phingOutDir;
    private string $consoleOutDir;

    protected function setUp(): void
    {
        parent::setUp();
        $this->fixtureDir = dirname(__DIR__, 3) . '/fixtures/generator-parity';
        $this->phingOutDir = sys_get_temp_dir() . '/propulsion-om-task-test-phing-' . uniqid();
        $this->consoleOutDir = sys_get_temp_dir() . '/propulsion-om-task-test-console-' . uniqid();
        mkdir($this->phingOutDir, 0777, true);
        mkdir($this->consoleOutDir, 0777, true);
    }

    protected function tearDown(): void
    {
        $this->removeDir($this->phingOutDir);
        $this->removeDir($this->consoleOutDir);
        parent::tearDown();
    }

    public function testGeneratedClassesMatchConsolePathByteForByte(): void
    {
        $schemaFile = $this->fixtureDir . '/schema.xml';
        $this->assertFileExists($schemaFile);

        // --- Phing task path -------------------------------------------------
        $project = PhingGeneratorTaskTestHelper::bootProject(['propel.database' => 'pgsql', 'propel.project' => 'generator_parity']);

        $task = new PropulsionOMTask();
        PhingGeneratorTaskTestHelper::configureTask($task, $project, 'propel-om');
        $task->setOutputDirectory(new PhingFile($this->phingOutDir));
        $task->setTargetDatabase('pgsql');
        $task->setTargetPackage('generator_parity');
        $task->setValidate(false);

        $fileset = new PropulsionFileSet();
        $fileset->setProject($project);
        $fileset->setDir(new PhingFile($this->fixtureDir));
        $fileset->createInclude()->setName('schema.xml');
        $task->addSchemaFileset($fileset);

        PhingGeneratorTaskTestHelper::withoutDeprecationNotices(fn () => $task->main());

        // --- Console (ModelManager) path --------------------------------------
        $repoRoot = dirname(__DIR__, 4);
        $config = GeneratorConfig::createFromPropertiesFile(
            $repoRoot . '/generator/default.properties',
            null,
            ['propel.database' => 'pgsql']
        );
        PhingGeneratorTaskTestHelper::withoutDeprecationNotices(
            fn () => (new ModelManager($config, $this->consoleOutDir, 'generator_parity'))->generate([$schemaFile])
        );

        // --- Compare -----------------------------------------------------------
        $phingFiles = $this->relativeFileList($this->phingOutDir);
        $consoleFiles = $this->relativeFileList($this->consoleOutDir);

        sort($phingFiles);
        sort($consoleFiles);
        $this->assertSame($consoleFiles, $phingFiles, 'Both generators should produce the same set of files');
        $this->assertNotEmpty($phingFiles);

        foreach ($phingFiles as $relative) {
            $phingContent = $this->stripTimestamp(file_get_contents($this->phingOutDir . '/' . $relative));
            $consoleContent = $this->stripTimestamp(file_get_contents($this->consoleOutDir . '/' . $relative));
            $this->assertSame(
                $consoleContent,
                $phingContent,
                "Generated file $relative should be identical (modulo autogenerated timestamp) between the Phing task and console paths"
            );
        }
    }

    public function testForeignKeyAndBehaviorAreReflectedInGeneratedCode(): void
    {
        $project = PhingGeneratorTaskTestHelper::bootProject(['propel.database' => 'pgsql']);

        $task = new PropulsionOMTask();
        PhingGeneratorTaskTestHelper::configureTask($task, $project, 'propel-om');
        $task->setOutputDirectory(new PhingFile($this->phingOutDir));
        $task->setTargetDatabase('pgsql');
        // Note: targetPackage only applies to *external*-schema tables (see
        // XmlToAppData::startElement()'s "database"/"table" handling) -- for this
        // single, top-level schema.xml it has no effect, so files land directly
        // under the output dir rather than a package subdirectory.
        $task->setTargetPackage('generator_parity');
        $task->setValidate(false);

        $fileset = new PropulsionFileSet();
        $fileset->setProject($project);
        $fileset->setDir(new PhingFile($this->fixtureDir));
        $fileset->createInclude()->setName('schema.xml');
        $task->addSchemaFileset($fileset);

        PhingGeneratorTaskTestHelper::withoutDeprecationNotices(fn () => $task->main());

        $bookBase = file_get_contents($this->phingOutDir . '/om/BaseParityBook.php');

        // FK spot-check: parity_book.author_id -> parity_author.id should produce a
        // relation accessor on the Book side.
        $this->assertStringContainsString('getParityAuthor', $bookBase);
        $this->assertStringContainsString('setParityAuthor', $bookBase);

        // Behavior spot-check: timestampable should add created_at/updated_at handling.
        $this->assertStringContainsStringIgnoringCase('createdat', $bookBase);
        $this->assertStringContainsStringIgnoringCase('updatedat', $bookBase);
    }

    private function stripTimestamp(string $content): string
    {
        return preg_replace('/^\s*\*\s*\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\s*$/m', ' *', $content);
    }

    /** @return string[] */
    private function relativeFileList(string $dir): array
    {
        $files = [];
        $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS));
        foreach ($iterator as $file) {
            if ($file->isFile()) {
                $files[] = substr($file->getPathname(), strlen($dir) + 1);
            }
        }
        return $files;
    }

    private function removeDir(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }
        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST
        );
        foreach ($iterator as $file) {
            $file->isDir() ? rmdir($file->getPathname()) : unlink($file->getPathname());
        }
        rmdir($dir);
    }
}
