<?php

/**
 * Legacy (pre-namespace) global class name -> Propulsion\Generator\ FQCN map,
 * test-suite-only counterpart to runtime/Lib/legacy-class-map.php.
 *
 * This test suite predates the Propel -> Propulsion namespace rename entirely:
 * 117 test files reference generator classes (Criteria, ModelCriteria, Behavior,
 * XmlToAppData, MysqlPlatform, ...) by their bare historic name, with no `use`
 * import. Aliased eagerly from bootstrap.php for the same reason the runtime map
 * is eager, not lazy: `catch (SomeException $e)` does not trigger autoloading in
 * PHP, so an alias created only on first reference could still be missing the
 * first time a catch block needs it.
 *
 * This map also carries a parallel set of entries keyed by the *new* bare
 * Propulsion* names (PropulsionConvertConfTask, ...), for the same reason
 * described in runtime/Lib/legacy-class-map.php: some test files reference
 * generator classes by their bare *current* name too. The original bare
 * legacy keys are left exactly as they were; nothing here is renamed, only
 * added to.
 *
 * @return array<string,string>
 */
return [
    'AbstractObjectBuilder' => 'Propulsion\\Generator\\Builder\\OM\\AbstractObjectBuilder',
    'AbstractPeerBuilder' => 'Propulsion\\Generator\\Builder\\OM\\AbstractPeerBuilder',
    'AbstractSchemaManager' => 'Propulsion\\Generator\\Manager\\AbstractSchemaManager',
    'AggregateColumnBehavior' => 'Propulsion\\Generator\\Behavior\\AggregateColumn\\AggregateColumnBehavior',
    'AggregateColumnRelationBehavior' => 'Propulsion\\Generator\\Behavior\\AggregateColumn\\AggregateColumnRelationBehavior',
    'AlternativeCodingStandardsBehavior' => 'Propulsion\\Generator\\Behavior\\AlternativeCodingStandardsBehavior',
    'AppData' => 'Propulsion\\Generator\\Model\\AppData',
    'ArchivableBehavior' => 'Propulsion\\Generator\\Behavior\\Archivable\\ArchivableBehavior',
    'ArchivableBehaviorObjectBuilderModifier' => 'Propulsion\\Generator\\Behavior\\Archivable\\ArchivableBehaviorObjectBuilderModifier',
    'ArchivableBehaviorQueryBuilderModifier' => 'Propulsion\\Generator\\Behavior\\Archivable\\ArchivableBehaviorQueryBuilderModifier',
    'AutoAddPkBehavior' => 'Propulsion\\Generator\\Behavior\\AutoAddPkBehavior',
    'BaseSchemaParser' => 'Propulsion\\Generator\\Reverse\\BaseSchemaParser',
    'Behavior' => 'Propulsion\\Generator\\Model\\Behavior',
    'ClassTools' => 'Propulsion\\Generator\\Builder\\OM\\ClassTools',
    'Column' => 'Propulsion\\Generator\\Model\\Column',
    'ColumnDefaultValue' => 'Propulsion\\Generator\\Model\\ColumnDefaultValue',
    'ColumnValue' => 'Propulsion\\Generator\\Builder\\Util\\ColumnValue',
    'ConcreteInheritanceBehavior' => 'Propulsion\\Generator\\Behavior\\ConcreteInheritance\\ConcreteInheritanceBehavior',
    'ConcreteInheritanceParentBehavior' => 'Propulsion\\Generator\\Behavior\\ConcreteInheritance\\ConcreteInheritanceParentBehavior',
    'ConstraintNameGenerator' => 'Propulsion\\Generator\\Model\\ConstraintNameGenerator',
    'DataModelBuilder' => 'Propulsion\\Generator\\Builder\\DataModelBuilder',
    'DataRow' => 'Propulsion\\Generator\\Builder\\Util\\DataRow',
    'DataSQLBuilder' => 'Propulsion\\Generator\\Builder\\SQL\\DataSQLBuilder',
    'Database' => 'Propulsion\\Generator\\Model\\Database',
    'DefaultEnglishPluralizer' => 'Propulsion\\Generator\\Builder\\Util\\DefaultEnglishPluralizer',
    'DefaultPlatform' => 'Propulsion\\Generator\\Platform\\DefaultPlatform',
    'DelegateBehavior' => 'Propulsion\\Generator\\Behavior\\DelegateBehavior',
    'Domain' => 'Propulsion\\Generator\\Model\\Domain',
    'EngineException' => 'Propulsion\\Generator\\Exception\\EngineException',
    'ExtensionNodeBuilder' => 'Propulsion\\Generator\\Builder\\OM\\ExtensionNodeBuilder',
    'ExtensionNodePeerBuilder' => 'Propulsion\\Generator\\Builder\\OM\\ExtensionNodePeerBuilder',
    'ExtensionObjectBuilder' => 'Propulsion\\Generator\\Builder\\OM\\ExtensionObjectBuilder',
    'ExtensionPeerBuilder' => 'Propulsion\\Generator\\Builder\\OM\\ExtensionPeerBuilder',
    'ExtensionQueryBuilder' => 'Propulsion\\Generator\\Builder\\OM\\ExtensionQueryBuilder',
    'ExtensionQueryInheritanceBuilder' => 'Propulsion\\Generator\\Builder\\OM\\ExtensionQueryInheritanceBuilder',
    'ForeignKey' => 'Propulsion\\Generator\\Model\\ForeignKey',
    'GeneratorConfig' => 'Propulsion\\Generator\\Config\\GeneratorConfig',
    'GeneratorConfigInterface' => 'Propulsion\\Generator\\Config\\GeneratorConfigInterface',
    'I18nBehavior' => 'Propulsion\\Generator\\Behavior\\I18n\\I18nBehavior',
    'I18nBehaviorObjectBuilderModifier' => 'Propulsion\\Generator\\Behavior\\I18n\\I18nBehaviorObjectBuilderModifier',
    'I18nBehaviorPeerBuilderModifier' => 'Propulsion\\Generator\\Behavior\\I18n\\I18nBehaviorPeerBuilderModifier',
    'I18nBehaviorQueryBuilderModifier' => 'Propulsion\\Generator\\Behavior\\I18n\\I18nBehaviorQueryBuilderModifier',
    'IDMethod' => 'Propulsion\\Generator\\Model\\IDMethod',
    'IdMethodParameter' => 'Propulsion\\Generator\\Model\\IdMethodParameter',
    'Index' => 'Propulsion\\Generator\\Model\\Index',
    'Inheritance' => 'Propulsion\\Generator\\Model\\Inheritance',
    'InitCommand' => 'Propulsion\\Generator\\Command\\InitCommand',
    'InterfaceBuilder' => 'Propulsion\\Generator\\Builder\\OM\\InterfaceBuilder',
    'ModelBuildCommand' => 'Propulsion\\Generator\\Command\\ModelBuildCommand',
    'ModelManager' => 'Propulsion\\Generator\\Manager\\ModelManager',
    'MssqlDataSQLBuilder' => 'Propulsion\\Generator\\Builder\\SQL\\MSSQL\\MssqlDataSQLBuilder',
    'MssqlPlatform' => 'Propulsion\\Generator\\Platform\\MssqlPlatform',
    'MssqlSchemaParser' => 'Propulsion\\Generator\\Reverse\\MSSQL\\MssqlSchemaParser',
    'MultiExtendObjectBuilder' => 'Propulsion\\Generator\\Builder\\OM\\MultiExtendObjectBuilder',
    'MysqlDataSQLBuilder' => 'Propulsion\\Generator\\Builder\\SQL\\MySQL\\MysqlDataSQLBuilder',
    'MysqlPlatform' => 'Propulsion\\Generator\\Platform\\MysqlPlatform',
    'MysqlSchemaParser' => 'Propulsion\\Generator\\Reverse\\MySQL\\MysqlSchemaParser',
    'NameFactory' => 'Propulsion\\Generator\\Model\\NameFactory',
    'NameGenerator' => 'Propulsion\\Generator\\Model\\NameGenerator',
    'NestedSetBehavior' => 'Propulsion\\Generator\\Behavior\\NestedSet\\NestedSetBehavior',
    'NestedSetBehaviorObjectBuilderModifier' => 'Propulsion\\Generator\\Behavior\\NestedSet\\NestedSetBehaviorObjectBuilderModifier',
    'NestedSetBehaviorPeerBuilderModifier' => 'Propulsion\\Generator\\Behavior\\NestedSet\\NestedSetBehaviorPeerBuilderModifier',
    'NestedSetBehaviorQueryBuilderModifier' => 'Propulsion\\Generator\\Behavior\\NestedSet\\NestedSetBehaviorQueryBuilderModifier',
    'NestedSetBuilder' => 'Propulsion\\Generator\\Builder\\OM\\NestedSetBuilder',
    'NestedSetPeerBuilder' => 'Propulsion\\Generator\\Builder\\OM\\NestedSetPeerBuilder',
    'NodeBuilder' => 'Propulsion\\Generator\\Builder\\OM\\NodeBuilder',
    'NodePeerBuilder' => 'Propulsion\\Generator\\Builder\\OM\\NodePeerBuilder',
    'OMBuilder' => 'Propulsion\\Generator\\Builder\\OM\\OMBuilder',
    'ObjectBuilder' => 'Propulsion\\Generator\\Builder\\OM\\ObjectBuilder',
    'OracleDataSQLBuilder' => 'Propulsion\\Generator\\Builder\\SQL\\Oracle\\OracleDataSQLBuilder',
    'OraclePlatform' => 'Propulsion\\Generator\\Platform\\OraclePlatform',
    'OracleSchemaParser' => 'Propulsion\\Generator\\Reverse\\Oracle\\OracleSchemaParser',
    'PeerBuilder' => 'Propulsion\\Generator\\Builder\\OM\\PeerBuilder',
    'PgsqlDataSQLBuilder' => 'Propulsion\\Generator\\Builder\\SQL\\PgSQL\\PgsqlDataSQLBuilder',
    'PgsqlPlatform' => 'Propulsion\\Generator\\Platform\\PgsqlPlatform',
    'PgsqlSchemaParser' => 'Propulsion\\Generator\\Reverse\\PgSQL\\PgsqlSchemaParser',
    'PgsqlSchemaParserV12Plus' => 'Propulsion\\Generator\\Reverse\\PgSQL\\PgsqlSchemaParser',
    'PhpNameGenerator' => 'Propulsion\\Generator\\Model\\PhpNameGenerator',
    'Pluralizer' => 'Propulsion\\Generator\\Builder\\Util\\Pluralizer',
    'PropelColumnComparator' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionColumnComparator',
    'PropelColumnDiff' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionColumnDiff',
    'PropelDatabaseComparator' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionDatabaseComparator',
    'PropelDatabaseDiff' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionDatabaseDiff',
    'PropelForeignKeyComparator' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionForeignKeyComparator',
    'PropelIndexComparator' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionIndexComparator',
    'PropelMigrationManager' => 'Propulsion\\Generator\\Util\\PropulsionMigrationManager',
    'PropelPHPParser' => 'Propulsion\\Generator\\Util\\PropulsionPHPParser',
    'PropelPlatformInterface' => 'Propulsion\\Generator\\Platform\\PropulsionPlatformInterface',
    'PropelQuickBuilder' => 'Propulsion\\Generator\\Util\\PropulsionQuickBuilder',
    'PropelSQLParser' => 'Propulsion\\Generator\\Util\\PropulsionSQLParser',
    'PropelTableComparator' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionTableComparator',
    'PropelTableDiff' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionTableDiff',
    'PropelTemplate' => 'Propulsion\\Generator\\Builder\\Util\\PropulsionTemplate',
    'PropelTypes' => 'Propulsion\\Generator\\Model\\PropulsionTypes',
    'PropulsionColumnComparator' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionColumnComparator',
    'PropulsionColumnDiff' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionColumnDiff',
    'PropulsionDatabaseComparator' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionDatabaseComparator',
    'PropulsionDatabaseDiff' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionDatabaseDiff',
    'PropulsionForeignKeyComparator' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionForeignKeyComparator',
    'PropulsionIndexComparator' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionIndexComparator',
    'PropulsionMigrationManager' => 'Propulsion\\Generator\\Util\\PropulsionMigrationManager',
    'PropulsionPHPParser' => 'Propulsion\\Generator\\Util\\PropulsionPHPParser',
    'PropulsionPlatformInterface' => 'Propulsion\\Generator\\Platform\\PropulsionPlatformInterface',
    'PropulsionQuickBuilder' => 'Propulsion\\Generator\\Util\\PropulsionQuickBuilder',
    'PropulsionSQLParser' => 'Propulsion\\Generator\\Util\\PropulsionSQLParser',
    'PropulsionTableComparator' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionTableComparator',
    'PropulsionTableDiff' => 'Propulsion\\Generator\\Model\\Diff\\PropulsionTableDiff',
    'PropulsionTemplate' => 'Propulsion\\Generator\\Builder\\Util\\PropulsionTemplate',
    'PropulsionTypes' => 'Propulsion\\Generator\\Model\\PropulsionTypes',
    'QueryBuilder' => 'Propulsion\\Generator\\Builder\\OM\\QueryBuilder',
    'QueryCacheBehavior' => 'Propulsion\\Generator\\Behavior\\QueryCache\\QueryCacheBehavior',
    'QueryInheritanceBuilder' => 'Propulsion\\Generator\\Builder\\OM\\QueryInheritanceBuilder',
    'QuickGeneratorConfig' => 'Propulsion\\Generator\\Config\\QuickGeneratorConfig',
    'Rule' => 'Propulsion\\Generator\\Model\\Rule',
    'SchemaException' => 'Propulsion\\Generator\\Exception\\SchemaException',
    'SchemaParser' => 'Propulsion\\Generator\\Reverse\\SchemaParser',
    'ScopedElement' => 'Propulsion\\Generator\\Model\\ScopedElement',
    'SluggableBehavior' => 'Propulsion\\Generator\\Behavior\\Sluggable\\SluggableBehavior',
    'SoftDeleteBehavior' => 'Propulsion\\Generator\\Behavior\\SoftDeleteBehavior',
    'SortableBehavior' => 'Propulsion\\Generator\\Behavior\\Sortable\\SortableBehavior',
    'SortableBehaviorObjectBuilderModifier' => 'Propulsion\\Generator\\Behavior\\Sortable\\SortableBehaviorObjectBuilderModifier',
    'SortableBehaviorPeerBuilderModifier' => 'Propulsion\\Generator\\Behavior\\Sortable\\SortableBehaviorPeerBuilderModifier',
    'SortableBehaviorQueryBuilderModifier' => 'Propulsion\\Generator\\Behavior\\Sortable\\SortableBehaviorQueryBuilderModifier',
    'SqlBuildCommand' => 'Propulsion\\Generator\\Command\\SqlBuildCommand',
    'SqlManager' => 'Propulsion\\Generator\\Manager\\SqlManager',
    'SqlitePlatform' => 'Propulsion\\Generator\\Platform\\SqlitePlatform',
    'SqliteSchemaParser' => 'Propulsion\\Generator\\Reverse\\SQLite\\SqliteSchemaParser',
    'SqlsrvDataSQLBuilder' => 'Propulsion\\Generator\\Builder\\SQL\\Sqlsrv\\SqlsrvDataSQLBuilder',
    'SqlsrvPlatform' => 'Propulsion\\Generator\\Platform\\SqlsrvPlatform',
    'SqlsrvSchemaParser' => 'Propulsion\\Generator\\Reverse\\Sqlsrv\\SqlsrvSchemaParser',
    'StandardEnglishPluralizer' => 'Propulsion\\Generator\\Builder\\Util\\StandardEnglishPluralizer',
    'Table' => 'Propulsion\\Generator\\Model\\Table',
    'TableMapBuilder' => 'Propulsion\\Generator\\Builder\\OM\\TableMapBuilder',
    'TimestampableBehavior' => 'Propulsion\\Generator\\Behavior\\TimestampableBehavior',
    'Unique' => 'Propulsion\\Generator\\Model\\Unique',
    'Validator' => 'Propulsion\\Generator\\Model\\Validator',
    'VendorInfo' => 'Propulsion\\Generator\\Model\\VendorInfo',
    'VersionableBehavior' => 'Propulsion\\Generator\\Behavior\\Versionable\\VersionableBehavior',
    'VersionableBehaviorObjectBuilderModifier' => 'Propulsion\\Generator\\Behavior\\Versionable\\VersionableBehaviorObjectBuilderModifier',
    'VersionableBehaviorPeerBuilderModifier' => 'Propulsion\\Generator\\Behavior\\Versionable\\VersionableBehaviorPeerBuilderModifier',
    'VersionableBehaviorQueryBuilderModifier' => 'Propulsion\\Generator\\Behavior\\Versionable\\VersionableBehaviorQueryBuilderModifier',
    'XMLElement' => 'Propulsion\\Generator\\Model\\XMLElement',
    'XmlToAppData' => 'Propulsion\\Generator\\Builder\\Util\\XmlToAppData',
];
